High level:
This notebook shows all the inconsistencies of field that were produced with dictionaries (and have hebrew in the name) with their respective numeric values for the markers_hebrew table.

The specific analysis below is based on data from 2020-01-13_views_and_main_tables folder from Jan 12, 2020 that can be found here: https://drive.google.com/drive/folders/1zrwfdkedy7jtRRsGi2dEn8zboZAG8_U2?usp=sharing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
pd.options.display.max_rows = 300
pd.options.display.max_columns = 100

In [2]:
markers_raw = pd.read_csv('../../views_and_main_tables_2020_01/markers_hebrew.csv')
m_all = markers_raw[markers_raw['accident_year'] == 2019]

C:\Users\rkrichev\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (23,93) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
m_all.info(null_counts=True, max_cols=200)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53030 entries, 4 to 799333
Data columns (total 101 columns):
id                                           53030 non-null int64
provider_and_id                              53030 non-null int64
provider_code                                53030 non-null int64
provider_code_hebrew                         53030 non-null object
file_type_police                             53030 non-null float64
accident_type                                53030 non-null int64
accident_type_hebrew                         53030 non-null object
accident_severity                            53030 non-null int64
accident_severity_hebrew                     53030 non-null object
accident_timestamp                           53030 non-null object
location_accuracy                            53030 non-null int64
location_accuracy_hebrew                     53030 non-null object
road_type                                    53030 non-null int64
road_type_hebrew                             53030 non-null object
road_shape                                   53030 non-null int64
road_shape_hebrew                            53030 non-null object
day_type                                     53030 non-null int64
day_type_hebrew                              53030 non-null object
police_unit                                  53030 non-null int64
police_unit_hebrew                           53030 non-null object
one_lane                                     53030 non-null int64
one_lane_hebrew                              48614 non-null object
multi_lane                                   53030 non-null int64
multi_lane_hebrew                            4416 non-null object
speed_limit                                  53030 non-null int64
speed_limit_hebrew                           53030 non-null object
road_intactness                              53030 non-null int64
road_intactness_hebrew                       53030 non-null object
road_width                                   53030 non-null int64
road_width_hebrew                            53030 non-null object
road_sign                                    53030 non-null int64
road_sign_hebrew                             53030 non-null object
road_light                                   53030 non-null int64
road_light_hebrew                            53030 non-null object
road_control                                 7106 non-null float64
road_control_hebrew                          7106 non-null object
weather                                      53030 non-null int64
weather_hebrew                               53030 non-null object
road_surface                                 53030 non-null int64
road_surface_hebrew                          53030 non-null object
road_object                                  53030 non-null int64
road_object_hebrew                           53030 non-null object
object_distance                              53030 non-null int64
object_distance_hebrew                       53030 non-null object
didnt_cross                                  53030 non-null int64
didnt_cross_hebrew                           53030 non-null object
cross_mode                                   53030 non-null int64
cross_mode_hebrew                            3185 non-null object
cross_location                               53030 non-null int64
cross_location_hebrew                        2545 non-null object
cross_direction                              53030 non-null int64
cross_direction_hebrew                       53030 non-null object
road1                                        14023 non-null float64
road2                                        13852 non-null float64
km                                           14008 non-null float64
km_raw                                       14008 non-null float64
km_accurate                                  14008 non-null object
road_segment_id                              13660 non-null float64
road_segment_number                          13660 non-null float64
road_segment_name                            13660 non-null object
yishuv_symbol                                53030 non-null int64
yishuv_name                                  38886 non-null object
geo_area                                     53030 non-null int64
geo_area_hebrew                              53030 non-null object
day_night                                    53030 non-null int64
day_night_hebrew                             53030 non-null object
day_in_week                                  53030 non-null int64
day_in_week_hebrew                           53030 non-null object
traffic_light                                53030 non-null int64
traffic_light_hebrew                         53030 non-null object
region                                       42898 non-null float64
region_hebrew                                42898 non-null object
district                                     53030 non-null int64
district_hebrew                              38921 non-null object
natural_area                                 42898 non-null float64
natural_area_hebrew                          38822 non-null object
municipal_status                             42805 non-null float64
municipal_status_hebrew                      42805 non-null object
yishuv_shape                                 42898 non-null float64
yishuv_shape_hebrew                          38921 non-null object
street1                                      28750 non-null float64
street1_hebrew                               27712 non-null object
street2                                      6075 non-null float64
street2_hebrew                               6072 non-null object
house_number                                 32595 non-null float64
non_urban_intersection                       4309 non-null float64
non_urban_intersection_hebrew                4302 non-null object
non_urban_intersection_by_junction_number    4309 non-null object
urban_intersection                           6076 non-null float64
accident_year                                53030 non-null int64
accident_month                               53030 non-null int64
accident_day                                 53030 non-null int64
accident_hour_raw                            53030 non-null int64
accident_hour_raw_hebrew                     53030 non-null object
accident_hour                                53030 non-null int64
accident_minute                              53030 non-null int64
geom                                         52926 non-null object
longitude                                    52926 non-null float64
latitude                                     52926 non-null float64
x                                            52926 non-null float64
y                                            52926 non-null float64
dtypes: float64(21), int64(37), object(43)
memory usage: 41.3+ MB

### Helper functions

In [8]:
def calc_diff_counts_hebrew(data, feat_name):
    data = data[(data[feat_name].isnull() == False) & (data[feat_name + '_hebrew'].isnull() == False)]
    print(f'Shape of data: {data.shape}')
    return data[feat_name].value_counts().reset_index(drop=True) - \
           data[feat_name + '_hebrew'].value_counts().reset_index(drop=True)

def merge_with_hebrew(data, feat_name):
    nums_df = data[feat_name].value_counts().reset_index()
    nums_df.columns = ['index_' + feat_name, 'count']

    hebrew_df = data[feat_name + '_hebrew'].value_counts().reset_index()
    hebrew_df.columns = ['index_' + feat_name + '_hebrew', 'count']

    return pd.merge(nums_df, hebrew_df, how='outer', on='count')

### provider_code and provider_code_hebrew

In [10]:
# provider_code                                53030 non-null int64
# provider_code_hebrew                         53030 non-null object

In [11]:
calc_diff_counts_hebrew(m_all, 'provider_code')

Shape of data: (53030, 101)

0    0
1    0
dtype: int64

### accident_type and accident_type_hebrew

In [12]:
# accident_type                                53030 non-null int64
# accident_type_hebrew                         53030 non-null object

In [13]:
calc_diff_counts_hebrew(m_all, 'accident_type')

Shape of data: (53030, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64

### accident_severity and accident_severity_hebrew

In [15]:
# accident_severity                            53030 non-null int64
# accident_severity_hebrew                     53030 non-null object

In [16]:
calc_diff_counts_hebrew(m_all, 'accident_severity')

Shape of data: (53030, 101)

0    0
1    0
2    0
dtype: int64

In [17]:
### location_accuracy and location_accuracy_hebrew

In [18]:
# location_accuracy                            53030 non-null int64
# location_accuracy_hebrew                     53030 non-null object

In [19]:
calc_diff_counts_hebrew(m_all, 'location_accuracy')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
dtype: int64

### road_type and road_type_hebrew

In [21]:
# road_type                                    53030 non-null int64
# road_type_hebrew                             53030 non-null object

In [22]:
calc_diff_counts_hebrew(m_all, 'road_type')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
dtype: int64

### road_shape and road_shape_hebrew

In [23]:
# road_shape                                   53030 non-null int64
# road_shape_hebrew                            53030 non-null object

In [24]:
calc_diff_counts_hebrew(m_all, 'road_shape')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

### day_type and day_type_hebrew

In [26]:
# day_type                                     53030 non-null int64
# day_type_hebrew                              53030 non-null object

In [27]:
calc_diff_counts_hebrew(m_all, 'day_type')

Shape of data: (53030, 101)

0    0
1    0
2    0
dtype: int64

### police_unit and police_unit_hebrew

In [28]:
# police_unit                                  53030 non-null int64
# police_unit_hebrew                           53030 non-null object

In [29]:
calc_diff_counts_hebrew(m_all, 'police_unit')

Shape of data: (53030, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

### one_lane and one_lane_hebrew

In [ ]:
# one_lane                                     53030 non-null int64
# one_lane_hebrew                              48614 non-null object

In [30]:
m_all[(m_all['one_lane'].isnull() == False) & (m_all['one_lane_hebrew'].isnull() == True)].shape

(4416, 101)

In [31]:
m_all[(m_all['one_lane'].isnull() == False) & (m_all['one_lane_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.416000e+03,4.416000e+03,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.0,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,3159.000000,4416.000000,4416.000000,4416.000000,4416.000000,4416.00000,4416.000000,4416.000000,4416.000000,1714.000000,1696.000000,1713.000000,1713.000000,1.680000e+03,1680.00000,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4391.000000,4416.000000,4391.000000,4389.000000,4391.000000,2596.000000,1569.000000,1012.000000,842.000000,1.570000e+03,4416.0,4416.000000,4416.000000,4416.000000,4416.000000,4416.000000,4414.000000,4414.000000,4414.000000,4414.000000
mean,2.019049e+09,1.224550e+10,1.022645,1.023098,3.147418,2.819520,1.315897,2.204257,8.310915,3.867980,34.170743,0.0,2.628170,2.436594,0.937274,3.000906,3.042799,2.075181,3.274454,1.199049,1.130661,8.692935,8.574728,8.95154,0.557292,0.537817,7.930254,349.498833,512.859080,827.033859,826.733800,3.116545e+06,93.08750,3198.743207,1.018569,2.375000,3.761096,4.433197,5.868823,63.417572,636.882031,40.832536,47.023913,899.814715,809.059273,5110.800395,2912.402613,1.561188e+07,2019.0,5.527853,15.517889,56.121377,13.439085,20.475543,34.930205,32.138643,193532.758269,671736.591074
std,2.873457e+04,2.116299e+09,0.211630,0.213711,2.837742,0.445732,0.725576,1.150288,0.860103,0.560301,18.122893,0.0,0.797427,1.811268,0.296306,1.169255,0.421643,1.886054,2.137681,1.060998,0.793748,1.237359,1.691451,0.43713,1.327939,1.255537,2.648725,1120.067266,1589.288972,962.805973,963.063787,1.035547e+07,165.11529,3346.956113,0.135012,1.900051,1.922446,4.135099,2.767220,30.935493,312.293739,48.597166,41.234820,1180.283526,1038.894454,4978.649852,2927.501835,2.172875e+07,0.0,3.041747,8.699574,22.785856,5.696030,16.777819,0.192629,0.526785,18232.771651,58394.574913
min,2.019000e+09,1.201900e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.0,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,-218.000000,1.001000e+04,0.00000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,101.000000,1.000000,1.000000,0.000000e+00,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.440184,29.493003,146698.000000,378407.000000
25%,2.019024e+09,1.201902e+10,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,8.000000,4.000000,14.000000,0.0,2.000000,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.00000,0.000000,0.000000,9.000000,5.000000,0.000000,120.000000,120.000000,5.003000e+04,20.00000,0.000000,1.000000,1.000000,2.000000,1.000000,4.000000,42.000000,421.000000,0.000000,13.000000,224.750000,222.000000,26.000000,707.000000,7.782526e+06,2019.0,3.000000,8.000000,39.000000,9.000000,0.000000,34.794870,31.822866,180719.000000,636669.750000
50%,2.019050e+09,1.201905e+10,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,8.000000,4.000000,38.000000,0.0,3.000000,1.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.00000,0.000000,0.000000,9.000000,44.000000,0.000000,340.000000,340.000000,4.300200e+05,40.00000,2630.000000,1.000000,1.000000,4.000000,1.000000,5.000000,51.000000,513.000000,0.000000,16.000000,484.000000,451.000000,9999.000000,1963.000000,9.545178e+06,2019.0,5.000000,16.000000,58.000000,14.000000,15.000000,34.900797,32.076588,190867.000000,664882.000000
75%,2.019074e+09,1.201907e+10,1.000000,1.000000,3.000000,3.000000,1.000000,3.000000,9.000000,4.000000,51.000000,0.0,3.000000,4.000000,1.000000,4.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.00000,0.000000,0.000000,9.000000,90.000000,57.000000,1450.000000,1450.000000,9.000940e+05,90.00000,6600.000000,1.000000,5.000000,5.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,996.000000,934.000000,9999.000000,4083.000000,1.593021e+07,2019.0,8.000000,23.000000,74.000000,18.000000,30.000000,35.072065,32.471587,207052.000000,708647.000000
max,2.019100e+09,3.201910e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,0.0,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.00000,9.000000,9.000000,9.000000,9330.000000,9119.000000,4645.000000,4645.000000,9.330000e+07,874.00000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,7001.000000,9999.000000,10443.000000,9.997059e+07,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.771453,33.306394,272256.000000,801333.000000

In [33]:
m_all[m_all['one_lane'] == 0].shape

(4416, 101)

**Null Conclusion:** `one_lane` == 0 is missing

In [35]:
calc_diff_counts_hebrew(m_all, 'one_lane')

Shape of data: (48614, 101)

0    0
1    0
2    0
3    0
dtype: int64

### multi_lane and multi_lane_hebrew

In [ ]:
# multi_lane                                   53030 non-null int64
# multi_lane_hebrew                            4416 non-null object

In [36]:
m_all[(m_all['multi_lane'].isnull() == False) & (m_all['multi_lane_hebrew'].isnull() == True)].shape

(48614, 101)

In [37]:
m_all[(m_all['multi_lane'].isnull() == False) & (m_all['multi_lane_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.861400e+04,4.861400e+04,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.0,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,3947.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,12309.000000,12156.000000,12295.000000,12295.000000,1.198000e+04,11980.000000,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,38507.000000,48614.000000,38507.000000,38416.000000,38507.000000,26154.000000,4506.000000,31583.000000,3467.000000,4.506000e+03,48614.0,48614.000000,48614.000000,48614.000000,48614.000000,48614.000000,48512.000000,48512.000000,48512.000000,48512.000000
mean,2.019050e+09,2.890513e+10,2.688608,2.702267,4.791891,2.964702,1.907537,2.342946,8.909861,3.894084,30.683486,8.141029,0.0,0.232711,0.121446,0.320052,4.745073,8.840972,4.079301,8.001214,7.997367,8.908298,8.929588,8.979121,0.180051,0.110195,8.814992,440.616947,271.575189,709.167385,707.790403,3.870527e+06,112.949583,3524.582384,1.025672,1.957584,3.631258,8.539310,4.030955,54.386617,429.340587,16.698069,21.543252,909.879865,841.749223,8249.418263,2624.235074,1.440293e+07,2019.0,5.881022,15.700416,55.811145,13.389517,18.796129,34.975141,32.185507,197761.095543,676929.634977
std,3.063804e+04,7.251411e+09,0.725141,0.711921,4.033328,0.203816,0.928229,0.885017,0.418422,0.492964,17.858416,2.269380,0.0,0.785600,0.346452,0.905887,0.692575,3.346369,2.365177,2.635733,2.636790,0.671362,0.709481,0.300296,0.919653,0.627615,1.178860,1424.061003,1189.814207,872.147166,873.265116,1.316548e+07,211.478187,3271.551916,0.158155,1.706877,1.848042,1.931789,1.990949,29.448919,209.736188,35.980411,20.366929,1239.587793,940.447702,3789.592197,2828.983657,2.133756e+07,0.0,3.074905,8.763885,19.683312,4.930935,16.562671,0.223663,0.577381,21128.934827,64006.324210
min,2.018012e+09,1.201801e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,1.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,-222.000000,1.001000e+04,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,101.000000,1.000000,1.000000,0.000000e+00,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.284338,29.492253,131783.000000,378324.000000
25%,2.019025e+09,3.201901e+10,3.000000,3.000000,3.000000,3.000000,1.000000,2.000000,9.000000,4.000000,12.000000,9.000000,0.0,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,100.000000,100.000000,4.028000e+04,12.000000,0.000000,1.000000,1.000000,2.000000,9.000000,2.000000,31.000000,245.000000,0.000000,13.000000,210.000000,249.000000,9999.000000,435.000000,6.400205e+05,2019.0,3.000000,8.000000,41.000000,10.000000,0.000000,34.797467,31.893969,180829.000000,644592.000000
50%,2.019050e+09,3.201904e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,20.000000,9.000000,0.0,0.000000,0.000000,0.000000,5.000000,11.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,40.000000,0.000000,330.000000,330.000000,4.001300e+05,40.000000,3000.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,431.000000,0.000000,14.000000,474.000000,509.000000,9999.000000,1277.000000,8.820246e+06,2019.0,6.000000,16.000000,57.000000,14.000000,15.000000,34.920087,32.082614,192669.500000,665527.500000
75%,2.019075e+09,3.201907e+10,3.000000,3.000000,5.000000,3.000000,3.000000,3.000000,9.000000,4.000000,51.000000,9.000000,0.0,0.000000,0.000000,0.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,90.000000,0.000000,1060.000000,1060.000000,9.000700e+05,92.500000,6700.000000,1.000000,1.000000,5.000000,9.000000,5.000000,99.000000,512.000000,0.000000,17.000000,1018.000000,1022.750000,9999.000000,4071.000000,1.434071e+07,2019.0,8.000000,23.000000,70.000000,17.000000,30.000000,35.134088,32.707888,212791.250000,734818.000000
max,2.019100e+09,3.201910e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,0.0,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9974.000000,9977.000000,4760.000000,4760.000000,9.898071e+07,874.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,6606.000000,11111.000000,10447.000000,1.000000e+08,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.808684,33.307069,275932.000000,801408.000000

In [38]:
m_all[m_all['multi_lane'] == 0].shape

(48614, 101)

**Null Conclusion:** `multi_lane` == 0 is missing

In [39]:
calc_diff_counts_hebrew(m_all, 'multi_lane')

Shape of data: (4416, 101)

0    0
1    0
2    0
3    0
4    0
dtype: int64

### speed_limit and speed_limit_hebrew

In [40]:
# speed_limit                                  53030 non-null int64
# speed_limit_hebrew                           53030 non-null object

In [42]:
calc_diff_counts_hebrew(m_all, 'speed_limit')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

### road_intactness and road_intactness_hebrew

In [43]:
# road_intactness                              53030 non-null int64
# road_intactness_hebrew                       53030 non-null object

In [44]:
calc_diff_counts_hebrew(m_all, 'road_intactness')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
dtype: int64

### road_width and road_width_hebrew

In [46]:
# road_width                                   53030 non-null int64
# road_width_hebrew                            53030 non-null object

In [47]:
calc_diff_counts_hebrew(m_all, 'road_width')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

### road_sign and road_sign_hebrew

In [ ]:
# road_sign                                    53030 non-null int64
# road_sign_hebrew                             53030 non-null object

In [49]:
calc_diff_counts_hebrew(m_all, 'road_sign')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
dtype: int64

### road_light and road_light_hebrew

In [50]:
# road_light                                   53030 non-null int64
# road_light_hebrew                            53030 non-null object

In [51]:
calc_diff_counts_hebrew(m_all, 'road_light')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

### road_control and road_control_hebrew

In [ ]:
# road_control                                 7106 non-null float64
# road_control_hebrew                          7106 non-null object

In [53]:
calc_diff_counts_hebrew(m_all, 'road_control')

Shape of data: (7106, 101)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

### weather and weather_hebrew

In [ ]:
# weather                                      53030 non-null int64
# weather_hebrew                               53030 non-null object

In [54]:
calc_diff_counts_hebrew(m_all, 'weather')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

### road_surface and road_surface_hebrew

In [55]:
# road_surface                                 53030 non-null int64
# road_surface_hebrew                          53030 non-null object

In [56]:
calc_diff_counts_hebrew(m_all, 'road_surface')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

### road_object and road_object_hebrew

In [57]:
# road_object                                  53030 non-null int64
# road_object_hebrew                           53030 non-null object

In [58]:
calc_diff_counts_hebrew(m_all, 'road_object')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

### object_distance and object_distance_hebrew

In [ ]:
# object_distance                              53030 non-null int64
# object_distance_hebrew                       53030 non-null object

In [60]:
calc_diff_counts_hebrew(m_all, 'object_distance')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

### didnt_cross and didnt_cross_hebrew

In [61]:
# didnt_cross                                  53030 non-null int64
# didnt_cross_hebrew                           53030 non-null object

In [62]:
calc_diff_counts_hebrew(m_all, 'didnt_cross')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

### cross_mode and cross_mode_hebrew

In [63]:
# cross_mode                                   53030 non-null int64
# cross_mode_hebrew                            3185 non-null object

In [64]:
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)].shape

(49845, 101)

In [65]:
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.984500e+04,4.984500e+04,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,5640.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.0,49845.000000,49845.0,13884.000000,13721.000000,13869.000000,13869.000000,1.353000e+04,13530.000000,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,39745.000000,49845.000000,39745.000000,39656.000000,39745.000000,26009.000000,4925.000000,30739.000000,4262.000000,4.925000e+03,49845.0,49845.000000,49845.000000,49845.000000,49845.000000,49845.000000,49741.000000,49741.000000,49741.000000,49741.000000
mean,2.019050e+09,2.819600e+10,2.617695,2.630454,4.883138,2.961641,1.874972,2.371813,8.878604,3.890541,30.871381,7.697362,0.189126,0.393861,0.160498,0.476156,4.665262,8.522560,3.584574,7.676698,7.668813,8.885204,8.896218,8.993680,0.0,0.000782,9.0,425.553443,299.652941,723.111400,721.890115,3.754478e+06,110.017738,3414.458822,1.025078,1.987541,3.646805,8.306731,4.229916,55.886348,452.128268,19.945910,24.633941,915.894037,844.473706,8318.751521,2678.362506,1.483257e+07,2019.0,5.860829,15.704825,55.790531,13.382987,18.878724,34.973361,32.186784,197594.127199,677071.291932
std,3.055879e+04,7.864258e+09,0.786426,0.776234,3.983878,0.214094,0.929663,0.910533,0.482176,0.501958,17.909484,2.935151,0.709431,1.115435,0.383797,1.144563,0.767800,3.584579,2.198343,2.961477,2.966843,0.753202,0.857752,0.140862,0.0,0.057180,0.0,1384.924104,1243.863059,883.379082,884.377458,1.281253e+07,205.778776,3284.749917,0.156363,1.724815,1.857251,2.309769,2.179409,30.046152,233.883704,38.737612,25.123509,1240.491993,965.056848,3729.250465,2848.212216,2.120964e+07,0.0,3.066256,8.758245,19.988189,5.005604,16.575459,0.222149,0.575853,20987.600768,63836.706974
min,2.018012e+09,1.201801e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.000000,9.0,1.000000,0.000000,0.000000,-222.000000,1.001000e+04,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,101.000000,1.000000,1.000000,0.000000e+00,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.284338,29.492253,131783.000000,378324.000000
25%,2.019025e+09,3.201901e+10,3.000000,3.000000,3.000000,3.000000,1.000000,2.000000,9.000000,4.000000,12.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.0,0.000000,9.0,4.000000,0.000000,105.000000,105.000000,4.028200e+04,13.000000,0.000000,1.000000,1.000000,2.000000,9.000000,2.000000,31.000000,246.000000,0.000000,13.000000,211.000000,252.000000,9999.000000,497.000000,7.300023e+06,2019.0,3.000000,8.000000,41.000000,10.000000,0.000000,34.797981,31.894089,180883.000000,644592.000000
50%,2.019050e+09,3.201904e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,20.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.0,0.000000,9.0,40.000000,0.000000,331.000000,331.000000,4.001400e+05,40.000000,3000.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,432.000000,0.000000,15.000000,493.000000,508.000000,9999.000000,1355.000000,9.110323e+06,2019.0,6.000000,16.000000,57.000000,14.000000,15.000000,34.918826,32.083957,192584.000000,665686.000000
75%,2.019075e+09,3.201907e+10,3.000000,3.000000,5.000000,3.000000,3.000000,3.000000,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.0,0.000000,9.0,90.000000,0.000000,1093.000000,1093.000000,9.000660e+05,90.000000,6600.000000,1.000000,1.000000,5.000000,9.000000,5.000000,99.000000,513.000000,0.000000,25.000000,1021.000000,1015.000000,9999.000000,4071.000000,1.540000e+07,2019.0,8.000000,23.000000,70.000000,17.000000,30.000000,35.115013,32.707888,211060.000000,734818.000000
max,2.019100e+09,3.201910e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.0,9.000000,9.0,9974.000000,9977.000000,4760.000000,4760.000000,9.898071e+07,874.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,7001.000000,11111.000000,10447.000000,1.000000e+08,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.808684,33.307069,275932.000000,801408.000000

In [66]:
m_all[m_all['cross_mode']==0].shape

(49845, 101)

**Null Conclusions**: All `cross_mode` == 0 translation is missing

In [67]:
calc_diff_counts_hebrew(m_all, 'cross_mode')

Shape of data: (3185, 101)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

### cross_location and cross_location_hebrew

In [68]:
# cross_location                               53030 non-null int64
# cross_location_hebrew                        2545 non-null object

In [69]:
m_all[(m_all['cross_location'].isnull() == False) & (m_all['cross_location_hebrew'].isnull() == True)].shape

(50485, 101)

In [70]:
m_all[(m_all['cross_location'].isnull() == False) & (m_all['cross_location_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,5.048500e+04,5.048500e+04,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,5686.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.0,50485.0,13922.000000,13757.000000,13907.000000,13907.000000,1.356400e+04,13564.000000,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,40369.000000,50485.000000,40369.000000,40280.000000,40369.000000,26458.000000,4972.000000,31294.000000,4272.000000,4.972000e+03,50485.0,50485.000000,50485.000000,50485.000000,50485.000000,50485.000000,50381.000000,50381.000000,50381.000000,50381.000000
mean,2.019050e+09,2.817316e+10,2.615411,2.628206,4.837140,2.960464,1.876102,2.367475,8.878063,3.890641,30.884877,7.690383,0.188888,0.393067,0.161652,0.477310,4.663365,8.515084,3.588815,7.668377,7.660513,8.885055,8.895276,8.975834,0.083708,0.0,9.0,426.586841,298.963219,723.015316,721.797368,3.753764e+06,109.984223,3431.716807,1.024978,1.986352,3.646548,8.311023,4.229136,55.754125,451.994327,19.855437,24.560058,913.219026,845.808729,8290.282674,2682.043539,1.488511e+07,2019.0,5.859741,15.699336,55.779063,13.379994,18.886303,34.973044,32.185526,197563.921121,676931.902920
std,3.054865e+04,7.882146e+09,0.788215,0.778054,3.983727,0.217722,0.928747,0.907393,0.482056,0.501863,17.896841,2.939939,0.709523,1.111878,0.385688,1.144338,0.769639,3.590957,2.204363,2.968998,2.974160,0.754880,0.861718,0.320833,0.771725,0.0,0.0,1385.663809,1242.322441,883.291795,884.287413,1.280206e+07,205.743541,3287.912267,0.156059,1.724116,1.857317,2.303606,2.173933,29.963161,233.200215,38.670770,25.016835,1241.030507,971.624340,3754.298746,2851.282083,2.127560e+07,0.0,3.066686,8.757585,19.980186,5.003719,16.575661,0.222044,0.576301,20977.913589,63886.333897
min,2.018012e+09,1.201801e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.0,9.0,1.000000,0.000000,0.000000,-222.000000,1.001000e+04,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,101.000000,1.000000,1.000000,0.000000e+00,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.284338,29.492253,131783.000000,378324.000000
25%,2.019025e+09,3.201901e+10,3.000000,3.000000,3.000000,3.000000,1.000000,2.000000,9.000000,4.000000,12.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.0,9.0,4.000000,0.000000,105.000000,103.000000,4.028200e+04,13.000000,0.000000,1.000000,1.000000,2.000000,9.000000,2.000000,31.000000,246.000000,0.000000,13.000000,210.000000,249.750000,9999.000000,497.000000,7.310001e+06,2019.0,3.000000,8.000000,41.000000,10.000000,0.000000,34.797981,31.893690,180873.000000,644590.000000
50%,2.019050e+09,3.201904e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,20.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.0,9.0,40.000000,0.000000,330.000000,330.000000,4.001400e+05,40.000000,3000.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,432.000000,0.000000,15.000000,487.000000,508.000000,9999.000000,1355.000000,9.110323e+06,2019.0,6.000000,16.000000,57.000000,14.000000,15.000000,34.918717,32.083793,192579.000000,665671.000000
75%,2.019075e+09,3.201907e+10,3.000000,3.000000,5.000000,3.000000,3.000000,3.000000,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.0,9.0,90.000000,0.000000,1093.000000,1093.000000,9.000660e+05,90.000000,6600.000000,1.000000,1.000000,5.000000,9.000000,5.000000,99.000000,513.000000,0.000000,25.000000,1020.000000,1014.250000,9999.000000,4071.000000,1.540002e+07,2019.0,8.000000,23.000000,70.000000,17.000000,30.000000,35.114690,32.707318,211029.000000,734755.000000
max,2.019100e+09,3.201910e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.0,9.0,9974.000000,9977.000000,4760.000000,4760.000000,9.898071e+07,874.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,7001.000000,11111.000000,10447.000000,1.000000e+08,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.808684,33.307069,275932.000000,801408.000000

In [71]:
m_all[m_all['cross_location']==0].shape

(50485, 101)

**Null Conclusion:** all `cross_location` == 0 has no translation

In [72]:
calc_diff_counts_hebrew(m_all, 'cross_location')

Shape of data: (2545, 101)

0    0
1    0
2    0
3    0
4    0
dtype: int64

### cross_direction and cross_direction_hebrew

In [73]:
# cross_direction                              53030 non-null int64
# cross_direction_hebrew                       53030 non-null object

In [74]:
calc_diff_counts_hebrew(m_all, 'cross_direction')

Shape of data: (53030, 101)

0    0
1    0
2    0
dtype: int64

In [75]:
### geo_area and geo_area_hebrew

In [77]:
# geo_area                                     53030 non-null int64
# geo_area_hebrew                              53030 non-null object

In [78]:
calc_diff_counts_hebrew(m_all, 'geo_area')

Shape of data: (53030, 101)

0    0
1    0
dtype: int64

### day_night and day_night_hebrew

In [79]:
# day_night                                    53030 non-null int64
# day_night_hebrew                             53030 non-null object

In [80]:
calc_diff_counts_hebrew(m_all, 'day_night')

Shape of data: (53030, 101)

0    0
1    0
dtype: int64

### day_in_week and day_in_week_hebrew

In [81]:
# day_in_week                                  53030 non-null int64
# day_in_week_hebrew                           53030 non-null object

In [82]:
calc_diff_counts_hebrew(m_all, 'day_in_week')

Shape of data: (53030, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

### traffic_light and traffic_light_hebrew

In [83]:
# traffic_light                                53030 non-null int64
# traffic_light_hebrew                         53030 non-null object

In [84]:
calc_diff_counts_hebrew(m_all, 'traffic_light')

Shape of data: (53030, 101)

0    0
1    0
2    0
dtype: int64

### region and region_hebrew

In [85]:
# region                                       42898 non-null float64
# region_hebrew                                42898 non-null object

In [86]:
calc_diff_counts_hebrew(m_all, 'region')

Shape of data: (42898, 101)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

### district and district_hebrew

In [87]:
# district                                     53030 non-null int64
# district_hebrew                              38921 non-null object

In [88]:
m_all[(m_all['district'].isnull() == False) & (m_all['district_hebrew'].isnull() == True)].shape

(14109, 101)

In [89]:
m_all[(m_all['district'].isnull() == False) & (m_all['district_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.410900e+04,1.410900e+04,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,2062.000000,14109.000000,14109.000000,14109.000000,14109.000000,14109.00000,14109.000000,14109.00000,14109.000000,14023.000000,13852.000000,14008.000000,14008.000000,1.366000e+04,13660.000000,14109.0,14109.000000,14109.000000,14109.000000,14109.000000,3977.0,14109.0,3977.0,3977.0,3977.0,0.0,0.0,2.0,4309.000000,0.0,14109.0,14109.000000,14109.000000,14109.000000,14109.000000,14109.000000,14012.000000,14012.000000,14012.000000,14012.000000
mean,2.019050e+09,2.638151e+10,2.436246,2.449429,4.368843,2.926501,1.130838,3.694096,8.803955,3.875824,30.572046,7.011269,0.305266,0.980084,0.241831,0.800411,4.503012,7.786803,3.388458,7.025799,7.005812,8.839110,8.820469,8.98866,0.033808,0.01942,8.957828,429.479783,301.117312,723.580954,722.335665,3.777797e+06,110.506808,0.0,1.056985,2.121554,3.706358,8.169325,9.0,99.0,999.0,99.0,99.0,NaN,NaN,9999.0,2680.544442,NaN,2019.0,5.853356,15.812389,55.259267,13.241264,19.413141,34.989018,32.227187,199071.700328,681549.480303
std,3.342239e+04,8.998592e+09,0.899859,0.893347,3.316353,0.304812,0.766949,0.461113,0.676143,0.534495,17.486237,3.467979,0.854789,1.836710,0.443495,1.466572,0.884975,3.923376,2.177456,3.432597,3.443121,0.816386,1.116741,0.22719,0.418497,0.26606,0.563259,1390.760048,1248.065933,884.539563,885.556859,1.285512e+07,206.436623,0.0,0.231822,1.796820,1.875491,2.481923,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,2850.449342,NaN,0.0,3.120121,8.743082,21.164329,5.297760,16.537198,0.217273,0.730042,20520.828811,80935.048189
min,2.018012e+09,1.201801e+10,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.00000,1.000000,1.000000,0.000000,0.000000,-222.000000,1.001000e+04,0.000000,0.0,1.000000,1.000000,1.000000,0.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,9999.0,1.000000,NaN,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.327066,29.492253,135850.000000,378324.000000
25%,2.019025e+09,1.201909e+10,1.000000,1.000000,3.000000,3.000000,1.000000,3.000000,9.000000,4.000000,12.000000,3.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,2.000000,9.000000,9.000000,9.00000,0.000000,0.00000,9.000000,4.000000,0.000000,105.000000,100.750000,4.028200e+04,13.000000,0.0,1.000000,1.000000,2.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,9999.0,497.000000,NaN,2019.0,3.000000,8.000000,38.000000,9.000000,0.000000,34.823468,31.950518,183382.000000,650913.000000
50%,2.019051e+09,3.201903e+10,3.000000,3.000000,3.000000,3.000000,1.000000,4.000000,9.000000,4.000000,20.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.00000,0.000000,0.00000,9.000000,40.000000,0.000000,330.000000,330.000000,4.001400e+05,40.000000,0.0,1.000000,1.000000,4.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,9999.0,1355.000000,NaN,2019.0,6.000000,16.000000,58.000000,14.000000,15.000000,34.962120,32.160494,196752.000000,674176.000000
75%,2.019075e+09,3.201907e+10,3.000000,3.000000,4.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,9.000000,0.000000,1.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.00000,0.000000,0.00000,9.000000,90.000000,0.000000,1093.000000,1093.000000,9.000700e+05,90.000000,0.0,1.000000,5.000000,5.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,9999.0,4071.000000,NaN,2019.0,9.000000,23.000000,71.000000,17.000000,30.000000,35.105292,32.796266,210194.000000,744639.000000
max,2.019100e+09,3.201910e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.00000,9.000000,9.00000,9.000000,9974.000000,9977.000000,4760.000000,4760.000000,9.898071e+07,874.000000,0.0,2.000000,5.000000,7.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,9999.0,10447.000000,NaN,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.788364,33.307069,273927.000000,801408.000000

In [91]:
m_all[m_all['district'] == 99].shape

(14109, 101)

**Null Conclusion:** all `district` == 99 missing translation

In [92]:
calc_diff_counts_hebrew(m_all, 'district')

Shape of data: (38921, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
dtype: int64

### natural_area and natural_area_hebrew

In [93]:
# natural_area                                 42898 non-null float64
# natural_area_hebrew                          38822 non-null object

In [94]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].shape

(4076, 101)

In [95]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.076000e+03,4.076000e+03,4076.0,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,2025.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,3973.000000,3905.000000,3970.000000,3970.000000,3.854000e+03,3854.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4073.000000,4076.000000,80.00000,32.000000,67.000000,1491.000000,3.200000e+01,4076.0,4076.000000,4076.000000,4076.000000,4076.000000,4076.000000,4065.000000,4065.000000,4065.00000,4065.000000
mean,2.019049e+09,1.201905e+10,1.0,1.050540,3.921246,2.738960,1.112120,3.577772,8.319921,3.846909,28.906035,2.113837,1.059863,3.341021,0.838567,2.771099,3.274779,2.965162,3.456790,2.149411,2.081943,8.676644,8.510304,8.963690,0.113101,0.082434,8.807164,751.723886,469.303201,677.857935,677.260453,6.417106e+06,123.886871,89.103778,1.100098,2.387635,3.925908,6.197988,8.951423,98.465653,993.607949,97.353793,97.055937,327.71250,159.312500,5829.895522,2955.134138,1.882210e+06,2019.0,5.792198,15.648430,56.464181,13.530667,20.122669,35.023208,32.255862,202289.84674,684725.987454
std,3.654600e+04,3.654600e+04,0.0,0.313926,3.017158,0.528977,0.587343,0.569220,1.126678,0.599483,17.325856,2.806879,1.319732,1.882694,0.428373,1.404937,0.773526,3.028902,2.207433,2.736170,2.660257,1.171630,1.799834,0.402027,0.732231,0.523392,1.194510,1889.794208,1628.389523,907.358458,907.804623,1.730744e+07,230.298570,565.135492,0.300168,1.904179,1.978264,3.912015,0.307925,3.387171,34.179639,12.398519,12.377927,916.63032,70.337178,4957.507050,2947.991375,7.067256e+06,0.0,3.084137,8.760357,22.826482,5.708957,16.579895,0.233193,0.688389,22015.02724,76315.974952
min,2.018012e+09,1.201801e+10,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,-222.000000,1.001000e+04,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,7.000000,77.000000,777.000000,0.000000,15.000000,102.00000,102.000000,1.000000,1.000000,0.000000e+00,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.327066,29.493003,135850.00000,378407.000000
25%,2.019025e+09,1.201903e+10,1.0,1.000000,2.000000,3.000000,1.000000,3.000000,8.000000,4.000000,12.000000,0.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,84.000000,80.000000,2.000120e+05,10.000000,0.000000,1.000000,1.000000,2.000000,1.000000,9.000000,99.000000,999.000000,99.000000,99.000000,132.25000,115.250000,23.500000,727.000000,1.000575e+04,2019.0,3.000000,8.000000,41.000000,10.000000,0.000000,34.871383,31.949478,188016.00000,650753.000000
50%,2.019050e+09,1.201905e+10,1.0,1.000000,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,20.000000,1.000000,0.000000,4.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,70.000000,0.000000,240.000000,240.000000,7.000500e+05,30.000000,0.000000,1.000000,1.000000,4.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,179.50000,135.500000,9999.000000,1629.000000,5.502250e+04,2019.0,6.000000,16.000000,59.000000,14.000000,15.000000,35.005529,32.271115,200708.00000,686393.000000
75%,2.019075e+09,1.201907e+10,1.0,1.000000,5.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,3.000000,2.000000,5.000000,1.000000,4.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,444.000000,6.000000,910.000000,910.000000,4.440026e+06,98.000000,0.000000,1.000000,5.000000,6.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,219.25000,177.000000,9999.000000,4089.000000,1.550790e+05,2019.0,8.000000,23.000000,73.000000,18.000000,30.000000,35.146154,32.808936,213986.00000,746035.000000
max,2.019100e+09,1.201910e+10,1.0,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9974.000000,9977.000000,4760.000000,4760.000000,9.898071e+07,874.000000,3797.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,6001.00000,412.000000,9999.000000,10447.000000,2.882007e+07,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.771844,33.307069,272292.00000,801408.000000

In [96]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)]['natural_area'].value_counts()

999.0    3977
777.0      99
Name: natural_area, dtype: int64

**Null Conclusion:** Following `natural_area` had translation issues:
- 999 - all values missing
- 777 - all values missing

In [97]:
calc_diff_counts_hebrew(m_all, 'natural_area')

Shape of data: (38822, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
52    0
53    0
54    0
55    0
56    0
57    0
dtype: int64

### municipal_status and municipal_status_hebrew

In [98]:
# municipal_status                             42805 non-null float64
# municipal_status_hebrew                      42805 non-null object

In [99]:
calc_diff_counts_hebrew(m_all, 'municipal_status')

Shape of data: (42805, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
52    0
53    0
54    0
dtype: int64

### yishuv_shape and yishuv_shape_hebrew

In [ ]:
# yishuv_shape                                 42898 non-null float64
# yishuv_shape_hebrew                          38921 non-null object

In [100]:
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)].shape

(3977, 101)

In [101]:
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,3.977000e+03,3.977000e+03,3977.0,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,1991.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3973.000000,3905.000000,3970.000000,3970.000000,3.854000e+03,3854.000000,3977.0,3977.000000,3977.000000,3977.000000,3977.000000,3977.0,3977.0,3977.0,3977.0,3977.0,0.0,0.0,0.0,1491.000000,0.0,3977.0,3977.000000,3977.000000,3977.000000,3977.000000,3977.000000,3966.000000,3966.000000,3966.000000,3966.000000
mean,2.019049e+09,1.201905e+10,1.0,1.046769,3.929847,2.739251,1.097058,3.625094,8.316067,3.845361,28.573799,2.086749,1.069399,3.399799,0.840835,2.784762,3.273573,2.954488,3.420894,2.138798,2.070153,8.671612,8.502892,8.964295,0.092784,0.057581,8.867488,751.723886,469.303201,677.857935,677.260453,6.417106e+06,123.886871,0.0,1.077697,2.400050,3.927835,6.166709,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,2955.134138,NaN,2019.0,5.794820,15.649987,56.442796,13.525019,20.140810,35.019338,32.264259,201923.111447,685657.977559
std,3.671299e+04,3.671299e+04,0.0,0.302280,2.993346,0.529939,0.571484,0.484159,1.128970,0.602622,17.409500,2.791779,1.322005,1.863577,0.423840,1.404913,0.768853,3.008655,2.190580,2.724497,2.646009,1.178821,1.812808,0.401497,0.698655,0.440588,0.992320,1889.794208,1628.389523,907.358458,907.804623,1.730744e+07,230.298570,0.0,0.267727,1.908134,1.987276,3.918898,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2947.991375,NaN,0.0,3.083944,8.769901,22.908110,5.728906,16.556342,0.234152,0.694232,22104.482531,76963.230984
min,2.018012e+09,1.201801e+10,1.0,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,-222.000000,1.001000e+04,0.000000,0.0,1.000000,1.000000,1.000000,0.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,1.000000,NaN,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.327066,29.493003,135850.000000,378407.000000
25%,2.019025e+09,1.201903e+10,1.0,1.000000,2.000000,3.000000,1.000000,3.000000,8.000000,4.000000,12.000000,0.000000,0.000000,2.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,84.000000,80.000000,2.000120e+05,10.000000,0.0,1.000000,1.000000,2.000000,1.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,727.000000,NaN,2019.0,3.000000,8.000000,41.000000,10.000000,0.000000,34.866409,31.950518,187620.000000,650913.000000
50%,2.019050e+09,1.201905e+10,1.0,1.000000,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,20.000000,1.000000,0.000000,4.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,70.000000,0.000000,240.000000,240.000000,7.000500e+05,30.000000,0.0,1.000000,1.000000,4.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,1629.000000,NaN,2019.0,6.000000,16.000000,59.000000,14.000000,15.000000,35.004343,32.279632,200496.000000,687337.000000
75%,2.019075e+09,1.201907e+10,1.0,1.000000,5.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,3.000000,2.000000,5.000000,1.000000,4.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,444.000000,6.000000,910.000000,910.000000,4.440026e+06,98.000000,0.0,1.000000,5.000000,6.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,4089.000000,NaN,2019.0,8.000000,23.000000,73.000000,18.000000,30.000000,35.142769,32.812910,213627.000000,746486.000000
max,2.019100e+09,1.201910e+10,1.0,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9974.000000,9977.000000,4760.000000,4760.000000,9.898071e+07,874.000000,0.0,2.000000,5.000000,7.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,10447.000000,NaN,2019.0,11.000000,31.000000,96.000000,23.000000,45.000000,35.771844,33.307069,272292.000000,801408.000000

In [102]:
m_all[m_all['yishuv_shape']==99].shape

(3977, 101)

**Null Conclusion:** `yishuv_shape` translation issues: 99

In [104]:
calc_diff_counts_hebrew(m_all, 'yishuv_shape')

Shape of data: (38921, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
dtype: int64

### street1 and street1_hebrew

In [105]:
# street1                                      28750 non-null float64
# street1_hebrew                               27712 non-null object

In [106]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].shape

(1038, 101)

In [107]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.038000e+03,1.038000e+03,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.0,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,17.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,0.0,0.0,0.0,0.0,0.0,0.0,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1028.000000,1038.000000,1038.000000,0.0,1038.000000,0.0,0.0,1038.0,1038.000000,1038.000000,1038.000000,1038.000000,1038.000000,1037.000000,1037.000000,1037.000000,1037.000000
mean,2.019050e+09,3.034275e+10,2.832370,2.845857,4.936416,2.975915,2.006744,2.0,8.958574,3.920039,31.656069,8.494220,0.028902,0.093449,0.096339,0.167630,4.839114,8.991329,5.588235,8.426782,8.436416,8.806358,8.934489,8.955684,0.129094,0.046243,8.931599,NaN,NaN,NaN,NaN,NaN,NaN,3362.500000,1.020231,2.148362,3.879576,8.992293,3.567437,37.730250,379.655106,20.483463,22.529865,420.025048,NaN,9883.991329,NaN,NaN,2019.0,3.515414,14.336224,56.411368,13.557803,17.702312,35.018294,32.328091,201863.692382,692727.972035
std,2.917011e+04,5.544878e+09,0.554488,0.533666,4.137208,0.159549,0.230200,0.0,0.290012,0.456775,18.309148,1.788602,0.321419,0.400019,0.405324,0.650519,0.621173,3.002237,1.583462,2.045749,2.003205,0.953134,0.670026,0.510225,0.903599,0.478849,0.732325,NaN,NaN,NaN,NaN,NaN,NaN,2929.811929,0.140858,1.810489,1.904658,0.248308,1.275380,12.343699,122.897753,36.717277,7.357949,1998.349381,NaN,1064.039020,NaN,NaN,0.0,3.003895,8.816114,18.979138,4.751900,16.036813,0.203450,0.385370,19189.727970,42715.208927
min,2.019000e+09,1.201900e+10,1.000000,1.000000,1.000000,1.000000,1.000000,2.0,4.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,NaN,1.000000,NaN,NaN,2019.0,1.000000,1.000000,1.000000,0.000000,0.000000,34.558311,30.176872,158123.000000,454192.000000
25%,2.019024e+09,3.201902e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.0,9.000000,4.000000,12.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,638.000000,1.000000,1.000000,2.000000,9.000000,2.000000,29.000000,292.000000,0.000000,16.000000,0.000000,NaN,9999.000000,NaN,NaN,2019.0,1.000000,6.000000,42.000000,10.000000,0.000000,34.885739,32.077135,189291.000000,664940.000000
50%,2.019051e+09,3.201905e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.0,9.000000,4.000000,34.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,2720.000000,1.000000,1.000000,4.000000,9.000000,4.000000,41.000000,412.000000,0.000000,26.000000,0.000000,NaN,9999.000000,NaN,NaN,2019.0,2.000000,14.000000,57.000000,14.000000,15.000000,34.979519,32.288494,198245.000000,688325.000000
75%,2.019076e+09,3.201907e+10,3.000000,3.000000,7.000000,3.000000,2.000000,2.0,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,6400.000000,1.000000,5.000000,5.000000,9.000000,4.000000,43.000000,432.000000,20.000000,26.000000,0.000000,NaN,9999.000000,NaN,NaN,2019.0,5.000000,22.000000,71.000000,17.000000,30.000000,35.151865,32.557274,214510.000000,718116.000000
max,2.019100e+09,3.201910e+10,3.000000,3.000000,20.000000,3.000000,9.000000,2.0,11.000000,4.000000,61.000000,9.000000,5.000000,5.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,9800.000000,2.000000,5.000000,7.000000,9.000000,7.000000,77.000000,770.000000,99.000000,53.000000,9998.000000,NaN,9999.000000,NaN,NaN,2019.0,11.000000,31.000000,95.000000,23.000000,45.000000,35.757375,33.241761,270989.000000,794121.000000

In [108]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

0.0       989
9998.0     20
9991.0     16
9992.0      5
202.0       3
139.0       1
5369.0      1
9995.0      1
9994.0      1
107.0       1
Name: street1, dtype: int64

In [29]:
def print_yishuv_street1(street1):
    print(f"street1: {street1}, shape: {m_all[m_all['street1'] == street1].shape}")
    display(m_all[(m_all['street1'] == street1) & (m_all['street1_hebrew'].isnull() == True)]['yishuv_symbol'].value_counts())

In [36]:
print_yishuv_street1(0)

street1: 0, shape: (989, 101)

2730    84
638     63
2720    46
6000    32
7300    31
5000    30
6500    27
2710    20
7400    17
6400    17
4000    16
1139    14
3000    12
637     11
634     11
628     11
8300    10
8800    10
6700     9
654      9
8900     9
7900     9
1061     9
9200     9
2650     8
8000     8
70       8
8700     8
8400     8
7000     7
7100     7
7600     7
7800     7
661      6
1345     6
1290     6
8500     6
7500     6
6900     6
2630     6
1020     6
507      6
531      5
716      5
6100     5
1063     5
2660     5
9100     5
681      5
6600     5
529      4
2400     4
168      4
8600     4
9000     4
2530     4
483      4
494      4
496      4
502      4
481      3
1292     3
473      3
466      3
2640     3
9700     3
2610     3
3567     3
1326     3
504      3
480      3
1304     3
1066     3
2100     3
232      3
720      3
1084     3
1748     3
166      3
705      3
1034     3
6800     3
499      2
498      2
9300     2
7200     2
53       2
6200     2
2043     2
509      2
63       2
516      2
259      2
758      2
267      2
1224     2
2300     2
246      2
9500     2
1319     2
2006     2
304      2
1200     2
1161     2
171      2
358      2
392      2
155      2
418      2
447      2
462      2
2055     2
9800     2
543      2
812      2
804      2
825      2
7700     2
3570     2
798      2
537      2
538      2
541      2
198      1
190      1
184      1
1207     1
177      1
182      1
663      1
777      1
3750     1
3843     1
690      1
1188     1
666      1
230      1
1243     1
1245     1
229      1
3710     1
788      1
242      1
1267     1
1275     1
801      1
975      1
2550     1
921      1
158      1
530      1
154      1
2200     1
745      1
740      1
2038     1
739      1
738      1
3568     1
280      1
532      1
3797     1
1746     1
3793     1
64       1
710      1
2034     1
72       1
808      1
763      1
1132     1
4203     1
2030     1
2018     1
122      1
3200     1
3041     1
703      1
142      1
1167     1
1296     1
147      1
807      1
32       1
633      1
490      1
442      1
2500     1
176      1
3917     1
3650     1
469      1
577      1
576      1
2620     1
1332     1
3641     1
3640     1
487      1
492      1
281      1
565      1
848      1
497      1
542      1
3578     1
853      1
535      1
510      1
2560     1
518      1
520      1
522      1
525      1
7        1
863      1
431      1
427      1
285      1
9400     1
294      1
817      1
627      1
620      1
610      1
316      1
897      1
322      1
3400     1
874      1
354      1
868      1
839      1
359      1
369      1
375      1
662      1
382      1
388      1
597      1
400      1
732      1
594      1
417      1
3660     1
757      1
Name: yishuv_symbol, dtype: int64

In [30]:
print_yishuv_street1(9998)

street1: 9998, shape: (20, 101)

8300    2
126     1
836     1
707     1
8900    1
359     1
7400    1
586     1
4203    1
1264    1
700     1
6800    1
6500    1
365     1
755     1
99      1
345     1
1864    1
2400    1
Name: yishuv_symbol, dtype: int64

In [31]:
print_yishuv_street1(9991)

street1: 9991, shape: (16, 101)

7100    3
3000    2
6400    2
7600    1
2200    1
2650    1
5000    1
7000    1
874     1
166     1
466     1
70      1
Name: yishuv_symbol, dtype: int64

In [32]:
print_yishuv_street1(9992)

street1: 9992, shape: (5, 101)

7100    1
147     1
634     1
3041    1
8500    1
Name: yishuv_symbol, dtype: int64

In [33]:
print_yishuv_street1(202)

street1: 202, shape: (74, 101)

6200    3
Name: yishuv_symbol, dtype: int64

In [35]:
streets = [139, 5369, 9995, 9994, 107]
for street in streets:
    print_yishuv_street1(street)

street1: 139, shape: (75, 101)

577    1
Name: yishuv_symbol, dtype: int64

street1: 5369, shape: (1, 101)

3000    1
Name: yishuv_symbol, dtype: int64

street1: 9995, shape: (1, 101)

1066    1
Name: yishuv_symbol, dtype: int64

street1: 9994, shape: (1, 101)

1748    1
Name: yishuv_symbol, dtype: int64

street1: 107, shape: (102, 101)

807    1
Name: yishuv_symbol, dtype: int64

**Null Conclusion:** Most `street1` == 0, other 49 miscellenious.  
- Some of the miscellenious all the index translation is missing, some only part of the instances translation missing.
- `street1` is not unique in itself, but unique within specific `yishuv_symbol`.  Some `street1` values are missing for specific `yishuv_symbol` and some for many `yishuv_symbol`s.

See details above.

**Specific values mistmatch investigations:**

Didn't do detailed investigation, especially due to all the differences already in the null

## street2 and street2_hebrew

In [109]:
# street2                                      6075 non-null float64
# street2_hebrew                               6072 non-null object

In [110]:
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)].shape

(3, 101)

In [13]:
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,...,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,road_segment_id,road_segment_number,road_segment_name,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
201077,2019092408,12019092408,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,1.0,2,התנגשות חזית בצד,3,קלה,2019-06-01 11:45:00,1,עיגון מדויק,1,עירונית בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",2,דו סיטרי + קו הפרדה רצוף,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,4,10.5 עד 14 מטר,3,אין ליקוי,1,אור יום רגיל,2.0,רמזור תקין,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6200,בת ים,1,ישראל ללא יהודה ושומרון,1,יום,7,שבת,1,כן,5.0,תל אביב,51,תל אביב,513.0,אזור חולון,0.0,עירייה,14.0,יישובים יהודיים 199999-100000 תושבים,201.0,שד העצמאות,202.0,NaN,NaN,NaN,NaN,NaN,67040011.0,2019,6,1,48,11:45-11:59,11,45,0101000020E610000074A694ACFA5F4140C85710DAC503...,34.749837,32.029475,176506.0,659670.0
201965,2019099904,12019099904,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,1.0,5,התנגשות חזית בחזית,3,קלה,2019-10-10 19:00:00,1,עיגון מדויק,1,עירונית בצומת,9,אחר,4,יום אחר,20,"מחוז ת""א",0,NaN,3,מיפרדה בנויה ללא גדר בטיחות,1,"עד 50 קמ""ש",1,אין ליקויים,2,5 עד 7 מטר,3,אין ליקוי,3,לילה פעלה תאורה,5.0,תמרור עצור,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6200,בת ים,1,ישראל ללא יהודה ושומרון,5,לילה,5,חמישי,0,לא,5.0,תל אביב,51,תל אביב,513.0,אזור חולון,0.0,עירייה,14.0,יישובים יהודיים 199999-100000 תושבים,217.0,ברדיצ'ב אבא,202.0,NaN,NaN,NaN,NaN,NaN,9150022.0,2019,10,10,77,19:00-19:14,19,0,0101000020E6100000281FD774E55F414079FE7E98D103...,34.749190,32.029834,176445.0,659710.0
791490,2019081989,32019081989,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,3.0,11,החלקה,3,קלה,2019-06-06 21:30:00,1,עיגון מדויק,1,עירונית בצומת,9,אחר,4,יום אחר,20,"מחוז ת""א",9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,6,לילה לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6200,בת ים,1,ישראל ללא יהודה ושומרון,5,לילה,5,חמישי,9,לא ידוע,5.0,תל אביב,51,תל אביב,513.0,אזור חולון,0.0,עירייה,14.0,יישובים יהודיים 199999-100000 תושבים,219.0,העמדות,202.0,NaN,NaN,NaN,NaN,NaN,68870022.0,2019,6,6,87,21:30-21:44,21,30,0101000020E61000007046815DA35F41404BDF4297F603...,34.747173,32.030963,176255.0,659836.0

In [111]:
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,road_segment_id,road_segment_number,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,3.000000e+00,3.000000e+00,3.000000,3.000000,3.000000,3.0,3.0,3.0,3.000000,3.0,3.0,3.000000,3.000000,3.000000,3.000000,3.0,3.000000,3.000000,2.00000,3.000000,3.000000,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,3.000000,3.000000,3.000000,3.0,3.0,3.0,3.0,3.0,3.000000,3.0,0.0,0.0,3.000000e+00,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
mean,2.019091e+09,1.868576e+10,1.666667,1.666667,6.000000,3.0,1.0,1.0,8.666667,4.0,20.0,3.666667,1.000000,0.666667,0.666667,2.0,3.666667,3.333333,3.50000,3.666667,3.666667,9.0,9.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,6200.0,1.0,3.666667,5.666667,3.333333,5.0,51.0,513.0,0.0,14.0,212.333333,202.0,NaN,NaN,4.835335e+07,2019.0,7.333333,5.666667,70.666667,17.000000,25.000000,34.748733,32.030091,176402.000000,659738.666667
std,8.997155e+03,1.154700e+10,1.154701,1.154701,4.582576,0.0,0.0,0.0,0.577350,0.0,0.0,4.725816,1.732051,0.577350,0.577350,2.0,1.154701,2.516611,2.12132,4.618802,4.618802,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.309401,1.154701,4.932883,0.0,0.0,0.0,0.0,0.0,9.865766,0.0,NaN,NaN,3.396341e+07,0.0,2.309401,4.509250,20.256686,5.291503,22.912878,0.001390,0.000776,130.908365,86.633327
min,2.019082e+09,1.201909e+10,1.000000,1.000000,2.000000,3.0,1.0,1.0,8.000000,4.0,20.0,0.000000,0.000000,0.000000,0.000000,0.0,3.000000,1.000000,2.00000,1.000000,1.000000,9.0,9.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,6200.0,1.0,1.000000,5.000000,0.000000,5.0,51.0,513.0,0.0,14.0,201.000000,202.0,NaN,NaN,9.150022e+06,2019.0,6.000000,1.000000,48.000000,11.000000,0.000000,34.747173,32.029475,176255.000000,659670.000000
25%,2.019087e+09,1.201910e+10,1.000000,1.000000,3.500000,3.0,1.0,1.0,8.500000,4.0,20.0,1.000000,0.000000,0.500000,0.500000,1.0,3.000000,2.000000,2.75000,1.000000,1.000000,9.0,9.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,6200.0,1.0,3.000000,5.000000,0.500000,5.0,51.0,513.0,0.0,14.0,209.000000,202.0,NaN,NaN,3.809502e+07,2019.0,6.000000,3.500000,62.500000,15.000000,15.000000,34.748181,32.029655,176350.000000,659690.000000
50%,2.019092e+09,1.201910e+10,1.000000,1.000000,5.000000,3.0,1.0,1.0,9.000000,4.0,20.0,2.000000,0.000000,1.000000,1.000000,2.0,3.000000,3.000000,3.50000,1.000000,1.000000,9.0,9.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,6200.0,1.0,5.000000,5.000000,1.000000,5.0,51.0,513.0,0.0,14.0,217.000000,202.0,NaN,NaN,6.704001e+07,2019.0,6.000000,6.000000,77.000000,19.000000,30.000000,34.749190,32.029834,176445.000000,659710.000000
75%,2.019096e+09,2.201909e+10,2.000000,2.000000,8.000000,3.0,1.0,1.0,9.000000,4.0,20.0,5.500000,1.500000,1.000000,1.000000,3.0,4.000000,4.500000,4.25000,5.000000,5.000000,9.0,9.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,6200.0,1.0,5.000000,6.000000,5.000000,5.0,51.0,513.0,0.0,14.0,218.000000,202.0,NaN,NaN,6.795502e+07,2019.0,8.000000,8.000000,82.000000,20.000000,37.500000,34.749514,32.030398,176475.500000,659773.000000
max,2.019100e+09,3.201908e+10,3.000000,3.000000,11.000000,3.0,1.0,1.0,9.000000,4.0,20.0,9.000000,3.000000,1.000000,1.000000,4.0,5.000000,6.000000,5.00000,9.000000,9.000000,9.0,9.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,6200.0,1.0,5.000000,7.000000,9.000000,5.0,51.0,513.0,0.0,14.0,219.000000,202.0,NaN,NaN,6.887002e+07,2019.0,10.000000,10.000000,87.000000,21.000000,45.000000,34.749837,32.030963,176506.000000,659836.000000

In [115]:
m_all[m_all['street2'] == 202].shape

(14, 101)

In [12]:
m_all[m_all['street2'] == 202][['yishuv_symbol','street2','street2_hebrew','accident_year']].sort_values(by='yishuv_symbol')

        yishuv_symbol  street2 street2_hebrew  accident_year
195679             70    202.0    שפירא אברהם           2019
196390           2400    202.0     יהדות קנדה           2019
200036           2400    202.0     יהדות קנדה           2019
763236           2400    202.0     יהדות קנדה           2019
788523           2400    202.0     יהדות קנדה           2019
6473             3570    202.0   דרך הנחשונים           2019
201077           6200    202.0            NaN           2019
201965           6200    202.0            NaN           2019
791490           6200    202.0            NaN           2019
203750           6700    202.0         אלחדיף           2019
202263           8500    202.0          תל חי           2019
197027           9000    202.0    אברהם אבינו           2019
196292           9600    202.0          הגליל           2019
199682           9600    202.0          הגליל           2019

**Conclusion:** `street2` is not unique on it's own, but only with combination with `yishuv_symbol`.  Seems that there is an issue with `street2` == 202 and `yishuv_symbol` == 6200

**Specific values mistmatch investigations:**

Didn't do detailed investigation, especially due to all the differences already in the null

### non_urban_intersection and non_urban_intersection_hebrew

In [120]:
# non_urban_intersection                       4309 non-null float64
# non_urban_intersection_hebrew                4302 non-null object

In [121]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)].shape

(7, 101)

In [122]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,...,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,road_segment_id,road_segment_number,road_segment_name,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
5924,2019025840,12019025840,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,1.0,2,התנגשות חזית בצד,3,קלה,2019-02-27 12:15:00,1,עיגון מדויק,3,לא-עירונית בצומת,8,כביש ישר / צומת,4,יום אחר,34,מרחב נגב,0,NaN,3,מיפרדה בנויה ללא גדר בטיחות,5,"90 קמ""ש",1,אין ליקויים,4,10.5 עד 14 מטר,3,אין ליקוי,1,אור יום רגיל,2.0,רמזור תקין,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,60.0,NaN,0.0,0.0,t,600005.0,5.0,יישוב באר שבע (לערד) - צומת חטיבת הנגב,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,4,רביעי,1,כן,9.0,לא ידוע,99,NaN,999.0,NaN,99.0,מועצה מקומית,99.0,NaN,NaN,NaN,NaN,NaN,NaN,8015.0,NaN,יישוב באר שבע (לערד),NaN,2019,2,27,50,12:15-12:29,12,15,0101000020E6100000FEF8F1852066414044392327423D...,34.797868,31.239291,180717.0,572034.0
202628,2019004747,12019004747,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,1.0,2,התנגשות חזית בצד,3,קלה,2019-09-10 09:30:00,1,עיגון מדויק,3,לא-עירונית בצומת,9,אחר,4,יום אחר,34,מרחב נגב,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,2.0,רמזור תקין,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,60.0,NaN,0.0,0.0,t,600005.0,5.0,יישוב באר שבע (לערד) - צומת חטיבת הנגב,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,3,שלישי,1,כן,9.0,לא ידוע,99,NaN,999.0,NaN,99.0,מועצה מקומית,99.0,NaN,NaN,NaN,NaN,NaN,NaN,8015.0,NaN,יישוב באר שבע (לערד),NaN,2019,9,10,39,09:30-09:44,9,30,0101000020E6100000FEF8F1852066414044392327423D...,34.797868,31.239291,180717.0,572034.0
782328,2019056033,32019056033,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,3.0,4,התנגשות צד בצד,3,קלה,2019-05-16 16:00:00,1,עיגון מדויק,3,לא-עירונית בצומת,9,אחר,4,יום אחר,14,מרחב עמקים,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,75.0,NaN,171.0,171.0,t,750030.0,30.0,צומת נצרת (דרום) - צומת מגדל העמק,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1077.0,NaN,צומת נצרת (דרום),NaN,2019,5,16,65,16:00-16:14,16,0,0101000020E6100000E268982E5DA541401E54AEF4BD58...,35.291906,32.693297,227652.0,733197.0
782329,2019056033,32019056033,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,3.0,4,התנגשות צד בצד,3,קלה,2019-05-16 16:00:00,1,עיגון מדויק,3,לא-עירונית בצומת,9,אחר,4,יום אחר,14,מרחב עמקים,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,75.0,NaN,171.0,171.0,t,750020.0,20.0,כניסה לקריית הממשלה - צומת נצרת (דרום),0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1077.0,NaN,צומת נצרת (דרום),NaN,2019,5,16,65,16:00-16:14,16,0,0101000020E6100000E268982E5DA541401E54AEF4BD58...,35.291906,32.693297,227652.0,733197.0
787592,2019071126,32019071126,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,3.0,3,התנגשות חזית באחור,3,קלה,2019-02-12 18:15:00,1,עיגון מדויק,3,לא-עירונית בצומת,9,אחר,4,יום אחר,52,מרחב שפלה,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,6,לילה לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,431.0,4313.0,160.0,160.0,t,4310040.0,40.0,מחלף ראשונים - מחלף נס ציונה,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,3,שלישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4186.0,NaN,מחלף נס ציונה,NaN,2019,2,12,74,18:15-18:29,18,15,0101000020E6100000C728FC506A6841404D65ED227BF0...,34.815745,31.939379,182696.0,649655.0
796815,2019095698,32019095698,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,3.0,3,התנגשות חזית באחור,3,קלה,2019-05-03 16:00:00,1,עיגון מדויק,3,לא-עירונית בצומת,9,אחר,4,יום אחר,14,מרחב עמקים,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,75.0,NaN,171.0,171.0,t,750030.0,30.0,צומת נצרת (דרום) - צומת מגדל העמק,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,6,שישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1077.0,NaN,צומת נצרת (דרום),NaN,2019,5,3,65,16:00-16:14,16,0,0101000020E6100000E268982E5DA541401E54AEF4BD58...,35.291906,32.693297,227652.0,733197.0
796816,2019095698,32019095698,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,3.0,3,התנגשות חזית באחור,3,קלה,2019-05-03 16:00:00,1,עיגון מדויק,3,לא-עירונית בצומת,9,אחר,4,יום אחר,14,מרחב עמקים,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,...,לא ידוע,75.0,NaN,171.0,171.0,t,750020.0,20.0,כניסה לקריית הממשלה - צומת נצרת (דרום),0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,6,שישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1077.0,NaN,צומת נצרת (דרום),NaN,2019,5,3,65,16:00-16:14,16,0,0101000020E6100000E268982E5DA541401E54AEF4BD58...,35.291906,32.693297,227652.0,733197.0

In [123]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts()

1077.0    4
8015.0    2
4186.0    1
Name: non_urban_intersection, dtype: int64

In [125]:
m_all[m_all['non_urban_intersection'] == 1077].shape

(4, 101)

In [16]:
m_all[m_all['non_urban_intersection'] == 1077][['non_urban_intersection','non_urban_intersection_hebrew','non_urban_intersection_by_junction_number','km','road1','road2','provider_and_id']]

,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,km,road1,road2,provider_and_id
782328,1077.0,NaN,צומת נצרת (דרום),171.0,75.0,NaN,32019056033
782329,1077.0,NaN,צומת נצרת (דרום),171.0,75.0,NaN,32019056033
796815,1077.0,NaN,צומת נצרת (דרום),171.0,75.0,NaN,32019095698
796816,1077.0,NaN,צומת נצרת (דרום),171.0,75.0,NaN,32019095698

In [126]:
m_all[m_all['non_urban_intersection'] == 8015].shape

(2, 101)

In [17]:
m_all[m_all['non_urban_intersection'] == 8015][['non_urban_intersection','non_urban_intersection_hebrew','non_urban_intersection_by_junction_number','km','road1','road2','provider_and_id']]

,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,km,road1,road2,provider_and_id
5924,8015.0,NaN,יישוב באר שבע (לערד),0.0,60.0,NaN,12019025840
202628,8015.0,NaN,יישוב באר שבע (לערד),0.0,60.0,NaN,12019004747

In [127]:
m_all[m_all['non_urban_intersection'] == 4186].shape

(3, 101)

In [15]:
m_all[m_all['non_urban_intersection'] == 4186][['non_urban_intersection','non_urban_intersection_hebrew','non_urban_intersection_by_junction_number','km','road1','road2','provider_and_id']]

,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,km,road1,road2,provider_and_id
767096,4186.0,מחלף נס ציונה,מחלף נס ציונה,65.0,423.0,431.0,32019012216
787592,4186.0,NaN,מחלף נס ציונה,160.0,431.0,4313.0,32019071126
791105,4186.0,מחלף נס ציונה,מחלף נס ציונה,160.0,431.0,423.0,32019080980

**Null conclusions** of `non_urban_intersection`:  It's mostly our internal issue since in all cases `non_urban_intersection_by_junction_number` is not empty.
 Issues: All values of 1077, 8015, some values of 4186

In [129]:
m_all['non_urban_intersection'].nunique()

797

**Specific values conclusion:** because of issues above, and so many unique values, not investigated

## accident_hour_raw and accident_hour_raw_hebrew

In [131]:
# accident_hour_raw                            53030 non-null int64
# accident_hour_raw_hebrew                     53030 non-null object

In [132]:
calc_diff_counts_hebrew(m_all, 'accident_hour_raw')

Shape of data: (53030, 101)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
52    0
53    0
54    0
55    0
56    0
57    0
58    0
59    0
60    0
61    0
62    0
63    0
64    0
65    0
66    0
67    0
68    0
69    0
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
91    0
92    0
93    0
94    0
95    0
dtype: int64