#### High level:
This notebook shows all the inconsistencies of field that were produced with dictionaries (and have `hebrew` in the name) with their respective numeric values for the `markers_hebrew` table.

The specific analysis below is based on data from `2019-11-16_views_and_main_tables` folder from Nov 16, 2019 that can be found here: https://drive.google.com/drive/folders/1StZkyR7KG_cfPpk8xMj5es3HGkIA00C9?usp=sharing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
pd.options.display.max_rows = 200
pd.options.display.max_columns = 100

In [3]:
markers_raw = pd.read_csv('../../views_and_main_tables_2019_11/markers_hebrew.csv')
m_all = markers_raw[markers_raw['accident_year'] < 2019]

C:\Users\rkrichev\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (23,90) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
m_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 720541 entries, 0 to 761517
Data columns (total 98 columns):
id                                           720541 non-null int64
provider_and_id                              720541 non-null int64
provider_code                                720541 non-null int64
provider_code_hebrew                         720541 non-null object
file_type_police                             55400 non-null float64
accident_type                                720541 non-null int64
accident_type_hebrew                         720541 non-null object
accident_severity                            720541 non-null int64
accident_severity_hebrew                     720541 non-null object
accident_timestamp                           720541 non-null object
location_accuracy                            720541 non-null int64
location_accuracy_hebrew                     720541 non-null object
road_type                                    720541 non-null int64
road_type_hebrew                             720541 non-null object
road_shape                                   720541 non-null int64
road_shape_hebrew                            720538 non-null object
day_type                                     720541 non-null int64
day_type_hebrew                              720541 non-null object
police_unit                                  720541 non-null int64
police_unit_hebrew                           720541 non-null object
one_lane                                     720541 non-null int64
one_lane_hebrew                              657395 non-null object
multi_lane                                   720541 non-null int64
multi_lane_hebrew                            63177 non-null object
speed_limit                                  720541 non-null int64
speed_limit_hebrew                           720540 non-null object
road_intactness                              720541 non-null int64
road_intactness_hebrew                       720541 non-null object
road_width                                   720541 non-null int64
road_width_hebrew                            720541 non-null object
road_sign                                    720541 non-null int64
road_sign_hebrew                             720541 non-null object
road_light                                   720541 non-null int64
road_light_hebrew                            720541 non-null object
road_control                                 80906 non-null float64
road_control_hebrew                          80904 non-null object
weather                                      720541 non-null int64
weather_hebrew                               720541 non-null object
road_surface                                 720541 non-null int64
road_surface_hebrew                          720541 non-null object
road_object                                  720541 non-null int64
road_object_hebrew                           720541 non-null object
object_distance                              720541 non-null int64
object_distance_hebrew                       720477 non-null object
didnt_cross                                  720541 non-null int64
didnt_cross_hebrew                           720538 non-null object
cross_mode                                   720541 non-null int64
cross_mode_hebrew                            33365 non-null object
cross_location                               720541 non-null int64
cross_location_hebrew                        28925 non-null object
cross_direction                              720541 non-null int64
cross_direction_hebrew                       720541 non-null object
road1                                        154049 non-null float64
road2                                        146383 non-null float64
km                                           140626 non-null float64
km_raw                                       140626 non-null float64
km_accurate                                  140626 non-null object
yishuv_symbol                                720541 non-null int64
yishuv_name                                  560665 non-null object
geo_area                                     720541 non-null int64
geo_area_hebrew                              720541 non-null object
day_night                                    720541 non-null int64
day_night_hebrew                             720541 non-null object
day_in_week                                  720541 non-null int64
day_in_week_hebrew                           720541 non-null object
traffic_light                                720541 non-null int64
traffic_light_hebrew                         720541 non-null object
region                                       605597 non-null float64
region_hebrew                                565389 non-null object
district                                     720541 non-null int64
district_hebrew                              561538 non-null object
natural_area                                 605597 non-null float64
natural_area_hebrew                          557164 non-null object
municipal_status                             604357 non-null float64
municipal_status_hebrew                      604314 non-null object
yishuv_shape                                 605597 non-null float64
yishuv_shape_hebrew                          561532 non-null object
street1                                      553240 non-null float64
street1_hebrew                               389936 non-null object
street2                                      71838 non-null float64
street2_hebrew                               70713 non-null object
house_number                                 487549 non-null float64
non_urban_intersection                       34382 non-null float64
non_urban_intersection_hebrew                33018 non-null object
non_urban_intersection_by_junction_number    33136 non-null object
urban_intersection                           70730 non-null float64
accident_year                                720541 non-null int64
accident_month                               720541 non-null int64
accident_day                                 720541 non-null int64
accident_hour_raw                            720541 non-null int64
accident_hour_raw_hebrew                     322739 non-null object
accident_hour                                720541 non-null int64
accident_minute                              720541 non-null int64
geom                                         710613 non-null object
longitude                                    710613 non-null float64
latitude                                     710613 non-null float64
x                                            710613 non-null float64
y                                            710613 non-null float64
dtypes: float64(19), int64(37), object(42)
memory usage: 544.2+ MB

### Helper functions

In [77]:
def calc_diff_counts_hebrew(data, feat_name):
    data = data[(data[feat_name].isnull() == False) & (data[feat_name + '_hebrew'].isnull() == False)]
    print(f'Shape of data: {data.shape}')
    return data[feat_name].value_counts().reset_index(drop=True) - \
           data[feat_name + '_hebrew'].value_counts().reset_index(drop=True)

In [152]:
def merge_with_hebrew(data, feat_name):
    nums_df = data[feat_name].value_counts().reset_index()
    nums_df.columns = ['index_' + feat_name, 'count']

    hebrew_df = data[feat_name + '_hebrew'].value_counts().reset_index()
    hebrew_df.columns = ['index_' + feat_name + '_hebrew', 'count']

    return pd.merge(nums_df, hebrew_df, how='outer', on='count')

### road_shape and road_shape_hebrew

In [4]:
# road_shape                                   720541 non-null int64
# road_shape_hebrew                            720538 non-null object
m_all[(m_all['road_shape'].isnull() == False) & (m_all['road_shape_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
218018,2008060753,32008060753,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2008-04-17 17:30:00,3,מרכז דרך,4,לא-עירונית לא בצומת,0,NaN,4,יום אחר,51,מרחב השרון,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,471.0,0.0,NaN,NaN,NaN,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,4,17,71,NaN,17,30,0101000020E61000007983A3FF237241400F7DC91FDB08...,34.891724,32.069187,189922.0,664026.0
225363,2008069185,32008069185,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2008-10-27 19:15:00,3,מרכז דרך,4,לא-עירונית לא בצומת,0,NaN,4,יום אחר,51,מרחב השרון,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,6,לילה לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,471.0,0.0,NaN,NaN,NaN,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,10,27,78,NaN,19,15,0101000020E61000007983A3FF237241400F7DC91FDB08...,34.891724,32.069187,189922.0,664026.0
503229,2012052602,32012052602,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2012-12-03 18:30:00,1,עיגון מדויק,4,לא-עירונית לא בצומת,15,NaN,4,יום אחר,52,מרחב שפלה,1,חד סיטרי,0,NaN,5,"90 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,3,לילה פעלה תאורה,NaN,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,5.0,0.0,190.0,190.0,t,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,12,3,75,NaN,18,30,0101000020E61000004CD62616D67E414060719F754C0D...,34.990908,32.103896,199295.0,667852.0

In [5]:
m_all[(m_all['road_shape']==0) & (m_all['accident_year']==2008)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
218018,2008060753,32008060753,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2008-04-17 17:30:00,3,מרכז דרך,4,לא-עירונית לא בצומת,0,NaN,4,יום אחר,51,מרחב השרון,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,471.0,0.0,NaN,NaN,NaN,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,4,17,71,NaN,17,30,0101000020E61000007983A3FF237241400F7DC91FDB08...,34.891724,32.069187,189922.0,664026.0
225363,2008069185,32008069185,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2008-10-27 19:15:00,3,מרכז דרך,4,לא-עירונית לא בצומת,0,NaN,4,יום אחר,51,מרחב השרון,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,6,לילה לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,471.0,0.0,NaN,NaN,NaN,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,10,27,78,NaN,19,15,0101000020E61000007983A3FF237241400F7DC91FDB08...,34.891724,32.069187,189922.0,664026.0

In [7]:
m_all[m_all['road_shape']==0]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
218018,2008060753,32008060753,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2008-04-17 17:30:00,3,מרכז דרך,4,לא-עירונית לא בצומת,0,NaN,4,יום אחר,51,מרחב השרון,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,471.0,0.0,NaN,NaN,NaN,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,4,17,71,NaN,17,30,0101000020E61000007983A3FF237241400F7DC91FDB08...,34.891724,32.069187,189922.0,664026.0
225363,2008069185,32008069185,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2008-10-27 19:15:00,3,מרכז דרך,4,לא-עירונית לא בצומת,0,NaN,4,יום אחר,51,מרחב השרון,9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,6,לילה לא ידוע,NaN,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,471.0,0.0,NaN,NaN,NaN,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,10,27,78,NaN,19,15,0101000020E61000007983A3FF237241400F7DC91FDB08...,34.891724,32.069187,189922.0,664026.0

In [6]:
m_all[(m_all['road_shape']==15) & (m_all['accident_year']==2012)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
503229,2012052602,32012052602,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2012-12-03 18:30:00,1,עיגון מדויק,4,לא-עירונית לא בצומת,15,NaN,4,יום אחר,52,מרחב שפלה,1,חד סיטרי,0,NaN,5,"90 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,3,לילה פעלה תאורה,NaN,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,5.0,0.0,190.0,190.0,t,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,12,3,75,NaN,18,30,0101000020E61000004CD62616D67E414060719F754C0D...,34.990908,32.103896,199295.0,667852.0

In [8]:
m_all[m_all['road_shape']==15]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
503229,2012052602,32012052602,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,3,התנגשות חזית באחור,3,קלה,2012-12-03 18:30:00,1,עיגון מדויק,4,לא-עירונית לא בצומת,15,NaN,4,יום אחר,52,מרחב שפלה,1,חד סיטרי,0,NaN,5,"90 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,3,לילה פעלה תאורה,NaN,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,5.0,0.0,190.0,190.0,t,0,NaN,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,12,3,75,NaN,18,30,0101000020E61000004CD62616D67E414060719F754C0D...,34.990908,32.103896,199295.0,667852.0

**Null Conclusion**: seems that all `road_shape` 0 and 15 don't have translation into `road_shape_hebrew`

**Specific values mistmatch investigations:**

In [17]:
m_all[(m_all['road_shape']!=0) & (m_all['road_shape']!=15)]['road_shape'].value_counts()

9     462341
8     253586
5       2048
4        922
1        361
3        316
6        311
10       206
11       166
2        157
7        124
Name: road_shape, dtype: int64

In [18]:
m_all[(m_all['road_shape']!=0) & (m_all['road_shape']!=15)]['road_shape_hebrew'].value_counts()

אחר                    462341
כביש ישר / צומת        253586
עקום חד                  2048
שיפוע תלול                922
כניסה למחלף               361
מ. חניה / ת. דלק          316
על גשר/ בתוך מנהרה        261
תחנת אוטובוס              206
נתיב תחבורה ציבורית       166
ביציאה ממחלף              157
מפגש מסילת ברזל           124
על גשר מנהרה               50
Name: road_shape_hebrew, dtype: int64

In [78]:
calc_diff_counts_hebrew(m_all[(m_all['road_shape']!=0) & (m_all['road_shape']!=15)], 'road_shape')

Shape of data: (720538, 98)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6     50.0
7      0.0
8      0.0
9      0.0
10     0.0
11     NaN
dtype: float64

In [21]:
m_all[m_all['road_shape_hebrew'] == 'על גשר מנהרה'].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,5.000000e+01,5.000000e+01,50.0,0.0,50.000000,50.000000,50.000000,50.000000,50.0,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,8.000000,50.000000,50.000000,50.000000,50.0000,50.000000,50.000000,50.000000,50.000000,20.000000,20.000000,19.000000,19.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,29.000000,3.000000,27.000000,5.000000,2.000000e+00,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,2.009121e+09,1.200912e+10,1.0,NaN,5.000000,2.640000,1.820000,2.640000,6.0,3.860000,23.060000,1.440000,0.680000,2.340000,1.000000,2.88000,3.100000,2.780000,4.375000,1.080000,1.240000,8.180000,7.4200,8.920000,0.080000,0.220000,8.700000,50.750000,2.200000,679.473684,676.736842,2376.180000,1.060000,2.84000,3.800000,7.980000,5.560000,60.020000,604.820000,41.720000,47.980000,1195.241379,1045.333333,4147.962963,5716.200000,4.015520e+07,2009.080000,6.600000,15.520000,55.700000,13.380000,17.700000,34.992650,32.293490,199477.100000,688893.620000
std,9.166888e+05,9.166888e+05,0.0,NaN,3.528311,0.631163,0.962353,0.984782,0.0,0.495284,15.630178,1.197957,1.168288,1.636447,0.349927,0.91785,0.505076,2.418382,2.825269,0.274048,1.152814,1.769238,3.0445,0.395897,0.444467,1.298193,1.488048,96.334874,9.838699,745.664012,748.286550,2451.521216,0.239898,2.01383,2.060315,2.795696,3.038259,33.882444,342.228214,49.247828,42.237178,2026.089560,1710.246279,4947.324782,3478.398151,5.656175e+07,0.922286,3.614032,9.071687,25.666821,6.410737,14.749957,0.194294,0.400497,18335.102435,44399.949627
min,2.008003e+09,1.200800e+10,1.0,NaN,1.000000,1.000000,1.000000,1.000000,6.0,2.000000,11.000000,0.000000,0.000000,1.000000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.0000,7.000000,0.000000,0.000000,1.000000,2.000000,0.000000,17.000000,-26.000000,0.000000,1.000000,1.00000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,145.000000,0.000000,1.000000,311.000000,1.600020e+05,2008.000000,1.000000,1.000000,3.000000,0.000000,0.000000,34.641327,31.406168,166117.000000,590478.000000
25%,2.008072e+09,1.200807e+10,1.0,NaN,3.000000,2.000000,1.000000,2.000000,6.0,4.000000,11.000000,0.000000,0.000000,1.000000,1.000000,2.00000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.0000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,149.000000,149.000000,0.000000,1.000000,1.00000,2.000000,9.000000,3.000000,31.000000,311.000000,0.000000,12.250000,215.000000,58.500000,30.500000,4083.000000,2.015760e+07,2008.000000,4.000000,7.000000,35.250000,8.000000,0.000000,34.821717,32.038535,183326.250000,660668.250000
50%,2.009032e+09,1.200903e+10,1.0,NaN,3.000000,3.000000,1.000000,2.000000,6.0,4.000000,20.000000,1.500000,0.000000,1.000000,1.000000,3.00000,3.000000,2.000000,4.500000,1.000000,1.000000,9.000000,9.0000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,300.000000,300.000000,2069.500000,1.000000,1.00000,4.000000,9.000000,5.000000,51.000000,511.000000,0.000000,15.500000,525.000000,117.000000,218.000000,8046.000000,4.015520e+07,2009.000000,6.500000,17.000000,57.000000,14.000000,15.000000,34.973473,32.146841,197716.000000,672650.500000
75%,2.010014e+09,1.201001e+10,1.0,NaN,8.000000,3.000000,3.000000,4.000000,6.0,4.000000,20.000000,2.000000,1.750000,4.000000,1.000000,3.00000,3.000000,3.000000,7.000000,1.000000,1.000000,9.000000,9.0000,9.000000,0.000000,0.000000,9.000000,60.000000,0.000000,946.500000,946.500000,4000.000000,1.000000,5.00000,5.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,1035.000000,1568.000000,9999.000000,8065.000000,6.015280e+07,2010.000000,9.750000,22.750000,76.500000,18.750000,30.000000,35.152412,32.689298,214551.250000,732754.750000
max,2.011067e+09,1.201107e+10,1.0,NaN,15.000000,3.000000,3.000000,4.000000,6.0,4.000000,61.000000,4.000000,4.000000,5.000000,3.000000,5.00000,5.000000,11.000000,7.000000,2.000000,9.000000,9.000000,9.0000,9.000000,3.000000,9.000000,9.000000,444.000000,44.000000,2182.000000,2182.000000,8200.000000,2.000000,5.00000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,3019.000000,9999.000000,8076.000000,8.015040e+07,2011.000000,12.000000,30.000000,95.000000,23.000000,45.000000,35.473897,32.922816,244774.000000,758652.000000

In [22]:
m_all[m_all['road_shape_hebrew'] == 'על גשר/ בתוך מנהרה'].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,2.610000e+02,2.610000e+02,261.000000,30.000000,261.000000,261.000000,261.000000,261.000000,261.0,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,136.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,130.000000,126.000000,128.000000,128.000000,261.000000,261.000000,261.000000,261.000000,261.000000,255.000000,261.000000,255.000000,255.000000,255.000000,131.000000,24.000000,103.000000,57.000000,2.400000e+01,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000
mean,2.014837e+09,1.270449e+10,1.068966,1.200000,4.505747,2.735632,1.689655,2.662835,6.0,3.862069,30.946360,1.111111,1.157088,2.371648,1.003831,2.804598,3.038314,2.333333,3.904412,1.210728,1.195402,8.383142,8.000000,8.961686,0.076628,0.099617,8.681992,392.215385,200.539683,564.156250,564.031250,2355.088123,1.019157,2.609195,3.957854,6.750958,6.074510,66.574713,663.219608,50.509804,55.494118,1448.900763,967.583333,6322.388350,3885.087719,1.734242e+07,2014.796935,6.160920,15.375479,53.532567,12.800766,19.942529,34.989392,32.267601,199162.666667,686022.762452
std,2.081276e+06,3.656403e+09,0.365632,0.610257,3.156947,0.529000,0.927905,0.992916,0.0,0.571888,19.780259,1.446186,1.417690,1.634896,0.297400,1.093749,0.325912,2.051266,2.372305,0.893158,0.874938,1.583188,2.505379,0.313889,0.384645,0.478017,1.522404,1329.760024,875.713009,760.161084,760.254567,2901.204976,0.137340,1.965215,1.988947,3.655771,3.072346,34.305852,347.046264,49.266179,42.558517,1897.150271,1095.258831,4832.129913,3556.434618,2.505169e+07,2.073864,3.326607,8.723356,25.356760,6.343270,16.422796,0.188564,0.414975,17784.847838,46009.015646
min,2.012001e+09,1.201200e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.0,1.000000,11.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,-8.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,11.000000,0.000000,108.000000,1.000000,7.000000,8.062100e+04,2012.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.629337,31.323147,164980.000000,581295.000000
25%,2.013019e+09,1.201302e+10,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,6.0,4.000000,11.000000,0.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,60.000000,60.000000,0.000000,1.000000,1.000000,2.000000,1.000000,3.000000,32.000000,317.500000,0.000000,13.000000,295.500000,320.750000,35.000000,481.000000,2.975342e+05,2013.000000,3.000000,8.000000,37.000000,9.000000,0.000000,34.829340,31.979922,184017.000000,654164.000000
50%,2.015012e+09,1.201502e+10,1.000000,1.000000,3.000000,3.000000,1.000000,2.000000,6.0,4.000000,20.000000,1.000000,0.000000,1.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,40.000000,0.000000,210.000000,210.000000,70.000000,1.000000,1.000000,4.000000,9.000000,6.000000,62.000000,613.000000,99.000000,31.000000,916.000000,822.000000,9999.000000,4006.000000,9.980079e+06,2015.000000,6.000000,15.000000,57.000000,14.000000,15.000000,34.957442,32.134671,196190.000000,671305.000000
75%,2.017018e+09,1.201702e+10,1.000000,1.000000,5.000000,3.000000,3.000000,4.000000,6.0,4.000000,51.000000,2.000000,2.000000,4.000000,1.000000,3.000000,3.000000,3.000000,7.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,83.500000,6.000000,792.500000,792.500000,4000.000000,1.000000,5.000000,6.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,1405.000000,1043.500000,9999.000000,8054.000000,2.046810e+07,2017.000000,9.000000,23.000000,73.000000,18.000000,30.000000,35.100809,32.725742,209748.000000,736797.000000
max,2.018100e+09,3.201806e+10,3.000000,3.000000,17.000000,3.000000,4.000000,4.000000,6.0,4.000000,61.000000,9.000000,5.000000,7.000000,3.000000,5.000000,4.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,3.000000,4.000000,9.000000,9779.000000,5720.000000,3001.000000,3001.000000,9600.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9992.000000,4316.000000,9999.000000,9970.000000,9.287128e+07,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.641975,33.182675,260295.000000,787544.000000

**Specific values conclusions:**
- Till 2011 (including) `road_shape` 3 was called `על גשר מנהרה` that was later changed to `על גשר/ בתוך מנהרה`

### one_lane and one_lane_hebrew

In [10]:
# one_lane                                     720541 non-null int64
# one_lane_hebrew                              657395 non-null object
m_all[(m_all['one_lane'].isnull() == False) & (m_all['one_lane_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,6.314600e+04,6.314600e+04,63146.000000,4953.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.0,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,39342.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,20449.000000,20096.000000,19825.000000,19825.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,62712.000000,63146.000000,62712.000000,62690.000000,62712.000000,42354.000000,22591.000000,19005.000000,8.964000e+03,2.239200e+04,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,63146.000000,62998.000000,62998.000000,62998.000000,62998.000000
mean,2.012672e+09,1.238197e+10,1.036930,1.022613,3.178159,2.859817,1.495265,2.129161,8.245922,3.879137,32.359421,0.0,2.643097,2.209182,0.868416,2.825785,3.044358,2.175926,3.323319,1.173756,1.162449,8.634466,8.472793,8.936750,0.423368,0.452649,8.024198,255.365103,441.041600,798.142598,796.009937,3513.802394,1.021696,2.457004,3.782932,5.178871,5.493654,59.229199,593.801075,34.465337,41.382351,946.799027,903.479483,6162.511181,1.164786e+04,1.679112e+07,2012.630792,6.265385,15.571263,55.103807,13.205714,19.214281,34.948469,32.149536,195260.083542,672940.915188
std,3.220278e+06,2.692632e+09,0.269254,0.211478,2.894097,0.405151,0.908892,1.103730,0.781467,0.510024,18.304831,0.0,0.736754,1.707097,0.374449,1.212679,0.567256,1.929704,2.162129,0.980203,0.929502,1.384110,1.861980,0.477731,1.109848,1.179556,2.545819,929.606326,1505.027249,949.725821,951.514106,3263.986605,0.145689,1.924893,1.924918,4.139565,2.742688,30.562598,307.927894,48.280026,39.655058,1284.827984,1100.998740,4840.782334,8.465430e+05,2.314225e+07,3.215860,3.409007,8.793801,23.606092,5.894208,16.703595,0.198667,0.468848,18784.281714,51972.555006
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.0,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-298.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.293560,29.493021,132646.000000,378409.000000
25%,2.010015e+09,1.201002e+10,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,8.000000,4.000000,14.000000,0.0,2.000000,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,130.000000,127.000000,0.000000,1.000000,1.000000,2.000000,1.000000,4.000000,41.000000,411.000000,0.000000,13.000000,206.000000,238.000000,43.000000,7.290000e+02,7.810034e+06,2010.000000,3.000000,8.000000,38.000000,9.000000,0.000000,34.798138,31.855066,181022.000000,640251.750000
50%,2.012063e+09,1.201300e+10,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,8.000000,4.000000,33.000000,0.0,3.000000,1.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,42.000000,0.000000,353.000000,353.000000,3000.000000,1.000000,1.000000,4.000000,9.000000,5.000000,51.000000,511.000000,0.000000,15.000000,502.000000,507.000000,9999.000000,1.393000e+03,9.600014e+06,2012.000000,6.000000,16.000000,57.000000,14.000000,15.000000,34.899238,32.077911,190634.000000,665006.000000
75%,2.015092e+09,1.201601e+10,1.000000,1.000000,3.000000,3.000000,2.000000,3.000000,9.000000,4.000000,51.000000,0.0,3.000000,4.000000,1.000000,3.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,85.000000,40.000000,1241.000000,1241.000000,6600.000000,1.000000,5.000000,5.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,1033.000000,1019.000000,9999.000000,4.050000e+03,1.700021e+07,2015.000000,9.000000,23.000000,73.000000,18.000000,30.000000,35.093269,32.471484,209027.000000,708616.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,0.0,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9998.000000,9998.000000,9999.000000,9999.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,999.000000,99.000000,9998.000000,9993.000000,11111.000000,8.015165e+07,1.000000e+08,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.801848,33.280197,275383.000000,798342.000000

In [11]:
m_all[(m_all['one_lane'].isnull() == False) & (m_all['one_lane_hebrew'].isnull() == True)].shape

(63146, 98)

In [13]:
m_all[m_all['one_lane'] == 0].shape

(63146, 98)

**Null Conclusion:** `one_lane` == 0 of all years is missing

**Specific values mistmatch investigations:**

In [79]:
calc_diff_counts_hebrew(m_all[m_all['one_lane'] != 0], 'one_lane')

Shape of data: (657395, 98)

0    0
1    0
2    0
3    0
4    0
dtype: int64

**Specific values conclusion:** no issues

### multi_lane and multi_lane_hebrew

In [14]:
# multi_lane                                   720541 non-null int64
# multi_lane_hebrew                            63177 non-null object
m_all[(m_all['multi_lane'].isnull() == False) & (m_all['multi_lane_hebrew'].isnull() == True)].shape

(657364, 98)

In [15]:
m_all[(m_all['multi_lane'].isnull() == False) & (m_all['multi_lane_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,6.573640e+05,6.573640e+05,657364.000000,50447.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.0,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,41554.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,133590.000000,126277.000000,120791.000000,120791.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,542864.000000,657364.000000,542864.000000,541646.000000,542864.000000,510866.000000,49244.000000,468526.000000,2.541400e+04,4.833500e+04,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,657364.000000,647584.000000,647584.000000,647584.000000,647584.000000
mean,2.012698e+09,2.919538e+10,2.718269,2.708684,4.829880,2.976384,2.406463,2.303838,8.657302,3.896716,30.778050,8.210942,0.0,0.221895,0.110754,0.296340,4.763510,8.798378,4.446215,8.031570,8.036940,8.877794,8.942682,8.966620,0.119251,0.095857,8.846517,399.149023,179.843400,688.864228,684.668518,3856.784460,1.024251,2.039491,3.631188,8.572751,4.011673,52.172947,425.361019,14.937803,19.859084,768.464427,809.116887,8650.870515,1.882986e+04,1.388055e+07,2012.656536,6.428892,15.652716,54.764905,13.140347,18.052761,34.964841,32.180087,196794.762990,676329.240749
std,3.194208e+06,6.957639e+09,0.695766,0.705533,4.116705,0.170989,1.651954,0.840542,0.557364,0.466855,17.804513,2.175194,0.0,4.238523,0.335081,0.873804,0.663001,3.302644,2.332783,2.599665,2.589624,0.791455,10.023855,0.366774,0.703511,0.650747,1.073541,1387.219504,985.621772,864.316766,867.644204,3235.215737,0.153829,1.754260,1.870957,1.867604,1.851469,27.728113,193.491013,35.275069,17.978236,1402.164538,929.903644,3406.400880,1.164231e+06,2.111140e+07,3.189286,3.423199,8.785176,20.342496,5.089282,16.567923,0.219809,0.495447,20759.862978,54921.562502
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,1.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-1.000000,0.000000,-478.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,0.000000,0.000000,-40.000000,0.000000e+00,0.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.260947,29.493021,129666.000000,378409.000000
25%,2.010023e+09,3.200901e+10,3.000000,3.000000,3.000000,3.000000,1.000000,2.000000,8.000000,4.000000,14.000000,9.000000,0.0,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,100.000000,100.000000,256.000000,1.000000,1.000000,2.000000,9.000000,3.000000,31.000000,311.000000,0.000000,13.000000,0.000000,244.000000,9999.000000,3.450000e+02,6.300050e+05,2010.000000,3.000000,8.000000,39.000000,9.000000,0.000000,34.797935,31.916663,180900.000000,647116.000000
50%,2.012061e+09,3.201200e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,20.000000,9.000000,0.0,0.000000,0.000000,0.000000,5.000000,11.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,40.000000,0.000000,310.000000,310.000000,4000.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,431.000000,0.000000,14.000000,300.000000,505.000000,9999.000000,1.209000e+03,8.740022e+06,2012.000000,6.000000,16.000000,56.000000,13.000000,15.000000,34.895926,32.082714,190308.000000,665548.000000
75%,2.015093e+09,3.201504e+10,3.000000,3.000000,5.000000,3.000000,3.000000,2.000000,9.000000,4.000000,51.000000,9.000000,0.0,0.000000,0.000000,0.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,90.000000,0.000000,1000.000000,1000.000000,6900.000000,1.000000,5.000000,5.000000,9.000000,5.000000,62.000000,512.000000,0.000000,16.000000,895.000000,1005.000000,9999.000000,3.993000e+03,1.342081e+07,2015.000000,9.000000,23.000000,70.000000,17.000000,30.000000,35.120514,32.612096,211517.000000,724193.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,15.000000,4.000000,61.000000,9.000000,0.0,3383.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,9.000000,9.000000,9999.000000,9999.000000,9999.000000,9999.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,999.000000,99.000000,9999.000000,9998.000000,11111.000000,1.000000e+08,1.000000e+08,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.000000,799843.000000

In [16]:
m_all[m_all['multi_lane'] == 0].shape

(657364, 98)

**Null Conclusion:** `multi_lane` == 0 of all years is missing

**Specific values mistmatch investigations:**

In [80]:
calc_diff_counts_hebrew(m_all[m_all['multi_lane'] != 0], 'multi_lane')

Shape of data: (63177, 98)

0    0
1    0
2    0
3    0
4    0
dtype: int64

**Specific values conclusion:** no issues

### speed_limit and speed_limit_hebrew

In [19]:
# speed_limit                                  720541 non-null int64
# speed_limit_hebrew                           720540 non-null object
m_all[(m_all['speed_limit'].isnull() == False) & (m_all['speed_limit_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
670485,2017079392,32017079392,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,8,התנגשות עם עצם דומם,3,קלה,2017-09-02 12:45:00,1,עיגון מדויק,4,לא-עירונית לא בצומת,8,כביש ישר / צומת,4,יום אחר,38,מרחב לכיש,1,חד סיטרי,0,NaN,3383,NaN,1,אין ליקויים,4,10.5 עד 14 מטר,3,אין ליקוי,1,אור יום רגיל,NaN,NaN,1,בהיר,1,יבש,6,גדר בטיחות לרכב,1,עד מטר,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,6.0,0.0,910.0,910.0,t,0,NaN,1,ישראל ללא יהודה ושומרון,1,יום,7,שבת,9,לא ידוע,NaN,NaN,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,9,2,52,12:45-12:59,12,45,0101000020E6100000E6E9282E0D694140CCAE7A7A55B6...,34.820715,31.712242,183077.0,624467.0

In [20]:
m_all[(m_all['speed_limit'].isnull() == False) & (m_all['speed_limit_hebrew'].isnull() == True)]['speed_limit']

670485    3383
Name: speed_limit, dtype: int64

In [21]:
m_all['speed_limit'].value_counts()

0       577210
1        96678
4        18629
5        13605
3         6390
2         6338
6          868
7          790
8           32
3383         1
Name: speed_limit, dtype: int64

**Null Conclusion:** Speed limit 3383 has wrong information

**Specific values mistmatch investigations:**

In [81]:
calc_diff_counts_hebrew(m_all[m_all['speed_limit'] != 3383], 'speed_limit')

Shape of data: (720540, 98)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

**Specific values conclusion:** no issues

### road_control and road_control_hebrew

In [23]:
# road_control                                 80906 non-null float64
# road_control_hebrew                          80904 non-null object
m_all[(m_all['road_control'].isnull() == False) & (m_all['road_control_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
64687,2010060525,12010060525,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,2,התנגשות חזית אל צד,3,קלה,2010-07-07 18:30:00,1,עיגון מדויק,1,עירונית בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",1,חד סיטרי,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,1,אור יום רגיל,0.0,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,5000,תל אביב -יפו,1,ישראל ללא יהודה ושומרון,1,יום,4,רביעי,9,לא ידוע,5.0,תל אביב,51,תל אביב,511.0,אזור תל אביב,0.0,עירייה,12.0,תל אביב-יפו,1135.0,אלנבי,461.0,הירקון,NaN,NaN,NaN,NaN,10380511.0,2010,7,7,75,NaN,18,30,0101000020E6100000888A4EC10C6241405BE555A46A09...,34.766014,32.073567,178054.0,664553.0
384308,2010026652,32010026652,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,15,אחר,3,קלה,2010-12-02 11:30:00,1,עיגון מדויק,1,עירונית בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,0.0,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,5000,תל אביב -יפו,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,1,כן,5.0,תל אביב,51,תל אביב,511.0,אזור תל אביב,0.0,עירייה,12.0,תל אביב-יפו,2731.0,"אצ""ל",2860.0,"לח""י",NaN,NaN,NaN,NaN,80150944.0,2010,12,2,47,NaN,11,30,0101000020E61000006FC8A1B3A36541400E6C32FA1A06...,34.794058,32.047698,180691.0,661674.0

In [24]:
m_all[m_all['road_control'] == 0]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
64687,2010060525,12010060525,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,2,התנגשות חזית אל צד,3,קלה,2010-07-07 18:30:00,1,עיגון מדויק,1,עירונית בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",1,חד סיטרי,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,1,אור יום רגיל,0.0,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,5000,תל אביב -יפו,1,ישראל ללא יהודה ושומרון,1,יום,4,רביעי,9,לא ידוע,5.0,תל אביב,51,תל אביב,511.0,אזור תל אביב,0.0,עירייה,12.0,תל אביב-יפו,1135.0,אלנבי,461.0,הירקון,NaN,NaN,NaN,NaN,10380511.0,2010,7,7,75,NaN,18,30,0101000020E6100000888A4EC10C6241405BE555A46A09...,34.766014,32.073567,178054.0,664553.0
384308,2010026652,32010026652,3,הלשכה המרכזית לסטטיסטיקה - סוג תיק 3,NaN,15,אחר,3,קלה,2010-12-02 11:30:00,1,עיגון מדויק,1,עירונית בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",9,לא ידוע מס מסלולים,0,NaN,0,לא ידוע,0,לא ידוע,0,לא ידוע,5,לא ידוע,11,יום לא ידוע,0.0,NaN,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,5000,תל אביב -יפו,1,ישראל ללא יהודה ושומרון,1,יום,5,חמישי,1,כן,5.0,תל אביב,51,תל אביב,511.0,אזור תל אביב,0.0,עירייה,12.0,תל אביב-יפו,2731.0,"אצ""ל",2860.0,"לח""י",NaN,NaN,NaN,NaN,80150944.0,2010,12,2,47,NaN,11,30,0101000020E61000006FC8A1B3A36541400E6C32FA1A06...,34.794058,32.047698,180691.0,661674.0

**Null Conclusion:** `road_control` == 0 of all years is missing, all in year 2010

**Specific values mistmatch investigations:**

In [82]:
calc_diff_counts_hebrew(m_all[(m_all['road_control'] != 0) | (m_all['accident_year'] != 2010)], 'road_control')

Shape of data: (80904, 98)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

**Specific values conclusion:** no issues

### object_distance and object_distance_hebrew

In [27]:
# object_distance                              720541 non-null int64
# object_distance_hebrew                       720477 non-null object
m_all[(m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].shape

(64, 98)

In [28]:
m_all[(m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,6.400000e+01,6.400000e+01,64.0,0.0,64.000000,64.0,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,1.0,64.000000,64.000000,64.000000,64.000000,64.0,64.0,64.0,64.0,27.000000,23.000000,24.000000,24.000000,64.000000,64.000000,64.000000,64.000000,64.000000,37.000000,64.000000,37.000000,37.000000,37.000000,37.000000,1.0,36.000000,1.0,1.0,64.000000,64.000000,64.00000,64.000000,64.000000,64.00000,63.000000,63.000000,63.000000,63.000000
mean,2.011755e+09,3.201176e+10,3.0,NaN,8.046875,3.0,2.203125,2.812500,8.859375,3.796875,31.875000,7.953125,0.109375,0.375000,0.093750,0.500000,4.687500,7.437500,6.0,7.562500,7.515625,5.328125,710.734375,9.0,0.0,0.0,9.0,811.666667,31.391304,555.875000,539.375000,1944.734375,1.093750,3.062500,3.937500,8.859375,4.135135,67.046875,439.405405,33.837838,21.054054,431.729730,124.0,7788.194444,1341.0,570031.0,2011.718750,6.953125,15.03125,52.062500,12.468750,17.81250,34.964118,32.091910,196657.793651,666558.555556
std,1.324987e+06,1.324987e+06,0.0,NaN,0.277728,0.0,1.928728,1.005935,0.559682,0.670931,16.769682,2.651323,0.507630,1.046536,0.293785,1.272418,0.731925,3.284765,NaN,3.028306,3.116735,2.828734,733.900370,0.0,0.0,0.0,0.0,1834.927687,150.547407,783.692615,795.632743,2945.633902,0.293785,2.014826,2.252864,1.125000,1.782043,30.578771,176.271801,42.488896,7.568010,1093.615427,NaN,4194.836634,NaN,NaN,1.314978,3.368527,8.29222,29.006225,7.213235,16.44797,0.254196,0.581042,24103.122914,64392.763297
min,2.010001e+09,3.201000e+10,3.0,NaN,8.000000,3.0,1.000000,1.000000,5.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,6.0,1.000000,1.000000,1.000000,5.000000,9.0,0.0,0.0,9.0,0.000000,0.000000,20.000000,-198.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,124.0,2.000000,1341.0,570031.0,2010.000000,1.000000,1.00000,1.000000,0.000000,0.00000,34.357415,31.039179,138754.000000,549798.000000
25%,2.011008e+09,3.201101e+10,3.0,NaN,8.000000,3.0,1.000000,2.000000,9.000000,4.000000,12.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,6.0,9.000000,9.000000,2.000000,5.000000,9.0,0.0,0.0,9.0,45.000000,0.000000,75.000000,64.250000,0.000000,1.000000,1.000000,2.000000,9.000000,2.000000,42.750000,245.000000,0.000000,14.000000,0.000000,124.0,9999.000000,1341.0,570031.0,2011.000000,4.000000,9.75000,31.000000,7.000000,0.00000,34.776427,31.608961,179014.000000,613033.500000
50%,2.012003e+09,3.201200e+10,3.0,NaN,8.000000,3.0,2.000000,2.000000,9.000000,4.000000,34.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,6.0,9.000000,9.000000,6.000000,5.000000,9.0,0.0,0.0,9.0,75.000000,0.000000,196.500000,192.500000,497.000000,1.000000,5.000000,4.000000,9.000000,4.000000,62.000000,441.000000,0.000000,17.000000,107.000000,124.0,9999.000000,1341.0,570031.0,2012.000000,8.000000,16.00000,56.000000,13.500000,15.00000,34.964248,32.083156,196692.000000,665590.000000
75%,2.013001e+09,3.201300e+10,3.0,NaN,8.000000,3.0,3.000000,4.000000,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.0,9.000000,9.000000,8.000000,1462.000000,9.0,0.0,0.0,9.0,444.500000,0.000000,530.000000,530.000000,2655.000000,1.000000,5.000000,6.000000,9.000000,6.000000,99.000000,621.000000,99.000000,28.000000,412.000000,124.0,9999.000000,1341.0,570031.0,2013.000000,9.000000,22.00000,77.250000,19.000000,30.00000,35.133929,32.584029,212818.000000,721084.500000
max,2.014098e+09,3.201410e+10,3.0,NaN,10.000000,3.0,9.000000,4.000000,9.000000,4.000000,61.000000,9.000000,3.000000,5.000000,1.000000,5.000000,5.000000,11.000000,6.0,9.000000,9.000000,9.000000,1462.000000,9.0,0.0,0.0,9.0,7212.000000,722.000000,3040.000000,3040.000000,9100.000000,2.000000,5.000000,7.000000,9.000000,7.000000,99.000000,770.000000,99.000000,33.000000,6500.000000,124.0,9999.000000,1341.0,570031.0,2014.000000,12.000000,31.00000,96.000000,23.000000,45.00000,35.571726,33.201772,253696.000000,789646.000000

In [31]:
m_all[(m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)]['object_distance'].value_counts()

5       33
1462    31
Name: object_distance, dtype: int64

In [29]:
m_all['object_distance'].value_counts()

9       704216
2         7270
1         6489
4         1472
3          825
5          238
1462        31
Name: object_distance, dtype: int64

In [32]:
m_all[(m_all['object_distance']==5) & (m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].shape

(33, 98)

In [33]:
m_all[(m_all['object_distance']==5) & (m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,3.300000e+01,3.300000e+01,33.0,0.0,33.000000,33.0,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,1.0,33.000000,33.000000,33.000000,33.0,33.0,33.0,33.0,33.0,16.000000,14.0,14.000000,14.000000,33.000000,33.000000,33.000000,33.000000,33.000000,17.000000,33.000000,17.000000,17.000000,17.000000,17.000000,1.0,16.00000,0.0,1.0,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,2.012832e+09,3.201283e+10,3.0,NaN,8.060606,3.0,1.575758,2.939394,8.878788,3.666667,29.696970,7.636364,0.212121,0.484848,0.181818,0.666667,4.575758,7.000000,6.0,7.333333,7.333333,5.545455,5.0,9.0,0.0,0.0,9.0,442.000000,0.0,627.214286,627.214286,2095.090909,1.121212,3.181818,3.909091,8.727273,4.176471,70.787879,444.411765,23.411765,18.823529,714.117647,124.0,6268.31250,NaN,570031.0,2012.787879,6.606061,16.181818,59.030303,14.212121,17.727273,34.992014,32.108428,199335.818182,668378.696970
std,8.657929e+05,8.657929e+05,0.0,NaN,0.348155,0.0,0.791766,1.058873,0.331434,0.853913,16.711682,3.008511,0.696311,1.202113,0.391675,1.471960,0.830298,3.436932,NaN,3.265986,3.265986,2.682011,0.0,0.0,0.0,0.0,0.0,1242.537672,0.0,849.775824,849.775824,3062.456983,0.331434,2.022600,2.309811,1.566699,1.810915,30.681588,183.065924,38.543902,7.195791,1540.748433,NaN,4974.47826,NaN,NaN,0.857233,3.463555,8.036847,27.536890,6.822562,15.666989,0.226836,0.564718,21459.004378,62602.313428
min,2.012001e+09,3.201200e+10,3.0,NaN,8.000000,3.0,1.000000,1.000000,8.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,6.0,1.000000,1.000000,1.000000,5.0,9.0,0.0,0.0,9.0,2.000000,0.0,30.000000,30.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,12.000000,0.000000,124.0,2.00000,NaN,570031.0,2012.000000,1.000000,2.000000,1.000000,0.000000,0.000000,34.543952,31.039179,156669.000000,549798.000000
25%,2.012044e+09,3.201204e+10,3.0,NaN,8.000000,3.0,1.000000,2.000000,9.000000,4.000000,12.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,6.0,9.000000,9.000000,5.000000,5.0,9.0,0.0,0.0,9.0,55.000000,0.0,160.000000,160.000000,0.000000,1.000000,1.000000,2.000000,9.000000,2.000000,44.000000,245.000000,0.000000,14.000000,0.000000,124.0,52.25000,NaN,570031.0,2012.000000,3.000000,10.000000,41.000000,10.000000,0.000000,34.820980,31.778582,183162.000000,631759.000000
50%,2.013001e+09,3.201300e+10,3.0,NaN,8.000000,3.0,1.000000,2.000000,9.000000,4.000000,34.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,6.0,9.000000,9.000000,6.000000,5.0,9.0,0.0,0.0,9.0,70.000000,0.0,262.500000,262.500000,469.000000,1.000000,5.000000,4.000000,9.000000,4.000000,77.000000,442.000000,0.000000,16.000000,366.000000,124.0,9999.00000,NaN,570031.0,2013.000000,7.000000,17.000000,67.000000,16.000000,30.000000,34.976898,32.083156,197727.000000,665590.000000
75%,2.014016e+09,3.201402e+10,3.0,NaN,8.000000,3.0,2.000000,4.000000,9.000000,4.000000,43.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.0,9.000000,9.000000,8.000000,5.0,9.0,0.0,0.0,9.0,248.750000,0.0,570.000000,570.000000,3000.000000,1.000000,5.000000,6.000000,9.000000,6.000000,99.000000,621.000000,39.000000,26.000000,607.000000,124.0,9999.00000,NaN,570031.0,2014.000000,9.000000,23.000000,81.000000,20.000000,30.000000,35.131314,32.482041,212552.000000,709779.000000
max,2.014098e+09,3.201410e+10,3.0,NaN,10.000000,3.0,3.000000,4.000000,9.000000,4.000000,61.000000,9.000000,3.000000,5.000000,1.000000,5.000000,5.000000,11.000000,6.0,9.000000,9.000000,9.000000,5.0,9.0,0.0,0.0,9.0,5066.000000,0.0,3040.000000,3040.000000,9100.000000,2.000000,5.000000,7.000000,9.000000,7.000000,99.000000,770.000000,99.000000,31.000000,6500.000000,124.0,9999.00000,NaN,570031.0,2014.000000,12.000000,29.000000,96.000000,23.000000,45.000000,35.571726,33.201772,253696.000000,789646.000000

In [36]:
m_all[(m_all['object_distance']==5) & ((m_all['accident_year'] == 2012) | (m_all['accident_year'] == 2013) | (m_all['accident_year'] == 2014))].shape

(33, 98)

In [34]:
m_all[(m_all['object_distance']==1462) & (m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].shape

(31, 98)

**Null Conclusion:** 
- *all* instances of `object_distance` == 1462
- *all* instances of `object_distance` == 5 during years 2012-2014.  Rest of the years `object_distance` == 5 is OK

**Specific values mistmatch investigations:**

In [83]:
temp = m_all[(m_all['object_distance'] != 1462) & \
             ((m_all['object_distance'] !=5) | \
                  ((m_all['accident_year'] != 2012) & (m_all['accident_year'] != 2013) & (m_all['accident_year'] != 2014)))]
calc_diff_counts_hebrew(temp, 'object_distance')

Shape of data: (720477, 98)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

**Specific values conclusion:** no issues

### didnt_cross and didnt_cross_hebrew

In [38]:
# didnt_cross                                  720541 non-null int64
# didnt_cross_hebrew                           720538 non-null object
m_all[(m_all['didnt_cross'].isnull() == False) & (m_all['didnt_cross_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
113180,2017035517,12017035517,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,4,התנגשות צד בצד,3,קלה,2017-03-08 20:30:00,2,מרכז ישוב,2,עירונית לא בצומת,8,כביש ישר / צומת,4,יום אחר,51,מרחב השרון,3,דו סיטרי אין קו הפרדה רצוף,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,6,לילה לא ידוע,6.0,תמרור זכות קדימה,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,638,קלנסווה,1,ישראל ללא יהודה ושומרון,5,לילה,4,רביעי,9,לא ידוע,4.0,המרכז,41,השרון,412.0,מזרח השרון,0.0,עירייה,26.0,יישובים לא יהודיים 49999-20000 תושבים,0.0,NaN,NaN,NaN,9999.0,NaN,NaN,NaN,NaN,2017,3,8,83,20:30-20:44,20,30,0101000020E610000046AB1DCE157D4140A783425BED24...,34.977228,32.288494,198047.0,688325.0
145608,2015079839,12015079839,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,1,פגיעה בהולך רגל,3,קלה,2015-03-02 00:00:00,1,עיגון מדויק,2,עירונית לא בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",1,חד סיטרי,0,NaN,1,"עד 50 קמ""ש",4,שוליים גרועים וכביש משובש,1,עד 5 מטר,3,אין ליקוי,6,לילה לא ידוע,NaN,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,0,NaN,3,חצה רגיל,2,לא במעבר חצייה לא ליד צומת,2,משמאל לימין,NaN,NaN,NaN,NaN,NaN,6600,חולון,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,5.0,תל אביב,51,תל אביב,513.0,אזור חולון,0.0,עירייה,14.0,יישובים יהודיים 199999-100000 תושבים,339.0,הס משה,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2015,3,2,1,00:00-00:14,0,0,0101000020E61000007F56425414644140B999F03A9802...,34.781870,32.020271,179528.0,658637.0
150298,2016005012,12016005012,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,2,התנגשות חזית בצד,3,קלה,2016-06-24 19:00:00,1,עיגון מדויק,1,עירונית בצומת,9,אחר,4,יום אחר,11,מרחב חוף (חיפה),0,NaN,3,מיפרדה בנויה ללא גדר בטיחות,1,"עד 50 קמ""ש",1,אין ליקויים,2,5 עד 7 מטר,4,לא נדרש תמרור,1,אור יום רגיל,1.0,אין בקרה,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,6500,חדרה,1,ישראל ללא יהודה ושומרון,1,יום,6,שישי,0,לא,3.0,חיפה,32,חדרה,324.0,אזור חדרה,0.0,עירייה,15.0,יישובים יהודיים 99999-50000 תושבים,450.0,אהרונסון,548.0,שועלי שמשון,NaN,NaN,NaN,NaN,9020004.0,2016,6,24,77,19:00-19:14,19,0,0101000020E6100000583BFAE85C73414043613DF4CB38...,34.901273,32.443724,190941.0,705557.0

In [39]:
m_all[m_all['didnt_cross'] == 0]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
113180,2017035517,12017035517,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,4,התנגשות צד בצד,3,קלה,2017-03-08 20:30:00,2,מרכז ישוב,2,עירונית לא בצומת,8,כביש ישר / צומת,4,יום אחר,51,מרחב השרון,3,דו סיטרי אין קו הפרדה רצוף,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,6,לילה לא ידוע,6.0,תמרור זכות קדימה,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,638,קלנסווה,1,ישראל ללא יהודה ושומרון,5,לילה,4,רביעי,9,לא ידוע,4.0,המרכז,41,השרון,412.0,מזרח השרון,0.0,עירייה,26.0,יישובים לא יהודיים 49999-20000 תושבים,0.0,NaN,NaN,NaN,9999.0,NaN,NaN,NaN,NaN,2017,3,8,83,20:30-20:44,20,30,0101000020E610000046AB1DCE157D4140A783425BED24...,34.977228,32.288494,198047.0,688325.0
145608,2015079839,12015079839,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,1,פגיעה בהולך רגל,3,קלה,2015-03-02 00:00:00,1,עיגון מדויק,2,עירונית לא בצומת,8,כביש ישר / צומת,4,יום אחר,20,"מחוז ת""א",1,חד סיטרי,0,NaN,1,"עד 50 קמ""ש",4,שוליים גרועים וכביש משובש,1,עד 5 מטר,3,אין ליקוי,6,לילה לא ידוע,NaN,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,0,NaN,3,חצה רגיל,2,לא במעבר חצייה לא ליד צומת,2,משמאל לימין,NaN,NaN,NaN,NaN,NaN,6600,חולון,1,ישראל ללא יהודה ושומרון,5,לילה,2,שני,9,לא ידוע,5.0,תל אביב,51,תל אביב,513.0,אזור חולון,0.0,עירייה,14.0,יישובים יהודיים 199999-100000 תושבים,339.0,הס משה,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2015,3,2,1,00:00-00:14,0,0,0101000020E61000007F56425414644140B999F03A9802...,34.781870,32.020271,179528.0,658637.0
150298,2016005012,12016005012,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,2,התנגשות חזית בצד,3,קלה,2016-06-24 19:00:00,1,עיגון מדויק,1,עירונית בצומת,9,אחר,4,יום אחר,11,מרחב חוף (חיפה),0,NaN,3,מיפרדה בנויה ללא גדר בטיחות,1,"עד 50 קמ""ש",1,אין ליקויים,2,5 עד 7 מטר,4,לא נדרש תמרור,1,אור יום רגיל,1.0,אין בקרה,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,6500,חדרה,1,ישראל ללא יהודה ושומרון,1,יום,6,שישי,0,לא,3.0,חיפה,32,חדרה,324.0,אזור חדרה,0.0,עירייה,15.0,יישובים יהודיים 99999-50000 תושבים,450.0,אהרונסון,548.0,שועלי שמשון,NaN,NaN,NaN,NaN,9020004.0,2016,6,24,77,19:00-19:14,19,0,0101000020E6100000583BFAE85C73414043613DF4CB38...,34.901273,32.443724,190941.0,705557.0

**Null Conclusion**: all instances of `didnt_cross` == 0 are missing translation

**Specific values mistmatch investigations:**

In [84]:
calc_diff_counts_hebrew(m_all[m_all['didnt_cross'] != 0], 'didnt_cross')

Shape of data: (720538, 98)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

**Specific values conclusion:** no issues

### cross_mode and cross_mode_hebrew

In [42]:
# cross_mode                                   720541 non-null int64
# cross_mode_hebrew                            33365 non-null object
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)].shape

(687176, 98)

In [43]:
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,6.871760e+05,6.871760e+05,687176.000000,51999.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,68594.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,152701.000000,145117.000000,139356.000000,139356.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,572530.000000,687176.000000,572530.000000,571363.000000,572530.000000,521589.000000,61646.000000,465982.000000,3.397800e+04,6.057700e+04,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,687176.000000,677314.000000,677314.000000,677314.000000,677314.000000
mean,2.012661e+09,2.819547e+10,2.618281,2.625262,4.860525,2.973969,2.354583,2.314359,8.628226,3.894787,30.910289,7.667276,0.205259,0.377101,0.155294,0.464478,4.659196,8.398778,3.840788,7.613163,7.617239,8.850182,8.897560,8.980139,0.000013,0.001185,8.999584,379.270175,215.138392,703.203328,699.333570,3777.505582,1.023844,2.073082,3.648733,8.328005,4.166138,53.219538,443.124294,17.292653,22.329270,779.744421,845.860526,8671.712869,1.712511e+04,1.493881e+07,2012.620080,6.414897,15.650742,54.738482,13.132497,18.127387,34.964664,32.180841,196779.313010,676412.604043
std,3.197496e+06,7.859600e+09,0.785958,0.780422,4.062755,0.180685,1.642001,0.870384,0.585640,0.471854,17.876349,2.968665,0.735345,4.212723,0.380841,1.115514,0.775514,3.595113,2.258240,3.016213,3.009644,0.880553,9.820855,0.279001,0.010857,0.085599,0.056811,1335.008210,1074.090229,876.762844,879.852603,3247.266965,0.152563,1.772238,1.878996,2.285169,2.024659,28.340537,215.871840,37.536515,22.566293,1398.510421,994.613874,3383.783087,1.096744e+06,2.181731e+07,3.192626,3.418740,8.784259,20.672076,5.170756,16.576701,0.218304,0.491119,20618.554326,54441.737938
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-1.000000,0.000000,-478.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,0.000000,0.000000,-40.000000,0.000000e+00,0.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.260947,29.493021,129666.000000,378409.000000
25%,2.010019e+09,3.200805e+10,3.000000,3.000000,3.000000,3.000000,1.000000,2.000000,8.000000,4.000000,14.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,100.000000,100.000000,70.000000,1.000000,1.000000,2.000000,9.000000,3.000000,31.000000,311.000000,0.000000,13.000000,0.000000,246.250000,9999.000000,4.330000e+02,7.210312e+06,2010.000000,3.000000,8.000000,39.000000,9.000000,0.000000,34.798275,31.913654,180918.250000,646786.750000
50%,2.012058e+09,3.201104e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,20.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,40.000000,0.000000,318.000000,317.000000,3000.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,432.000000,0.000000,14.000000,303.000000,508.000000,9999.000000,1.219000e+03,9.100033e+06,2012.000000,6.000000,16.000000,57.000000,14.000000,15.000000,34.897322,32.083403,190454.500000,665618.500000
75%,2.015090e+09,3.201502e+10,3.000000,3.000000,5.000000,3.000000,3.000000,2.000000,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,89.000000,0.000000,1002.000000,1002.000000,6800.000000,1.000000,5.000000,5.000000,9.000000,5.000000,62.000000,512.000000,0.000000,17.000000,905.000000,1011.000000,9999.000000,4.021000e+03,1.497004e+07,2015.000000,9.000000,23.000000,70.000000,17.000000,30.000000,35.117590,32.609303,211242.000000,723882.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,15.000000,4.000000,61.000000,9.000000,5.000000,3383.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,9.000000,9.000000,9999.000000,9999.000000,9999.000000,9999.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,999.000000,99.000000,9999.000000,9998.000000,11111.000000,1.000000e+08,1.000000e+08,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.000000,799843.000000

In [44]:
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)]['cross_mode'].value_counts()

0    687175
9         1
Name: cross_mode, dtype: int64

In [46]:
m_all[m_all['cross_mode']==0].shape

(687175, 98)

In [47]:
m_all[m_all['cross_mode']==0]['accident_year'].value_counts()

2008    77228
2009    75924
2010    70608
2011    64368
2012    60632
2015    58648
2013    58504
2016    58240
2017    55642
2014    55382
2018    51999
Name: accident_year, dtype: int64

In [48]:
m_all[m_all['cross_mode']==9].shape

(632, 98)

In [50]:
m_all[(m_all['cross_mode']==9) & (m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
28780,2008055825,12008055825,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,8,התנגשות עם עצם דומם,3,קלה,2008-09-26 16:30:00,1,עיגון מדויק,2,עירונית לא בצומת,9,אחר,4,יום אחר,61,מחוז ירושלים,3,דו סיטרי אין קו הפרדה רצוף,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,1,אור יום רגיל,NaN,NaN,1,בהיר,1,יבש,8,אחר,3,על הכביש,9,לא ידוע,9,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,3000,ירושלים,1,ישראל ללא יהודה ושומרון,1,יום,6,שישי,9,לא ידוע,1.0,ירושלים,11,ירושלים,111.0,הרי יהודה,0.0,עירייה,11.0,ירושלים,4457.0,עלית הנוער,NaN,NaN,99.0,NaN,NaN,NaN,NaN,2008,9,26,67,NaN,16,30,0101000020E61000003F9FF4C597994140E592A403E6CF...,35.199944,31.812103,219024.0,635476.0

In [51]:
m_all[m_all['cross_mode']==9]['accident_year'].value_counts()

2014    139
2015    127
2016    106
2017    105
2018    103
2013     51
2008      1
Name: accident_year, dtype: int64

**Null Conclusions**:
- All `cross_mode` == 0 that's spread over all years, translation is missing
- `cross_mode` == 9 from year 2008 is problematic (other years are OK)

**Specific values mistmatch investigations:**

In [85]:
temp = m_all[(m_all['cross_mode'] !=0) & ((m_all['cross_mode'] != 9) | (m_all['accident_year'] != 2008))]
calc_diff_counts_hebrew(temp, 'cross_mode')

Shape of data: (33365, 98)

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

**Specific values conclusion:** no issues

### cross_location and cross_location_hebrew

In [54]:
# cross_location                               720541 non-null int64
# cross_location_hebrew                        28925 non-null object
m_all[(m_all['cross_location'].isnull() == False) & (m_all['cross_location_hebrew'].isnull() == True)].shape

(691616, 98)

In [55]:
m_all[(m_all['cross_location'].isnull() == False) & (m_all['cross_location_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,6.916160e+05,6.916160e+05,691616.000000,52719.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,68915.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.0,691616.000000,152884.000000,145283.000000,139525.000000,139525.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,576865.000000,691616.000000,576865.000000,575664.000000,576865.000000,525735.000000,61874.000000,469999.000000,3.400300e+04,6.080400e+04,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,691616.000000,681738.000000,681738.000000,681738.000000,681738.000000
mean,2.012678e+09,2.819009e+10,2.617742,2.622755,4.837442,2.973368,2.352876,2.312512,8.629557,3.894660,30.909571,7.665365,0.204871,0.376525,0.155803,0.464908,4.658655,8.396493,3.847043,7.610323,7.614681,8.850880,8.897816,8.971033,0.039081,0.0,8.999138,379.354936,215.071633,703.329095,699.454492,3782.818603,1.023895,2.072451,3.649211,8.331259,4.165794,53.164069,443.062564,17.276575,22.299198,780.075618,845.797088,8658.299469,1.711379e+04,1.493393e+07,2012.637150,6.414188,15.649392,54.740362,13.133030,18.123597,34.964544,32.180374,196767.908242,676360.761430
std,3.198464e+06,7.863837e+09,0.786382,0.782425,4.062300,0.182743,1.638515,0.868647,0.585305,0.472137,17.871505,2.969403,0.734868,4.199551,0.381546,1.115532,0.775943,3.597173,2.261135,3.018669,3.011796,0.878548,9.789427,0.345917,0.512722,0.0,0.081798,1335.176471,1073.988271,876.906347,880.000005,3246.673380,0.152721,1.771908,1.878879,2.280132,2.022418,28.299294,215.588135,37.516632,22.511849,1400.317650,994.451705,3398.225570,1.096340e+06,2.181580e+07,3.193578,3.418969,8.784771,20.664240,5.168806,16.576135,0.218301,0.491838,20618.443433,54521.409096
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.0,1.000000,0.000000,-1.000000,0.000000,-478.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,0.000000,0.000000,-40.000000,0.000000e+00,0.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.260947,29.493021,129666.000000,378409.000000
25%,2.010020e+09,3.200805e+10,3.000000,3.000000,3.000000,3.000000,1.000000,2.000000,8.000000,4.000000,14.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.0,9.000000,4.000000,0.000000,100.000000,100.000000,70.000000,1.000000,1.000000,2.000000,9.000000,3.000000,31.000000,311.000000,0.000000,13.000000,0.000000,246.000000,9999.000000,4.330000e+02,7.210312e+06,2010.000000,3.000000,8.000000,39.000000,9.000000,0.000000,34.798275,31.912447,180906.000000,646647.000000
50%,2.012060e+09,3.201104e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,20.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.0,9.000000,40.000000,0.000000,319.000000,317.000000,3048.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,432.000000,0.000000,14.000000,303.000000,507.000000,9999.000000,1.219000e+03,9.100032e+06,2012.000000,6.000000,16.000000,57.000000,14.000000,15.000000,34.897127,32.083270,190453.000000,665605.000000
75%,2.015092e+09,3.201502e+10,3.000000,3.000000,5.000000,3.000000,3.000000,2.000000,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.0,9.000000,89.000000,0.000000,1002.000000,1002.000000,6800.000000,1.000000,5.000000,5.000000,9.000000,5.000000,62.000000,512.000000,0.000000,17.000000,905.000000,1011.000000,9999.000000,4.021000e+03,1.497001e+07,2015.000000,9.000000,23.000000,70.000000,17.000000,30.000000,35.116611,32.609303,211174.000000,723882.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,15.000000,4.000000,61.000000,9.000000,5.000000,3383.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,0.0,9.000000,9999.000000,9999.000000,9999.000000,9999.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,999.000000,99.000000,9999.000000,9998.000000,11111.000000,1.000000e+08,1.000000e+08,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.000000,799843.000000

In [56]:
m_all[m_all['cross_location']==0].shape

(691616, 98)

**Null Conclusion:** all `cross_location` == 0 spread over numerous years has no translation

**Specific values mistmatch investigations:**

In [86]:
calc_diff_counts_hebrew(m_all[m_all['cross_location'] != 0], 'cross_location')

Shape of data: (28925, 98)

0    0
1    0
2    0
3    0
4    0
dtype: int64

**Specific values conclusion:** no issues

### region and region_hebrew

In [73]:
# region                                       605597 non-null float64
# region_hebrew                                565389 non-null object
m_all[(m_all['region'].isnull() == False) & (m_all['region_hebrew'].isnull() == True)].shape

(40208, 98)

In [74]:
m_all[(m_all['region'].isnull() == False) & (m_all['region_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.020800e+04,4.020800e+04,40208.0,0.0,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,17413.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,39986.000000,39190.000000,38540.000000,38540.000000,40208.0,40208.000000,40208.000000,40208.000000,40208.000000,40208.0,40208.0,40208.0,40208.0,40208.0,0.0,0.0,0.0,1.301100e+04,0.0,40208.000000,40208.000000,40208.000000,40208.000000,40208.000000,40208.00000,39670.000000,39670.000000,39670.000000,39670.000000
mean,2.012311e+09,1.201231e+10,1.0,NaN,4.080233,2.781785,1.270021,3.664395,8.211973,3.868434,29.579163,1.870474,1.139276,3.582048,0.800960,2.817623,3.241718,2.805884,3.640498,1.754576,1.745026,8.591101,8.305710,8.970429,0.057725,0.060859,8.849383,519.196344,370.846491,700.440737,698.130929,0.0,1.113261,2.501990,3.922727,6.622239,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,2.350538e+04,NaN,2012.270096,6.468389,15.613361,54.972841,13.176607,18.99622,35.052093,32.256283,205017.214772,684768.087572
std,2.925865e+06,2.925865e+06,0.0,NaN,3.137877,0.509940,1.067747,0.472207,1.002749,0.532432,17.346469,2.596545,1.325334,1.683188,0.471067,1.326831,0.719973,2.717743,2.241423,2.226176,2.208351,1.314634,2.111477,0.364566,0.470774,0.474224,1.053496,1499.723759,1429.349904,928.988064,930.725168,0.0,0.316916,1.937028,1.964472,3.758388,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1.256351e+06,NaN,2.921787,3.457122,8.781739,23.816910,5.943000,16.64212,0.239200,0.530107,22569.483930,58768.532435
min,2.008000e+09,1.200800e+10,1.0,NaN,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-312.000000,0.0,1.000000,1.000000,1.000000,0.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,0.000000e+00,NaN,2008.000000,1.000000,1.000000,1.000000,0.000000,0.00000,34.293560,29.550787,132646.000000,384801.000000
25%,2.010007e+09,1.201001e+10,1.0,NaN,2.000000,3.000000,1.000000,3.000000,8.000000,4.000000,12.000000,0.000000,0.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,97.000000,92.750000,0.0,1.000000,1.000000,2.000000,1.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,7.490000e+02,NaN,2010.000000,3.000000,8.000000,37.000000,9.000000,0.00000,34.869231,31.916663,187755.250000,647121.000000
50%,2.012042e+09,1.201204e+10,1.0,NaN,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,20.000000,1.000000,0.000000,4.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,65.000000,0.000000,264.000000,264.000000,0.0,1.000000,1.000000,4.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,1.593000e+03,NaN,2012.000000,7.000000,16.000000,58.000000,14.000000,15.00000,35.022257,32.186025,202298.500000,676955.000000
75%,2.015033e+09,1.201503e+10,1.0,NaN,5.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,3.000000,2.000000,5.000000,1.000000,4.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,412.000000,0.000000,928.000000,928.000000,0.0,1.000000,5.000000,6.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,4.065000e+03,NaN,2015.000000,9.000000,23.000000,73.000000,18.000000,30.00000,35.216171,32.730269,220550.250000,737296.000000
max,2.017100e+09,1.201710e+10,1.0,NaN,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,7.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9998.000000,9998.000000,9999.000000,9999.000000,0.0,2.000000,5.000000,7.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,1.000000e+08,NaN,2017.000000,12.000000,31.000000,96.000000,23.000000,45.00000,35.849314,33.293023,279767.000000,799843.000000

In [75]:
m_all[(m_all['region'] == 9].shape

(44059, 98)

In [101]:
m_all[(m_all['region'] == 9) & (m_all['region_hebrew'].isnull())]['accident_year'].value_counts()

2009    4765
2008    4602
2010    4348
2011    4072
2017    3932
2013    3829
2012    3751
2015    3716
2016    3654
2014    3539
Name: accident_year, dtype: int64

In [102]:
m_all[(m_all['region'] == 9) & (m_all['region_hebrew'].isnull() == False)]['accident_year'].value_counts()

2018    3851
Name: accident_year, dtype: int64

In [107]:
m_all[(m_all['region'] == 9) & (m_all['accident_year'] != 2018)].shape

(40208, 98)

**Null Conclusion:** all `region` == 9 spread over numerous years missing translation, 2018 it was already fixed

**Specific values mistmatch investigations:**

In [109]:
calc_diff_counts_hebrew(m_all[(m_all['region'] != 9) | (m_all['accident_year'] == 2018)], 'region')

Shape of data: (565389, 98)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

**Specific values conclusion:** no issues

### district and district_hebrew

In [60]:
# district                                     720541 non-null int64
# district_hebrew                              561538 non-null object
m_all[(m_all['district'].isnull() == False) & (m_all['district_hebrew'].isnull() == True)].shape

(159003, 98)

In [61]:
m_all[(m_all['district'].isnull() == False) & (m_all['district_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.590030e+05,1.590030e+05,159003.000000,12902.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,20112.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,154045.000000,146382.000000,140626.000000,140626.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,44059.0,159003.0,44059.0,44102.000000,44059.0,232.00000,129.0,119.0,3.438200e+04,0.0,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,159003.000000,149644.000000,149644.000000,149644.00000,149644.000000
mean,2.012632e+09,2.646519e+10,2.445256,2.412804,4.592222,2.939001,2.663824,3.773539,8.579813,3.891040,31.333660,6.970346,0.322491,1.040785,0.229845,0.801450,4.500783,7.676220,3.669799,6.938485,6.933687,8.783834,8.800230,8.989315,0.023823,0.020981,8.952932,379.916940,215.696117,704.299888,700.395318,0.008622,1.068753,2.218946,3.684641,8.051798,9.0,99.0,999.0,99.877511,99.0,6075.75000,0.0,9999.0,1.695550e+04,NaN,2012.591272,6.406552,15.670409,54.247473,13.000912,18.657384,34.995371,32.215003,199671.93832,680196.357529
std,3.239787e+06,8.953954e+09,0.895406,0.910855,3.518502,0.286106,3.069516,0.426166,0.692570,0.479733,17.632231,3.499956,0.872548,8.681142,0.441579,1.454945,0.879991,3.890408,2.256578,3.477946,3.479413,0.951210,12.172188,0.217429,0.321059,0.291470,0.593270,1335.941754,1075.666638,877.683953,880.802981,3.438229,0.253035,1.841189,1.900428,2.647694,0.0,0.0,0.0,28.089286,0.0,4891.57897,0.0,0.0,1.090282e+06,NaN,3.234707,3.482407,8.773772,21.779547,5.444766,16.524326,0.225404,0.510802,21277.76152,56625.687929
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,-1.000000,0.000000,-478.000000,0.000000,1.000000,1.000000,1.000000,0.000000,9.0,99.0,999.0,99.000000,99.0,0.00000,0.0,9999.0,0.000000e+00,NaN,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.260947,29.514166,129666.00000,380748.000000
25%,2.010013e+09,1.201709e+10,1.000000,1.000000,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,12.000000,3.000000,0.000000,0.000000,0.000000,0.000000,4.000000,6.000000,2.000000,2.000000,2.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,100.000000,100.000000,0.000000,1.000000,1.000000,2.000000,9.000000,9.0,99.0,999.0,99.000000,99.0,0.00000,0.0,9999.0,4.330000e+02,NaN,2010.000000,3.000000,8.000000,37.000000,9.000000,0.000000,34.827124,31.902191,183755.00000,645512.000000
50%,2.012047e+09,3.201005e+10,3.000000,3.000000,3.000000,3.000000,1.000000,4.000000,9.000000,4.000000,34.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,40.000000,0.000000,320.000000,319.500000,0.000000,1.000000,1.000000,4.000000,9.000000,9.0,99.0,999.0,99.000000,99.0,9998.00000,0.0,9999.0,1.219000e+03,NaN,2012.000000,6.000000,16.000000,57.000000,14.000000,15.000000,34.942378,32.124671,194711.00000,670189.000000
75%,2.015096e+09,3.201407e+10,3.000000,3.000000,4.000000,3.000000,3.000000,4.000000,9.000000,4.000000,51.000000,9.000000,0.000000,1.000000,0.000000,1.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,89.000000,0.000000,1010.000000,1010.000000,0.000000,1.000000,5.000000,5.000000,9.000000,9.0,99.0,999.0,99.000000,99.0,9998.00000,0.0,9999.0,4.021000e+03,NaN,2015.000000,9.000000,23.000000,71.000000,17.000000,30.000000,35.143032,32.662456,213702.00000,729789.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,15.000000,4.000000,61.000000,9.000000,5.000000,3383.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,9.000000,9.000000,9999.000000,9999.000000,9999.000000,9999.000000,1371.000000,2.000000,5.000000,7.000000,9.000000,9.0,99.0,999.0,999.000000,99.0,9999.00000,0.0,9999.0,1.000000e+08,NaN,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.00000,799843.000000

In [62]:
m_all[m_all['district']==99].shape

(159003, 98)

**Null Conclusion:** all `district` == 99 spread over numerous years missing translation

**Specific values mistmatch investigations:**

In [110]:
calc_diff_counts_hebrew(m_all[m_all['district'] != 99], 'district')

Shape of data: (561538, 98)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
dtype: int64

**Specific values conclusion:** no issues

### natural_area and natural_area_hebrew

In [63]:
# natural_area                                 605597 non-null float64
# natural_area_hebrew                          557164 non-null object
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].shape

(48433, 98)

In [64]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.843300e+04,4.843300e+04,48433.000000,3960.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,19785.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,43826.000000,42945.000000,42359.000000,42359.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48290.000000,48433.000000,4220.000000,468.000000,3890.000000,1.424400e+04,4.510000e+02,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,47877.000000,47877.000000,47877.000000,47877.000000
mean,2.012859e+09,1.296964e+10,1.095679,1.034343,4.100820,2.792641,1.328805,3.505213,8.255962,3.872050,31.096587,2.221006,1.066442,3.312452,0.776557,2.669440,3.316520,3.119774,3.687086,2.091363,2.077839,8.602461,8.340491,8.965788,0.088782,0.085314,8.791526,534.724821,374.257958,697.441772,695.306074,461.034728,1.137840,2.463300,3.891417,6.798092,8.656866,95.171020,960.284703,92.451605,91.742118,617.999526,197.982906,6776.612853,2.175243e+04,4.450670e+06,2012.818161,6.446700,15.618008,55.040365,13.192451,19.058390,35.047174,32.239979,204556.401445,682959.432400
std,3.139614e+06,4.268719e+09,0.426857,0.259855,3.212625,0.496321,1.044801,0.685985,0.993598,0.524823,17.429198,2.929494,1.315646,1.844188,0.486986,1.418832,0.793434,3.074494,2.247699,2.657225,2.637163,1.316585,2.063355,0.383697,0.587915,0.547570,1.236340,1527.012971,1437.331930,926.635621,928.239265,1642.570151,0.344735,1.926663,1.958818,3.669710,1.175246,13.143063,133.018992,24.103650,23.151373,1854.142950,134.283696,4667.171040,1.200753e+06,1.284585e+07,3.135062,3.451869,8.773722,23.551294,5.878195,16.661091,0.233635,0.517817,22045.546899,57406.818193
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-312.000000,0.000000,1.000000,1.000000,1.000000,0.000000,4.000000,43.000000,432.000000,0.000000,9.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.293560,29.550787,132646.000000,384801.000000
25%,2.010042e+09,1.201004e+10,1.000000,1.000000,2.000000,3.000000,1.000000,3.000000,8.000000,4.000000,12.000000,0.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,96.000000,91.000000,0.000000,1.000000,1.000000,2.000000,1.000000,9.000000,99.000000,999.000000,99.000000,99.000000,0.000000,116.000000,26.000000,7.570000e+02,2.000100e+04,2010.000000,3.000000,8.000000,37.000000,9.000000,0.000000,34.873092,31.922466,188144.000000,647759.000000
50%,2.013023e+09,1.201303e+10,1.000000,1.000000,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,34.000000,1.000000,0.000000,4.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,65.000000,0.000000,262.000000,260.000000,0.000000,1.000000,1.000000,4.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,143.000000,158.000000,9999.000000,1.621000e+03,1.300920e+05,2013.000000,6.000000,16.000000,58.000000,14.000000,15.000000,35.015849,32.140940,201665.000000,672011.000000
75%,2.015093e+09,1.201606e+10,1.000000,1.000000,5.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,3.000000,2.000000,5.000000,1.000000,3.000000,3.000000,5.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,424.000000,0.000000,920.000000,920.000000,0.000000,1.000000,5.000000,6.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,306.000000,225.000000,9999.000000,4.072000e+03,7.635001e+06,2015.000000,9.000000,23.000000,73.000000,18.000000,30.000000,35.194220,32.711050,218490.000000,735167.000000
max,2.018100e+09,3.201710e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9998.000000,9998.000000,9999.000000,9999.000000,8500.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,767.000000,9999.000000,1.000000e+08,1.000000e+08,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.000000,799843.000000

In [65]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)]['natural_area'].value_counts()

999.0    44064
432.0     2624
777.0     1744
877.0        1
Name: natural_area, dtype: int64

In [69]:
for area in [999, 432, 777, 877]:
    print(f'{area} shape: {m_all[m_all["natural_area"]==area].shape}')

999 shape: (44064, 98)
432 shape: (8177, 98)
777 shape: (1744, 98)
877 shape: (1, 98)

In [70]:
m_all[(m_all['natural_area']==432) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,2.624000e+03,2.624000e+03,2624.000000,0.0,2624.000000,2624.000000,2624.000000,2624.00000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,148.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,0.0,0.0,0.0,0.0,2624.000000,2624.0,2624.000000,2624.000000,2624.000000,2624.0,2624.0,2624.0,2589.000000,2624.000000,2546.000000,117.000000,2496.000000,0.0,1.170000e+02,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000,2624.000000
mean,2.013528e+09,2.963548e+10,2.762195,NaN,4.568216,2.988186,2.205793,1.95122,8.919588,3.906631,51.727134,8.194360,0.127287,0.124619,0.111280,0.294207,4.777058,8.937881,4.689189,8.108994,8.113186,8.830030,8.928735,8.963034,0.135671,0.105564,8.820122,NaN,NaN,NaN,NaN,6077.309451,1.0,2.003049,3.512576,8.755335,4.0,43.0,432.0,15.840865,17.437500,542.301650,348.854701,7835.479968,NaN,7.366957e+06,2013.491235,6.392530,15.511433,54.046113,12.950457,18.664253,34.880856,31.948366,188855.532774,650631.581555
std,5.075693e+05,6.474725e+09,0.647471,NaN,4.068504,0.127490,0.717111,0.21545,0.317271,0.443586,2.936916,2.402096,0.601652,0.394515,0.350103,0.930459,0.664605,3.220270,2.166069,2.506783,2.499515,1.009334,0.706614,0.325211,0.749050,0.689709,1.158946,NaN,NaN,NaN,NaN,2811.948757,0.0,1.734138,1.846118,1.429087,0.0,0.0,0.0,33.172436,6.562168,1586.774608,176.082331,4113.678889,NaN,4.031807e+06,0.500018,3.473207,8.843444,20.299224,5.072316,16.522299,0.025463,0.024513,2408.853736,2716.753803
min,2.013000e+09,1.201300e+10,1.000000,NaN,1.000000,1.000000,1.000000,1.00000,5.000000,1.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,88.000000,1.0,1.000000,1.000000,0.000000,4.0,43.0,432.0,0.000000,15.000000,0.000000,102.000000,1.000000,NaN,1.000300e+04,2013.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.823099,31.830446,183419.000000,637555.000000
25%,2.013029e+09,3.201302e+10,3.000000,NaN,2.000000,3.000000,2.000000,2.00000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,7000.000000,1.0,1.000000,2.000000,9.000000,4.0,43.0,432.0,0.000000,15.000000,0.000000,218.000000,9999.000000,NaN,7.830049e+06,2013.000000,3.000000,8.000000,37.000000,9.000000,0.000000,34.866422,31.929593,187484.000000,648554.000000
50%,2.013060e+09,3.201305e+10,3.000000,NaN,3.000000,3.000000,2.000000,2.00000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,7000.000000,1.0,1.000000,3.000000,9.000000,4.0,43.0,432.0,0.000000,15.000000,176.000000,311.000000,9999.000000,NaN,8.390002e+06,2013.000000,6.000000,16.000000,55.000000,13.000000,15.000000,34.884018,31.948378,189155.500000,650631.000000
75%,2.014040e+09,3.201404e+10,3.000000,NaN,5.000000,3.000000,3.000000,2.00000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,8500.000000,1.0,5.000000,5.000000,9.000000,4.0,43.0,432.0,0.000000,15.000000,417.000000,436.000000,9999.000000,NaN,9.750042e+06,2014.000000,9.250000,23.000000,69.000000,17.000000,30.000000,34.892009,31.953937,189912.000000,651246.000000
max,2.014100e+09,3.201410e+10,3.000000,NaN,20.000000,3.000000,3.000000,2.00000,9.000000,4.000000,61.000000,9.000000,5.000000,5.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,8500.000000,1.0,5.000000,7.000000,9.000000,4.0,43.0,432.0,99.000000,52.000000,9998.000000,767.000000,9999.000000,NaN,1.284027e+07,2014.000000,12.000000,31.000000,96.000000,23.000000,45.000000,34.960535,32.019690,196407.000000,658553.000000

In [72]:
m_all[(m_all['natural_area']==432) & ((m_all['accident_year']==2013) | (m_all['accident_year']==2014))].shape

(2624, 98)

In [73]:
m_all[m_all['natural_area']==432]['accident_year'].value_counts()

2017    1426
2016    1416
2015    1368
2018    1343
2013    1335
2014    1289
Name: accident_year, dtype: int64

In [74]:
m_all[(m_all['natural_area']==999) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.406400e+04,4.406400e+04,44064.000000,3851.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,19198.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,43826.000000,42945.000000,42359.000000,42359.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.0,44064.000000,44064.000000,5.000000,0.0,5.000000,1.424400e+04,0.0,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,44064.000000,43509.000000,43509.000000,43509.000000,43509.000000
mean,2.012813e+09,1.201508e+10,1.000227,1.032719,4.076026,2.780297,1.255015,3.665441,8.220293,3.868509,29.429353,1.854802,1.139388,3.586034,0.811683,2.826752,3.236792,2.797817,3.639754,1.752269,1.734454,8.594590,8.308347,8.970974,0.060957,0.061479,8.848312,534.724821,374.257958,697.441772,695.306074,0.433801,1.111928,2.500726,3.922544,6.636438,8.999773,98.997163,999.0,98.997050,98.990922,113.000000,NaN,2014.800000,2.175243e+04,NaN,2012.771378,6.453454,15.624909,55.092683,13.205065,19.086329,35.051850,32.270042,204995.838355,686293.850468
std,3.231181e+06,2.131036e+08,0.021304,0.253740,3.129690,0.510028,1.038262,0.472082,0.997769,0.532027,17.330309,2.570624,1.326881,1.685681,0.463431,1.323109,0.713399,2.713108,2.238042,2.223584,2.192203,1.309387,2.107313,0.360167,0.493341,0.474013,1.057094,1527.012971,1437.331930,926.635621,928.239265,40.721862,0.315282,1.936701,1.966025,3.747287,0.021304,0.266295,0.0,0.276947,0.852145,0.707107,NaN,4463.347533,1.200753e+06,NaN,3.226492,3.452166,8.767660,23.780277,5.935000,16.660091,0.239075,0.532463,22556.869194,59029.482367
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-312.000000,0.000000,1.000000,1.000000,1.000000,0.000000,7.000000,74.000000,999.0,73.000000,19.000000,112.000000,NaN,1.000000,0.000000e+00,NaN,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.293560,29.550787,132646.000000,384801.000000
25%,2.010027e+09,1.201003e+10,1.000000,1.000000,2.000000,3.000000,1.000000,3.000000,8.000000,4.000000,12.000000,0.000000,0.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,96.000000,91.000000,0.000000,1.000000,1.000000,2.000000,1.000000,9.000000,99.000000,999.0,99.000000,99.000000,113.000000,NaN,4.000000,7.570000e+02,NaN,2010.000000,3.000000,8.000000,37.000000,9.000000,0.000000,34.872716,31.920773,188143.000000,647598.000000
50%,2.013005e+09,1.201300e+10,1.000000,1.000000,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,20.000000,1.000000,0.000000,4.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,65.000000,0.000000,262.000000,260.000000,0.000000,1.000000,1.000000,4.000000,9.000000,9.000000,99.000000,999.0,99.000000,99.000000,113.000000,NaN,19.000000,1.621000e+03,NaN,2013.000000,6.000000,16.000000,59.000000,14.000000,15.000000,35.025246,32.207578,202574.000000,679355.000000
75%,2.016012e+09,1.201601e+10,1.000000,1.000000,5.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,3.000000,2.000000,5.000000,1.000000,4.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,424.000000,0.000000,920.000000,920.000000,0.000000,1.000000,5.000000,6.000000,9.000000,9.000000,99.000000,999.0,99.000000,99.000000,113.000000,NaN,51.000000,4.072000e+03,NaN,2016.000000,9.000000,23.000000,73.000000,18.000000,30.000000,35.208478,32.753058,219832.000000,739829.000000
max,2.018100e+09,3.201710e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9998.000000,9998.000000,9999.000000,9999.000000,3823.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.0,99.000000,99.000000,114.000000,NaN,9999.000000,1.000000e+08,NaN,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.000000,799843.000000

In [75]:
m_all[(m_all['natural_area']==777) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.744000e+03,1.744000e+03,1744.0,109.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.00000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,439.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,0.0,0.0,0.0,0.0,1744.000000,1744.0,1744.000000,1744.000000,1744.000000,1744.0,1744.0,1744.0,1637.000000,1744.000000,1669.000000,351.000000,1388.000000,0.0,3.340000e+02,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000,1744.000000
mean,2.013027e+09,1.201303e+10,1.0,1.091743,4.024656,2.810206,1.869266,1.795872,8.15883,3.909404,42.191514,2.485665,0.637041,1.197821,0.889908,2.268349,3.133601,2.501720,5.419134,1.605505,1.673739,8.458716,8.267202,8.838876,0.721330,0.657110,7.313647,NaN,NaN,NaN,NaN,3645.653096,2.0,2.211009,3.674885,7.936353,7.0,77.0,777.0,37.428222,20.438647,734.986818,147.692308,4887.314841,NaN,3.429097e+06,2012.985092,6.358945,15.610092,55.206422,13.235665,18.956422,35.180762,31.928723,217216.733372,648413.036124
std,2.967755e+06,2.967755e+06,0.0,0.420346,3.729212,0.427254,0.827730,0.403179,1.18680,0.445340,0.981771,2.355843,1.181529,0.875743,0.515320,1.048019,0.745948,2.645209,1.910604,2.022051,2.091065,1.785874,2.175528,0.797200,1.477808,1.262221,3.151868,NaN,NaN,NaN,NaN,134.165355,0.0,1.838323,1.867170,2.899931,0.0,0.0,0.0,43.981623,8.876905,2197.888259,60.320543,4989.857229,NaN,1.460470e+07,2.963307,3.412483,8.824250,22.238184,5.552139,16.892911,0.107652,0.198893,10179.221428,22055.224908
min,2.008000e+09,1.200800e+10,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,3.00000,1.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,3019.000000,2.0,1.000000,1.000000,0.000000,7.0,77.0,777.0,0.000000,15.000000,0.000000,0.000000,1.000000,NaN,0.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.905200,31.375279,190988.000000,587067.000000
25%,2.011004e+09,1.201100e+10,1.0,1.000000,1.000000,3.000000,1.000000,2.000000,8.00000,4.000000,41.000000,1.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,5.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,3574.000000,2.0,1.000000,2.000000,9.000000,7.0,77.0,777.0,0.000000,16.000000,103.000000,110.000000,10.000000,NaN,1.003250e+04,2011.000000,3.000000,8.000000,37.000000,9.000000,0.000000,35.107885,31.774099,210321.000000,631266.000000
50%,2.013040e+09,1.201304e+10,1.0,1.000000,2.000000,3.000000,2.000000,2.000000,8.00000,4.000000,43.000000,3.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,3616.000000,2.0,1.000000,4.000000,9.000000,7.0,77.0,777.0,0.000000,17.000000,132.000000,134.000000,79.500000,NaN,8.000100e+04,2013.000000,6.000000,15.000000,59.000000,14.000000,15.000000,35.174795,31.928148,216656.500000,648354.500000
75%,2.015081e+09,1.201508e+10,1.0,1.000000,7.000000,3.000000,3.000000,2.000000,9.00000,4.000000,43.000000,3.000000,0.000000,1.000000,1.000000,3.000000,3.000000,3.000000,7.000000,1.000000,1.000000,9.000000,9.000000,9.000000,1.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,3760.000000,2.0,5.000000,5.000000,9.000000,7.0,77.0,777.0,76.000000,18.000000,204.000000,201.500000,9999.000000,NaN,1.301240e+05,2015.000000,9.000000,23.000000,72.000000,17.000000,30.000000,35.296057,32.105871,228125.000000,668055.000000
max,2.018099e+09,1.201810e+10,1.0,3.000000,19.000000,3.000000,3.000000,2.000000,10.00000,4.000000,43.000000,9.000000,5.000000,7.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,3918.000000,2.0,5.000000,7.000000,9.000000,7.0,77.0,777.0,99.000000,49.000000,9998.000000,311.000000,9999.000000,NaN,1.000000e+08,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.522053,32.511338,249406.000000,713015.000000

In [77]:
m_all[(m_all['natural_area']==877) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)]

,id,provider_and_id,provider_code,provider_code_hebrew,file_type_police,accident_type,accident_type_hebrew,accident_severity,accident_severity_hebrew,accident_timestamp,location_accuracy,location_accuracy_hebrew,road_type,road_type_hebrew,road_shape,road_shape_hebrew,day_type,day_type_hebrew,police_unit,police_unit_hebrew,one_lane,one_lane_hebrew,multi_lane,multi_lane_hebrew,speed_limit,speed_limit_hebrew,road_intactness,road_intactness_hebrew,road_width,road_width_hebrew,road_sign,road_sign_hebrew,road_light,road_light_hebrew,road_control,road_control_hebrew,weather,weather_hebrew,road_surface,road_surface_hebrew,road_object,road_object_hebrew,object_distance,object_distance_hebrew,didnt_cross,didnt_cross_hebrew,cross_mode,cross_mode_hebrew,cross_location,cross_location_hebrew,cross_direction,cross_direction_hebrew,road1,road2,km,km_raw,km_accurate,yishuv_symbol,yishuv_name,geo_area,geo_area_hebrew,day_night,day_night_hebrew,day_in_week,day_in_week_hebrew,traffic_light,traffic_light_hebrew,region,region_hebrew,district,district_hebrew,natural_area,natural_area_hebrew,municipal_status,municipal_status_hebrew,yishuv_shape,yishuv_shape_hebrew,street1,street1_hebrew,street2,street2_hebrew,house_number,non_urban_intersection,non_urban_intersection_hebrew,non_urban_intersection_by_junction_number,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour_raw_hebrew,accident_hour,accident_minute,geom,longitude,latitude,x,y
759812,2017005348,12017005348,1,הלשכה המרכזית לסטטיסטיקה - סוג תיק 1,NaN,3,התנגשות חזית באחור,3,קלה,2017-04-05 17:00:00,9,לא עוגן,2,עירונית לא בצומת,8,כביש ישר / צומת,4,יום אחר,12,מרחב גליל,3,דו סיטרי אין קו הפרדה רצוף,0,NaN,1,"עד 50 קמ""ש",1,אין ליקויים,3,7 עד 10.5 מטר,3,אין ליקוי,1,אור יום רגיל,NaN,NaN,1,בהיר,1,יבש,9,לא ידוע,9,לא ידוע,9,לא ידוע,0,NaN,0,NaN,9,לא ידוע,NaN,NaN,NaN,NaN,NaN,5301,NaN,1,ישראל ללא יהודה ושומרון,1,יום,4,רביעי,9,לא ידוע,8.0,חבל עזה,87,דיר אל-בלח,877.0,NaN,NaN,NaN,9.0,מחנות פליטים עירוניים,NaN,NaN,NaN,NaN,9999.0,NaN,NaN,NaN,NaN,2017,4,5,69,17:00-17:14,17,0,NaN,NaN,NaN,NaN,NaN

**Null Conclusion:** Following `natural_area` had translation issues:
- 999 - all values missing, spread over various years
- 777 - all values missing, spread over various years
- 877 - all values (it's actually 1 value in 2017).  
- 432 - years 2013, 2014 are problematic, rest of the years are OK

**Specific values mistmatch investigations:**

In [153]:
temp = m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == False)]
calc_diff_counts_hebrew(temp, 'natural_area')

Shape of data: (557164, 98)

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
6        0.0
7        0.0
8        0.0
9        0.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       0.0
16    1421.0
17       0.0
18       0.0
19       0.0
20       0.0
21       0.0
22       0.0
23       0.0
24       0.0
25       0.0
26       0.0
27       0.0
28       0.0
29       0.0
30       0.0
31       0.0
32       0.0
33       0.0
34       0.0
35       0.0
36     -35.0
37     -54.0
38    -130.0
39     -96.0
40     -11.0
41     -80.0
42    -116.0
43    -244.0
44      -6.0
45    -303.0
46     -21.0
47      -9.0
48      -3.0
49     -13.0
50     -50.0
51     -52.0
52     -18.0
53     -16.0
54     -57.0
55     -18.0
56      -4.0
57     -79.0
58       NaN
dtype: float64

In [155]:
merge_with_hebrew(temp, 'natural_area')

    index_natural_area  count index_natural_area_hebrew
0                511.0  84328              אזור תל אביב
1                311.0  53832                 אזור חיפה
2                111.0  51504                 הרי יהודה
3                512.0  33932               אזור רמת גן
4                422.0  29542            אזור פתח תקווה
5                513.0  27111                אזור חולון
6                623.0  22099              אזור באר שבע
7                442.0  22017          אזור ראשון לציון
8                237.0  20700            הרי נצרת-תירען
9                411.0  18323                מערב השרון
10               421.0  16252                דרום השרון
11               441.0  15355               אזור רחובות
12               324.0  14653                 אזור חדרה
13               613.0  14595                אזור אשדוד
14               614.0  13617               אזור אשקלון
15               241.0  13151                אזור שפרעם
16               431.0  11513                       NaN
17               245.0   7607               אזור נהרייה
18               242.0   7522               אזור כרמיאל
19               234.0   7133                עמק יזרעאל
20               323.0   7114                הר אלכסנדר
21               246.0   6689                  אזור עכו
22               412.0   6501                מזרח השרון
23               221.0   5573                    כינרות
24               432.0   5553                 אזור רמלה
25               243.0   4609                אזור יחיעם
26               625.0   3938                אזור הערבה
27               612.0   3218                 אזור לכיש
28               112.0   2778                שפלת יהודה
29               212.0   2572          גליל עליון מזרחי
30               222.0   2520          גליל תחתון מזרחי
31               611.0   2200                אזור מלאכי
32               235.0   2023                אזור יקנעם
33               621.0   1899                  אזור גרר
34               211.0   1747                  עמק חולה
35               760.0   1426               נפת בית לחם
36               626.0   1386            הר הנגב הצפוני
37               740.0   1332               נפת ראמאללה
38               231.0   1202               עמק בית שאן
39               730.0   1106               נפת טול כרם
40               622.0   1095                 אזור בשור
41               213.0   1015                 אזור חצור
42               322.0    899           אזור זכרון יעקב
43               321.0    655                 חוף הכרמל
44               244.0    649                אזור אילון
45               232.0    346                  עמק חרוד
46               291.0    325               אזור החרמון
47               233.0    316                  רמת כוכב
48               292.0    313                גולן צפוני
49               710.0    300                  נפת גנין
50               293.0    250               גולן תיכוני
51               770.0    198                 נפת חברון
52               236.0    180                  רמת מנשה
53               720.0    164                   נפת שכם
54               750.0    107          נפת ירדן (יריחו)
55               294.0     89                גולן דרומי
56               624.0     85              אזור ים המלח
57               627.0      6            הר הנגב הדרומי
58                 NaN  10092                  אזור לוד
59                 NaN   1421              אזור מודיעין

In [137]:
temp[temp['natural_area_hebrew'] == 'אזור לוד'].shape

(10092, 98)

In [138]:
temp[temp['natural_area'] == 431].shape

(11513, 98)

In [139]:
temp[temp['natural_area'] == 431].shape[0] - temp[temp['natural_area_hebrew'] == 'אזור לוד'].shape[0]

1421

In [140]:
temp[temp['natural_area_hebrew'] == 'אזור מודיעין'].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.421000e+03,1.421000e+03,1421.000000,371.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,133.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,0.0,0.0,0.0,0.0,1421.000000,1421.0,1421.000000,1421.000000,1421.000000,1421.0,1421.0,1421.0,1421.000000,1421.000000,1372.000000,260.000000,1156.000000,0.0,260.000000,1421.000000,1421.00000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000
mean,2.016597e+09,2.955354e+10,2.753695,2.735849,4.341309,2.990148,2.059817,1.813512,8.919775,3.919071,51.918367,8.093596,0.172414,0.159043,0.113300,0.339901,4.780436,8.909219,4.315789,8.114004,8.096411,8.852217,8.853624,8.994370,0.094300,0.075299,8.860662,NaN,NaN,NaN,NaN,1190.842365,1.0,1.988037,3.558058,8.498241,4.0,43.0,431.0,1.864884,15.972555,631.795918,396.719231,6094.153979,NaN,462212.242308,2016.546798,6.43209,15.206193,54.665025,13.104856,18.684025,35.002899,31.902003,200385.017593,645462.467980
std,1.110252e+06,6.574554e+09,0.657456,0.678060,3.854709,0.105690,0.899106,0.389637,0.296522,0.398671,1.785412,2.563634,0.702490,0.529454,0.330129,1.003103,0.624328,3.260658,2.023979,2.500075,2.524220,0.940095,1.022822,0.167742,0.611719,0.534014,1.023117,NaN,NaN,NaN,NaN,69.644584,0.0,1.725696,1.829427,1.993519,0.0,0.0,0.0,6.650641,3.784878,1402.848279,419.380010,4866.658266,NaN,285097.617389,1.110176,3.44930,8.837603,20.207490,5.059601,17.025026,0.018392,0.010762,1739.552077,1193.655031
min,2.015000e+09,1.201501e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,707.000000,1.0,1.000000,1.000000,0.000000,4.0,43.0,431.0,0.000000,15.000000,0.000000,100.000000,1.000000,NaN,0.000000,2015.000000,1.00000,1.000000,1.000000,0.000000,0.000000,34.932473,31.868664,193732.000000,641768.000000
25%,2.016006e+09,3.201506e+10,3.000000,3.000000,2.000000,3.000000,1.000000,2.000000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,1200.000000,1.0,1.000000,2.000000,9.000000,4.0,43.0,431.0,0.000000,15.000000,139.000000,160.000000,30.000000,NaN,220001.000000,2016.000000,3.00000,8.000000,37.000000,9.000000,0.000000,34.998747,31.895279,199993.000000,644715.000000
50%,2.017007e+09,3.201608e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,1200.000000,1.0,1.000000,3.000000,9.000000,4.0,43.0,431.0,0.000000,15.000000,305.000000,303.000000,9999.000000,NaN,415001.000000,2017.000000,6.00000,15.000000,57.000000,14.000000,15.000000,35.008973,31.900540,200957.000000,645299.000000
75%,2.018005e+09,3.201709e+10,3.000000,3.000000,4.000000,3.000000,3.000000,2.000000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,1200.000000,1.0,1.000000,5.000000,9.000000,4.0,43.0,431.0,0.000000,15.000000,453.000000,451.000000,9999.000000,NaN,780145.000000,2018.000000,10.00000,23.000000,71.000000,17.000000,30.000000,35.012575,31.909651,201299.000000,646309.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,3.000000,2.000000,9.000000,4.000000,61.000000,9.000000,5.000000,5.000000,3.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,1333.000000,1.0,5.000000,7.000000,9.000000,4.0,43.0,431.0,30.000000,37.000000,9998.000000,3196.000000,9999.000000,NaN,780217.000000,2018.000000,12.00000,31.000000,96.000000,23.000000,45.000000,35.037119,31.933893,203619.000000,649013.000000

In [141]:
temp[temp['natural_area_hebrew'] == 'אזור לוד'].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.009200e+04,1.009200e+04,10092.000000,0.0,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,682.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,0.0,0.0,0.0,0.0,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.0,10092.0,10092.0,9912.000000,10092.000000,9738.000000,914.000000,9024.000000,0.0,9.050000e+02,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000,10092.000000
mean,2.010293e+09,2.827070e+10,2.626040,NaN,4.462446,2.988506,2.162901,1.894174,8.791815,3.901011,51.758918,8.155470,0.133274,0.138030,0.047166,0.283987,4.794491,8.782699,4.906158,8.040924,8.056778,8.831847,9.166072,8.951050,0.126338,0.144669,8.880400,NaN,NaN,NaN,NaN,4807.473048,1.000099,2.058264,3.549643,8.666568,4.0,43.0,431.0,11.003228,17.423405,770.006572,413.100656,7085.333444,NaN,3.610563e+06,2010.258224,6.158442,15.653785,53.352358,12.788545,17.972652,34.915399,31.933941,192118.377923,649024.110781
std,1.626658e+06,7.798335e+09,0.779829,NaN,4.146184,0.123000,0.798261,0.307631,0.461758,0.460092,1.721418,2.437995,0.627054,0.438546,0.234636,0.875915,0.623887,3.299391,2.062886,2.586414,2.564759,0.989672,20.476674,0.388342,0.651407,0.946010,0.953203,NaN,NaN,NaN,NaN,3275.233232,0.009954,1.764495,1.837576,1.665847,0.0,0.0,0.0,27.676329,6.891315,1974.987263,818.033051,4536.240214,NaN,7.686986e+06,1.627758,3.394015,8.797496,21.308422,5.320365,16.657046,0.060802,0.029377,5745.881656,3265.026554
min,2.008000e+09,1.200800e+10,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,64.000000,1.000000,1.000000,1.000000,0.000000,4.0,43.0,431.0,0.000000,15.000000,0.000000,0.000000,1.000000,NaN,1.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.819699,31.830446,183097.000000,637555.000000
25%,2.009027e+09,3.200803e+10,3.000000,NaN,2.000000,3.000000,1.000000,2.000000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,1200.000000,1.000000,1.000000,2.000000,9.000000,4.0,43.0,431.0,0.000000,15.000000,100.000000,160.000000,40.000000,NaN,2.800010e+05,2009.000000,3.000000,8.000000,36.000000,8.000000,0.000000,34.870624,31.910548,187881.000000,646408.000000
50%,2.010049e+09,3.201001e+10,3.000000,NaN,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,7000.000000,1.000000,1.000000,3.000000,9.000000,4.0,43.0,431.0,0.000000,15.000000,301.000000,314.000000,9999.000000,NaN,6.100010e+05,2010.000000,6.000000,16.000000,55.000000,13.000000,15.000000,34.893084,31.931606,190012.000000,648777.000000
75%,2.011067e+09,3.201105e+10,3.000000,NaN,4.000000,3.000000,3.000000,2.000000,9.000000,4.000000,52.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,8500.000000,1.000000,5.000000,5.000000,9.000000,4.0,43.0,431.0,0.000000,15.000000,442.000000,451.000000,9999.000000,NaN,8.200001e+06,2011.000000,9.000000,23.000000,69.000000,17.000000,30.000000,34.993392,31.948880,199486.000000,650683.000000
max,2.014100e+09,3.201410e+10,3.000000,NaN,20.000000,3.000000,3.000000,2.000000,10.000000,4.000000,61.000000,9.000000,5.000000,5.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,8500.000000,2.000000,5.000000,7.000000,9.000000,4.0,43.0,431.0,99.000000,52.000000,9998.000000,9998.000000,10000.000000,NaN,1.000000e+08,2014.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.037033,32.023347,203611.000000,658961.000000

**Specific values conclusion:**

Seems that `natural_area` 431 was called `אזור לוד` until and including 2014, and `אזור מודיעין` since

### municipal_status and municipal_status_hebrew

In [78]:
# municipal_status                             604357 non-null float64
# municipal_status_hebrew                      604314 non-null object
m_all[(m_all['municipal_status'].isnull() == False) & (m_all['municipal_status_hebrew'].isnull() == True)].shape

(43, 98)

In [79]:
m_all[(m_all['municipal_status'].isnull() == False) & (m_all['municipal_status_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.300000e+01,4.300000e+01,43.0,0.0,43.000000,43.000000,43.0,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,27.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,0.0,0.0,0.0,0.0,43.0,43.000000,43.000000,43.000000,43.000000,0.0,43.0,0.0,43.0,0.0,38.000000,25.0,18.0,0.0,0.0,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,0.0,0.0,0.0,0.0
mean,2.009058e+09,1.200906e+10,1.0,NaN,6.860465,2.581395,9.0,1.418605,8.162791,3.930233,27.720930,3.209302,0.651163,1.720930,1.232558,1.930233,3.720930,3.302326,5.037037,2.139535,3.232558,8.953488,8.697674,8.744186,0.186047,0.255814,8.488372,NaN,NaN,NaN,NaN,0.0,1.093023,1.837209,4.604651,7.186047,NaN,99.0,NaN,999.0,NaN,6577.526316,0.0,9999.0,NaN,NaN,2009.023256,7.674419,16.441860,51.232558,12.325581,13.953488,NaN,NaN,NaN,NaN
std,1.140631e+06,1.140631e+06,0.0,NaN,4.857892,0.499169,0.0,0.499169,1.089566,0.457496,12.251969,2.605472,1.541238,1.548049,1.191981,1.386935,0.959305,3.615673,2.710116,2.799502,3.038148,0.213083,1.389328,0.726801,0.698836,0.847771,1.894504,NaN,NaN,NaN,NaN,0.0,0.293903,1.646500,2.237553,3.574085,NaN,0.0,NaN,0.0,NaN,4806.790662,0.0,0.0,NaN,NaN,1.144102,3.682138,8.907734,18.779215,4.734478,15.490325,NaN,NaN,NaN,NaN
min,2.008004e+09,1.200800e+10,1.0,NaN,1.000000,2.000000,9.0,1.000000,3.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.000000,2.000000,6.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,0.0,1.000000,1.000000,1.000000,0.000000,NaN,99.0,NaN,999.0,NaN,0.000000,0.0,9999.0,NaN,NaN,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,2.008043e+09,1.200804e+10,1.0,NaN,2.000000,2.000000,9.0,1.000000,8.000000,4.000000,14.000000,1.000000,0.000000,1.000000,1.000000,1.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,0.0,1.000000,1.000000,3.000000,9.000000,NaN,99.0,NaN,999.0,NaN,0.000000,0.0,9999.0,NaN,NaN,2008.000000,5.000000,9.500000,37.500000,9.000000,0.000000,NaN,NaN,NaN,NaN
50%,2.009030e+09,1.200903e+10,1.0,NaN,8.000000,3.000000,9.0,1.000000,8.000000,4.000000,34.000000,3.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,7.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,0.0,1.000000,1.000000,5.000000,9.000000,NaN,99.0,NaN,999.0,NaN,9998.000000,0.0,9999.0,NaN,NaN,2009.000000,9.000000,17.000000,54.000000,13.000000,0.000000,NaN,NaN,NaN,NaN
75%,2.010008e+09,1.201001e+10,1.0,NaN,10.000000,3.000000,9.0,2.000000,9.000000,4.000000,34.000000,4.000000,0.000000,3.500000,1.000000,3.000000,5.000000,5.500000,7.000000,1.000000,6.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,0.0,1.000000,1.000000,6.000000,9.000000,NaN,99.0,NaN,999.0,NaN,9998.000000,0.0,9999.0,NaN,NaN,2010.000000,11.000000,22.500000,67.000000,16.500000,30.000000,NaN,NaN,NaN,NaN
max,2.012055e+09,1.201205e+10,1.0,NaN,15.000000,3.000000,9.0,2.000000,10.000000,4.000000,52.000000,9.000000,5.000000,5.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,4.000000,4.000000,9.000000,NaN,NaN,NaN,NaN,0.0,2.000000,5.000000,7.000000,9.000000,NaN,99.0,NaN,999.0,NaN,9999.000000,0.0,9999.0,NaN,NaN,2012.000000,12.000000,31.000000,77.000000,19.000000,45.000000,NaN,NaN,NaN,NaN

In [81]:
m_all[m_all['municipal_status'] == 999].shape

(43, 98)

**Null Conclusion:** `municipal_status` == 999 is problematic, spread over numerous years

**Specific values mistmatch investigations:**

In [156]:
temp = m_all[m_all['municipal_status_hebrew'].isnull()==False]

merge_with_hebrew(temp, 'municipal_status')

    index_municipal_status   count index_municipal_status_hebrew
0                      0.0  482905                        עירייה
1                     99.0   96533                  מועצה מקומית
2                     20.0    1788                    דרום השרון
3                      9.0    1600                    עמק יזרעאל
4                     25.0    1406                   חבל מודיעין
5                      4.0    1194                       מטה אשר
6                     56.0    1118                          משגב
7                     16.0    1111                       עמק חפר
8                     26.0    1081                     מטה יהודה
9                     19.0    1009                     חוף השרון
10                    33.0     965                     באר טוביה
11                    15.0     916                     חוף הכרמל
12                    18.0     810                      לב השרון
13                     8.0     759                        הגלבוע
14                    13.0     714                         מגידו
15                    14.0     678                          מנשה
16                    40.0     599                       עמק לוד
17                    30.0     585                           גזר
18                    73.0     569                    מטה בנימין
19                     2.0     558                    מרום הגליל
20                    52.0     543                     מעלה יוסף
21                    12.0     520                        זבולון
22                    36.0     461                    חוף אשקלון
23                     6.0     458                     עמק הירדן
24                     1.0     424                  הגליל העליון
25                     3.0     422                  הגליל התחתון
26                    72.0     386                        שומרון
27                     7.0     296                           NaN
28                    27.0     290                       גן רווה
29                    71.0     270                          גולן
30                    55.0     262                 מבואות החרמון
31                    28.0     242                          ברנר
32                    41.0     238                     בני שמעון
33                    50.0     214                          לכיש
34                    38.0     188                         אשכול
35                    34.0     182                          שפיר
36                    35.0     181                          יואב
37                    39.0     153                      שדות נגב
38                    42.0     150                        מרחבים
39                    66.0     146                      שער הנגב
40                    66.0     146                  בוסתן אל-מרג
41                    37.0     146                      שער הנגב
42                    37.0     146                  בוסתן אל-מרג
43                    29.0     143                      חבל יבנה
44                    65.0     135                       אל-בטוף
45                    76.0     127                     גוש עציון
46                    32.0     109                         גדרות
47                    31.0     102                      נחל שורק
48                    51.0      91                           תמר
49                    24.0      80                          אפעל
50                    54.0      70                 הערבה התיכונה
51                    54.0      70                   ערבות הירדן
52                    75.0      70                 הערבה התיכונה
53                    75.0      70                   ערבות הירדן
54                    48.0      65                       רמת נגב
55                    69.0      52                       אל קסום
56                    78.0      46                      הר חברון
57                    45.0      44                         אלונה
58                    53.0      37                     חבל אילות
59                    74.0      31                        מגילות
60                    67.0      26                      אבו בסמה
61                    68.0      16                     נווה מדבר
62                     NaN     192                  בקעת בית שאן
63                     NaN     104                  עמק המעיינות

In [149]:
temp[temp['municipal_status_hebrew'] == 'בקעת בית שאן']['accident_year'].describe()

count     192.000000
mean     2010.791667
std         1.883612
min      2008.000000
25%      2009.000000
50%      2011.000000
75%      2012.000000
max      2014.000000
Name: accident_year, dtype: float64

In [150]:
temp[temp['municipal_status_hebrew'] == 'עמק המעיינות']['accident_year'].describe()

count     104.000000
mean     2016.394231
std         1.161003
min      2015.000000
25%      2015.000000
50%      2016.500000
75%      2017.000000
max      2018.000000
Name: accident_year, dtype: float64

**Specific values conclusion:**

`municipal_status` 7 was called `בקעת בית שאן` until and including 2014, and `עמק המעיינות` since

## yishuv_shape and yishuv_shape_hebrew

In [82]:
# yishuv_shape                                 605597 non-null float64
# yishuv_shape_hebrew                          561532 non-null object
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)].shape

(44065, 98)

In [83]:
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,4.406500e+04,4.406500e+04,44065.000000,3851.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,19199.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,43826.000000,42945.000000,42359.000000,42359.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44063.000000,44065.000000,6.000000,1.0,5.0,1.424400e+04,0.0,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,44065.000000,43504.000000,43504.000000,43504.000000,43504.000000
mean,2.012812e+09,1.201508e+10,1.000227,1.032719,4.076138,2.780279,1.256008,3.665381,8.220175,3.868512,29.426620,1.854851,1.139362,3.586066,0.811733,2.826733,3.236809,2.798003,3.639617,1.752275,1.734551,8.594599,8.308363,8.970975,0.061046,0.061682,8.848315,534.724821,374.257958,697.441772,695.306074,0.257302,1.111835,2.500511,3.922478,6.636287,8.999228,98.991581,998.914830,98.994984,98.993737,3331.666667,0.0,9999.0,2.175243e+04,NaN,2012.770407,6.453671,15.625304,55.089572,13.204266,19.087598,35.051854,32.270081,204996.211682,686298.201269
std,3.231172e+06,2.130201e+08,0.021303,0.253740,3.130061,0.510036,1.042107,0.472247,0.997726,0.532021,17.330462,2.570615,1.326877,1.685675,0.463543,1.323100,0.713400,2.713568,2.238065,2.223559,2.192272,1.309373,2.107291,0.360163,0.493692,0.475917,1.057082,1527.012971,1437.331930,926.635621,928.239265,22.061686,0.315167,1.936645,1.965971,3.747378,0.069358,0.753590,7.612869,0.598136,0.536737,5161.396155,NaN,0.0,1.200753e+06,NaN,3.226481,3.452249,8.767731,23.780093,5.934962,16.659886,0.239088,0.532481,22558.138537,59031.479314
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-312.000000,0.000000,1.000000,1.000000,1.000000,0.000000,2.000000,21.000000,211.000000,13.000000,53.000000,0.000000,0.0,9999.0,0.000000e+00,NaN,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.293560,29.550787,132646.000000,384801.000000
25%,2.010027e+09,1.201003e+10,1.000000,1.000000,2.000000,3.000000,1.000000,3.000000,8.000000,4.000000,12.000000,0.000000,0.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,20.000000,0.000000,96.000000,91.000000,0.000000,1.000000,1.000000,2.000000,1.000000,9.000000,99.000000,999.000000,99.000000,99.000000,0.000000,0.0,9999.0,7.570000e+02,NaN,2010.000000,3.000000,8.000000,37.000000,9.000000,0.000000,34.872716,31.920773,188142.500000,647593.250000
50%,2.013005e+09,1.201300e+10,1.000000,1.000000,3.000000,3.000000,1.000000,4.000000,8.000000,4.000000,20.000000,1.000000,0.000000,4.000000,1.000000,3.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,65.000000,0.000000,262.000000,260.000000,0.000000,1.000000,1.000000,4.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,0.000000,0.0,9999.0,1.621000e+03,NaN,2013.000000,6.000000,16.000000,59.000000,14.000000,15.000000,35.025246,32.207578,202584.000000,679355.000000
75%,2.016012e+09,1.201601e+10,1.000000,1.000000,5.000000,3.000000,1.000000,4.000000,9.000000,4.000000,51.000000,3.000000,2.000000,5.000000,1.000000,4.000000,3.000000,3.000000,6.000000,1.000000,1.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,424.000000,0.000000,920.000000,920.000000,0.000000,1.000000,5.000000,6.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,7494.000000,0.0,9999.0,4.072000e+03,NaN,2016.000000,9.000000,23.000000,73.000000,18.000000,30.000000,35.208493,32.753058,219834.250000,739829.000000
max,2.018100e+09,3.201003e+10,3.000000,3.000000,20.000000,3.000000,9.000000,4.000000,11.000000,4.000000,61.000000,9.000000,5.000000,8.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9998.000000,9998.000000,9999.000000,9999.000000,1981.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,99.000000,99.000000,9998.000000,0.0,9999.0,1.000000e+08,NaN,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.849314,33.293023,279767.000000,799843.000000

In [84]:
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)]['yishuv_shape'].value_counts()

99.0    44059
53.0        6
Name: yishuv_shape, dtype: int64

In [85]:
m_all[m_all['yishuv_shape']==99].shape

(44059, 98)

In [88]:
m_all[(m_all['yishuv_shape']==99) & (m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)]['accident_year'].value_counts()

2009    4765
2008    4602
2010    4348
2011    4072
2017    3932
2018    3851
2013    3829
2012    3751
2015    3716
2016    3654
2014    3539
Name: accident_year, dtype: int64

In [87]:
m_all[m_all['yishuv_shape']==53].shape

(30, 98)

In [89]:
m_all[(m_all['yishuv_shape']==53) & (m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)]['accident_year'].value_counts()

2010    2
2009    2
2008    2
Name: accident_year, dtype: int64

In [90]:
m_all[m_all['yishuv_shape']==53]['accident_year'].value_counts()

2017    9
2015    6
2018    6
2016    3
2010    2
2009    2
2008    2
Name: accident_year, dtype: int64

**Null Conclusion:** `yishuv_shape` translation issues:
- 99 spread over numerous years
- 53 for years 2008-2010, rest of the years there is 53 without problems

**Specific values mistmatch investigations:**

In [157]:
temp = m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == False)]
temp.shape

(561532, 98)

In [158]:
merge_with_hebrew(temp, 'yishuv_shape')

    index_yishuv_shape   count              index_yishuv_shape_hebrew
0                 13.0  107817                                    NaN
1                 14.0  105335                                    NaN
2                 16.0   79804                                    NaN
3                 12.0   64657                                    NaN
4                 15.0   56415                                    NaN
5                 11.0   25217                                ירושלים
6                 26.0   21513                                    NaN
7                 27.0   18525                                    NaN
8                 17.0   12449                                    NaN
9                 28.0   11180                                    NaN
10                31.0   10534                                    NaN
11                10.0    9452                            ראשון לציון
12                25.0    9073                                    NaN
13                 9.0    6789                                    NaN
14                33.0    6680                                קיבוצים
15                18.0    6522                                    NaN
16                35.0    1701                                    NaN
17                19.0    1608       יישובים יהודיים 4999-2000 תושבים
18                37.0    1417                       יישובים קהילתיים
19                29.0    1238                                    NaN
20                32.0    1077                        מושבים שיתופיים
21                45.0     745                                    NaN
22                52.0     675                                    NaN
23                49.0     635                                    NaN
24                34.0     357                                    NaN
25                46.0      66                            שבטי בדווים
26                51.0      27                                   מקום
27                53.0      24                         סמלים קיבוציים
28                 NaN   87474   יישובים יהודיים 499999-200000 תושבים
29                 NaN   62273      100,000-199,999-תושב, יישוב יהודי
30                 NaN   43062   יישובים יהודיים 199999-100000 תושבים
31                 NaN   40294                            תל אביב-יפו
32                 NaN   40190        20,000-49,999-תושב, יישוב יהודי
33                 NaN   39614     יישובים יהודיים 49999-20000 תושבים
34                 NaN   31926     יישובים יהודיים 99999-50000 תושבים
35                 NaN   24489        50,000-99,999-תושב, יישוב יהודי
36                 NaN   24363    יישובים יהודיים 500000 תושבים ומעלה
37                 NaN   20343                                   חיפה
38                 NaN   12579  יישובים לא יהודיים 49999-20000 תושבים
39                 NaN    9817     10,000-19,999-תושב, יישוב לא-יהודי
40                 NaN    8934     20,000-49,999-תושב, יישוב לא-יהודי
41                 NaN    8708  יישובים לא יהודיים 19999-10000 תושבים
42                 NaN    7385        10,000-19,999-תושב, יישוב יהודי
43                 NaN    6788                                  אשדוד
44                 NaN    5974    יישובים לא יהודיים 9999-5000 תושבים
45                 NaN    5821          מושבים - לרבות כפרים שיתופיים
46                 NaN    5206       2,000-9,999-תושב, יישוב לא-יהודי
47                 NaN    5203  יישובים לא יהודיים 99999-50000 תושבים
48                 NaN    5064     יישובים יהודיים 19999-10000 תושבים
49                 NaN    4713          מושבים (לרבות כפרים שיתופיים)
50                 NaN    4059          2,000-9,999-תושב, יישוב יהודי
51                 NaN    3870     50,000-99,999-תושב, יישוב לא-יהודי
52                 NaN    2463       יישובים יהודיים 9999-5000 תושבים
53                 NaN    1167    יישובים לא יהודיים 4999-2000 תושבים
54                 NaN     882          יישובים כפריים אחרים, יהודיים
55                 NaN     819           יישובים כפריים אחרים יהודיים
56                 NaN     402        יישובים כפריים אחרים לא יהודיים
57                 NaN     399                            מוקד תעסוקה
58                 NaN     352       יישובים כפריים - לא יהודי - יש"ע
59                 NaN     343       יישובים כפריים אחרים, לא-יהודיים
60                 NaN     283                         יישובים כפריים
61                 NaN     276         מוקד תעסוקה וחינוך מחוץ ליישוב
62                 NaN     234                יישובים מוסדיים יהודיים
63                 NaN     123               יישובים מוסדיים, יהודיים
64                 NaN      71  ערים ויישובים עירוניים -לא-יהודי-יש"ע
65                 NaN       1                  מחנות פליטים עירוניים

In [159]:
calc_diff_counts_hebrew(temp, 'yishuv_shape')

Shape of data: (561532, 98)

0     20343.0
1     43062.0
2     36742.0
3     24363.0
4     16225.0
5    -14397.0
6    -10413.0
7     -6692.0
8    -12040.0
9    -13183.0
10    -9809.0
11    -3127.0
12     -744.0
13    -2663.0
14    -2254.0
15    -2186.0
16    -5684.0
17    -5180.0
18    -5263.0
19    -4736.0
20    -4744.0
21    -4461.0
22    -4528.0
23    -4429.0
24    -4356.0
25    -3993.0
26    -3843.0
27    -2439.0
28        NaN
29        NaN
30        NaN
31        NaN
32        NaN
33        NaN
34        NaN
35        NaN
36        NaN
37        NaN
38        NaN
39        NaN
40        NaN
41        NaN
42        NaN
43        NaN
44        NaN
45        NaN
46        NaN
dtype: float64

**Specific values conclusion:** a big mess, worth investing more time to understand

### street1 and street1_hebrew

In [91]:
# street1                                      553240 non-null float64
# street1_hebrew                               389936 non-null object
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].shape

(163304, 98)

In [92]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.633040e+05,1.633040e+05,163304.000000,11643.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,2629.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,0.0,0.0,0.0,0.0,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163072.000000,163304.000000,163072.000000,162102.000000,163072.000000,163304.000000,616.000000,162192.000000,0.0,6.000000e+00,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,163304.000000,162694.000000,162694.000000,162694.000000,162694.000000
mean,2.012696e+09,3.065780e+10,2.864510,2.876492,4.938415,2.985359,2.026307,1.993191,8.682139,3.876696,25.736351,8.597922,0.035835,0.083048,0.057004,0.140989,4.885765,9.291744,5.384557,8.530269,8.541138,8.838277,8.969560,8.966553,0.089385,0.069147,8.933339,NaN,NaN,NaN,NaN,3835.832031,1.014856,2.025082,3.760134,8.970864,3.295888,35.500827,356.916902,27.239374,21.406624,139.165581,47.224026,9956.880913,NaN,1.884508e+07,2012.654173,6.385226,15.699542,55.252229,13.274764,17.297617,35.073846,32.394842,207067.754724,700131.234366
std,3.209588e+06,5.026161e+09,0.502617,0.481437,4.201458,0.130662,0.427273,0.082238,0.523821,0.514436,16.734344,1.646050,0.326048,0.415699,0.268631,0.615550,0.493530,2.805098,1.985700,1.874383,1.846632,0.923896,12.496107,0.381145,0.659719,0.652950,0.712391,NaN,NaN,NaN,NaN,3331.710163,0.120976,1.746297,1.915471,0.495779,1.494414,14.612485,143.716509,44.353320,7.504976,1166.944236,631.319654,643.122986,NaN,2.430330e+07,3.205090,3.406720,8.768506,20.026853,5.012964,16.414264,0.243024,0.510800,22935.695825,56618.479965
min,2.008000e+09,1.200800e+10,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,0.000000,0.000000,1.000000,NaN,2.000000e+00,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.283528,29.544820,131706.000000,384146.000000
25%,2.010013e+09,3.200905e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,8.000000,4.000000,12.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,613.000000,1.000000,1.000000,2.000000,9.000000,2.000000,24.000000,241.000000,0.000000,15.000000,0.000000,0.000000,9999.000000,NaN,8.152508e+06,2010.000000,3.000000,8.000000,41.000000,10.000000,0.000000,34.874859,32.077126,188359.000000,664939.000000
50%,2.013011e+09,3.201205e+10,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,9.000000,4.000000,14.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,2710.000000,1.000000,1.000000,4.000000,9.000000,3.000000,31.000000,311.000000,0.000000,18.000000,0.000000,0.000000,9999.000000,NaN,1.016007e+07,2013.000000,6.000000,16.000000,57.000000,14.000000,15.000000,35.084320,32.520113,208215.000000,713989.000000
75%,2.015091e+09,3.201507e+10,3.000000,3.000000,8.000000,3.000000,2.000000,2.000000,9.000000,4.000000,38.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,NaN,NaN,NaN,NaN,7300.000000,1.000000,5.000000,5.000000,9.000000,4.000000,43.000000,431.000000,56.000000,27.000000,0.000000,0.000000,9999.000000,NaN,1.621030e+07,2015.000000,9.000000,23.000000,70.000000,17.000000,30.000000,35.290338,32.805333,227504.000000,745619.000000
max,2.018100e+09,3.201810e+10,3.000000,3.000000,20.000000,3.000000,9.000000,2.000000,11.000000,4.000000,61.000000,9.000000,5.000000,7.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,9800.000000,2.000000,5.000000,7.000000,9.000000,7.000000,99.000000,777.000000,999.000000,53.000000,9999.000000,9998.000000,9999.000000,NaN,6.704001e+07,2018.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.838807,33.281610,278706.000000,798503.000000

In [163]:
m_all['street1'].nunique()

3331

In [94]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

0.0       160902
9998.0       831
9991.0       825
9992.0       246
9993.0       188
9994.0       131
942.0         21
9995.0        16
999.0         13
6713.0         8
916.0          6
195.0          6
547.0          4
805.0          4
7001.0         3
9999.0         3
202.0          3
221.0          2
828.0          2
6712.0         2
921.0          2
687.0          2
781.0          2
261.0          2
130.0          2
6742.0         2
5094.0         2
6718.0         1
9291.0         1
105.0          1
6721.0         1
6724.0         1
6725.0         1
6731.0         1
6732.0         1
914.0          1
4.0            1
574.0          1
4098.0         1
193.0          1
1058.0         1
139.0          1
197.0          1
102.0          1
198.0          1
794.0          1
812.0          1
1104.0         1
6505.0         1
6506.0         1
6519.0         1
6520.0         1
6521.0         1
280.0          1
6746.0         1
206.0          1
9099.0         1
6743.0         1
2040.0         1
1177.0         1
7678.0         1
164.0          1
5394.0         1
235.0          1
236.0          1
691.0          1
1898.0         1
950.0          1
701.0          1
7756.0         1
101.0          1
485.0          1
1430.0         1
975.0          1
244.0          1
361.0          1
123.0          1
103.0          1
7955.0         1
671.0          1
2678.0         1
925.0          1
461.0          1
1179.0         1
780.0          1
2372.0         1
949.0          1
149.0          1
108.0          1
154.0          1
1233.0         1
887.0          1
893.0          1
2572.0         1
161.0          1
113.0          1
163.0          1
909.0          1
228.0          1
658.0          1
107.0          1
Name: street1, dtype: int64

In [97]:
m_all[(m_all['street1'] != 0) & (m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].shape

(2402, 98)

In [108]:
num_total = []
for street in m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts().index:
    num_total.append(m_all[m_all['street1'] == street].shape[0])
num_total - m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

0.0          0
9998.0       0
9991.0     102
9992.0       0
9993.0       0
9994.0       0
942.0      486
9995.0       0
999.0       42
6713.0       2
916.0      510
195.0     3577
547.0      506
805.0       96
7001.0     517
9999.0       0
202.0     1144
221.0     1591
828.0       65
6712.0       4
921.0      286
687.0       10
781.0       34
261.0      160
130.0      398
6742.0      14
5094.0       0
6718.0       0
9291.0       0
105.0     1472
6721.0      28
6724.0       4
6725.0      70
6731.0      19
6732.0       1
914.0      416
4.0          0
574.0       42
4098.0       2
193.0      131
1058.0      70
139.0      802
197.0      333
102.0     2034
198.0      193
794.0       65
812.0       82
1104.0     301
6505.0     117
6506.0     127
6519.0      51
6520.0      69
6521.0      90
280.0      116
6746.0       1
206.0      597
9099.0       0
6743.0       1
2040.0       0
1177.0       9
7678.0       0
164.0      462
5394.0      10
235.0      708
236.0      235
691.0       42
1898.0       2
950.0      166
701.0     1411
7756.0       0
101.0     4268
485.0      108
1430.0       4
975.0       49
244.0      213
361.0      804
123.0      635
103.0     2328
7955.0       0
671.0       50
2678.0       0
925.0     2425
461.0     1278
1179.0      60
780.0       17
2372.0      41
949.0       72
149.0      364
108.0     1890
154.0      358
1233.0      24
887.0        4
893.0      136
2572.0      50
161.0     1197
113.0      853
163.0      366
909.0      146
228.0      428
658.0       48
107.0     1298
Name: street1, dtype: int64

In [164]:
temp = m_all[(m_all['street1'].isnull()==False) & (m_all['street1_hebrew'].isnull()==False)]
temp.shape

(389936, 98)

In [167]:
m_all[(m_all['street1'] != 0) & (m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

9998.0    831
9991.0    825
9992.0    246
9993.0    188
9994.0    131
942.0      21
9995.0     16
999.0      13
6713.0      8
916.0       6
195.0       6
805.0       4
547.0       4
9999.0      3
7001.0      3
202.0       3
130.0       2
6742.0      2
5094.0      2
687.0       2
6712.0      2
221.0       2
781.0       2
921.0       2
261.0       2
828.0       2
461.0       1
154.0       1
6506.0      1
6743.0      1
108.0       1
2678.0      1
6505.0      1
4.0         1
198.0       1
101.0       1
206.0       1
123.0       1
102.0       1
6521.0      1
6520.0      1
161.0       1
361.0       1
950.0       1
6721.0      1
6725.0      1
4098.0      1
893.0       1
658.0       1
925.0       1
1058.0      1
1430.0      1
235.0       1
794.0       1
701.0       1
6731.0      1
149.0       1
2040.0      1
1233.0      1
7756.0      1
975.0       1
6519.0      1
671.0       1
107.0       1
163.0       1
103.0       1
105.0       1
2372.0      1
1179.0      1
6746.0      1
9099.0      1
2572.0      1
197.0       1
139.0       1
1898.0      1
6718.0      1
914.0       1
7955.0      1
691.0       1
949.0       1
6732.0      1
812.0       1
6724.0      1
7678.0      1
485.0       1
9291.0      1
887.0       1
909.0       1
574.0       1
228.0       1
113.0       1
280.0       1
780.0       1
164.0       1
1104.0      1
244.0       1
236.0       1
1177.0      1
5394.0      1
193.0       1
Name: street1, dtype: int64

**Null Conclusion:** 160902 out of 163304 that are missing are `street1` == 0, other 2402 miscellenious.  
Some of the miscellenious all the index translation is missing, some only part of the instances translation missing.
See details above.

**Specific values mistmatch investigations:**

Didn't do detailed investigation, especially due to all the differences already in the nulls

**Specific values conclusion:**

See above

## street2 and street2_hebrew

In [109]:
# street2                                      71838 non-null float64
# street2_hebrew                               70713 non-null object
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)].shape

(1125, 98)

In [111]:
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]['street2'].value_counts()

0.0       1092
9998.0      15
9991.0       7
9992.0       3
9994.0       2
828.0        1
3226.0       1
130.0        1
9993.0       1
2632.0       1
4.0          1
Name: street2, dtype: int64

In [112]:
num_total = []
for street in m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]['street2'].value_counts().index:
    num_total.append(m_all[m_all['street2'] == street].shape[0])
num_total - m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]['street2'].value_counts()

0.0        0
9998.0     1
9991.0    27
9992.0     0
9994.0     0
828.0      7
3226.0     0
130.0     76
9993.0     1
2632.0    22
4.0        0
Name: street2, dtype: int64

**Null Conclusion:** 1092 out of 1125 that are missing are `street2` == 0, other 33 miscellenious.  
Some of the miscellenious all the index translation is missing, some only part of the instances translation missing.
See details above.

**Specific values mistmatch investigations:** see conclusions for `street1` above

**Specific values conclusion:** see conclusions for `street1` above

## non_urban_intersection and non_urban_intersection_hebrew

In [115]:
# non_urban_intersection                       34382 non-null float64
# non_urban_intersection_hebrew                33018 non-null object
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)].shape

(1364, 98)

In [168]:
m_all['non_urban_intersection'].nunique()

1798

In [116]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,1.364000e+03,1.364000e+03,1364.000000,0.0,1364.000000,1364.000000,1364.000000,1364.0,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,644.000000,1364.000000,1364.000000,1364.000000,1364.00000,1364.000000,1364.000000,1364.000000,1364.000000,1363.000000,1325.000000,1340.000000,1340.000000,1364.0,1364.000000,1364.000000,1364.000000,1364.000000,662.0,1364.0,662.0,662.0,662.0,0.0,0.0,0.0,1.364000e+03,0.0,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000,1364.000000
mean,2.014349e+09,2.230760e+10,2.029326,NaN,3.648827,2.925953,1.029326,3.0,8.572581,3.893695,31.214809,5.109238,0.834311,1.802053,0.456012,1.530059,4.054252,6.046921,2.785714,5.260264,5.247067,8.849707,8.79912,8.990469,0.071848,0.062317,8.840176,349.512106,982.015849,720.748507,720.748507,0.0,1.046921,2.337243,3.641496,4.875367,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,2.614507e+05,NaN,2014.300587,6.637097,15.569648,55.606305,13.331378,19.211877,34.989073,32.188017,199067.472141,677204.479472
std,1.909412e+06,9.998990e+09,0.999937,NaN,3.129017,0.317641,0.404330,0.0,0.805254,0.471947,17.584970,4.183144,1.274663,2.127029,0.512758,1.766188,1.015646,4.231992,1.759413,3.958201,3.961826,0.866000,1.17474,0.196962,0.539666,0.456230,1.087229,1084.261136,2013.422810,908.231686,908.231686,0.0,0.211547,1.887688,1.874588,4.131089,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,4.742781e+06,NaN,1.906617,3.448964,8.819058,22.631755,5.643364,16.610814,0.222851,0.507965,21046.973143,56308.864532
min,2.008000e+09,1.200800e+10,1.000000,NaN,1.000000,1.000000,1.000000,3.0,1.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.00000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.000000,1.000000,1.000000,0.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,0.000000e+00,NaN,2008.000000,1.000000,1.000000,1.000000,0.000000,0.000000,34.439143,29.832463,146599.000000,416011.000000
25%,2.015013e+09,1.201505e+10,1.000000,NaN,2.000000,3.000000,1.000000,3.0,8.000000,4.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,2.000000,1.000000,1.000000,9.000000,9.00000,9.000000,0.000000,0.000000,9.000000,6.000000,0.000000,111.000000,111.000000,0.0,1.000000,1.000000,2.000000,1.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,6.910000e+02,NaN,2015.000000,4.000000,8.000000,39.000000,9.000000,0.000000,34.821198,31.901670,183236.000000,645446.750000
50%,2.015041e+09,3.200805e+10,3.000000,NaN,3.000000,3.000000,1.000000,3.0,9.000000,4.000000,34.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.00000,9.000000,0.000000,0.000000,9.000000,60.000000,90.000000,300.000000,300.000000,0.0,1.000000,1.000000,4.000000,1.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,1.943000e+03,NaN,2015.000000,7.000000,16.000000,58.000000,14.000000,15.000000,34.941037,32.117734,194591.000000,669409.000000
75%,2.015072e+09,3.201504e+10,3.000000,NaN,3.000000,3.000000,1.000000,3.0,9.000000,4.000000,51.000000,9.000000,2.000000,4.000000,1.000000,3.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.00000,9.000000,0.000000,0.000000,9.000000,89.000000,653.000000,1159.000000,1159.000000,0.0,1.000000,5.000000,5.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,4.112000e+03,NaN,2015.000000,10.000000,23.000000,72.000000,17.000000,30.000000,35.100809,32.636451,209748.000000,726898.000000
max,2.017075e+09,3.201708e+10,3.000000,NaN,19.000000,3.000000,9.000000,3.0,9.000000,4.000000,61.000000,9.000000,5.000000,7.000000,3.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,9.00000,9.000000,8.000000,4.000000,9.000000,9088.000000,9977.000000,4721.000000,4721.000000,0.0,2.000000,5.000000,7.000000,9.000000,9.0,99.0,999.0,99.0,99.0,NaN,NaN,NaN,1.000000e+08,NaN,2017.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.731830,33.235774,268660.000000,793420.000000

In [117]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts()

1203.0      63
8015.0      31
867.0       24
57.0        24
2043.0      20
5.0         20
4071.0      19
317.0       15
58.0        15
325.0       14
2324.0      13
3497.0      12
4135.0      12
8017.0      11
4037.0      10
319.0       10
373.0       10
153.0        9
9378.0       9
4049.0       9
1083.0       9
4083.0       9
9736.0       9
1983.0       9
4197.0       9
475.0        8
641.0        8
1191.0       8
335.0        8
347.0        7
8055.0       7
1265.0       7
2169.0       7
1301.0       7
4043.0       7
639.0        7
4194.0       7
4182.0       7
8056.0       7
9470.0       6
4158.0       6
521.0        6
105.0        6
4189.0       6
3017.0       6
1137.0       6
3019.0       6
755.0        6
3898.0       6
1131.0       6
4223.0       6
361.0        6
831.0        5
4112.0       5
7095.0       5
536.0        5
683.0        5
863.0        5
3478.0       5
431.0        5
1421.0       5
8026.0       5
693.0        5
1161.0       5
4200.0       5
1317.0       5
1339.0       5
1621.0       5
91.0         5
1321.0       4
4177.0       4
445.0        4
9388.0       4
837.0        4
7289.0       4
1207.0       4
357.0        4
9674.0       4
4178.0       4
613.0        4
1195.0       4
1219.0       4
129.0        4
95.0         4
719.0        4
4018.0       4
7116.0       4
4104.0       4
19.0         4
1405.0       4
7157.0       4
125.0        4
8054.0       4
2273.0       4
9387.0       4
4062.0       4
2268.0       4
333.0        4
10005.0      3
9215.0       3
            ..
4131.0       1
3752.0       1
143.0        1
455.0        1
3408.0       1
7264.0       1
3964.0       1
393.0        1
275.0        1
9110.0       1
10073.0      1
371.0        1
2629.0       1
3630.0       1
3922.0       1
3961.0       1
3773.0       1
847.0        1
1279.0       1
4072.0       1
4137.0       1
409.0        1
4251.0       1
9229.0       1
4116.0       1
9124.0       1
1447.0       1
1955.0       1
1085.0       1
3710.0       1
9982.0       1
9107.0       1
8013.0       1
585.0        1
3430.0       1
1419.0       1
825.0        1
281.0        1
7098.0       1
563.0        1
9033.0       1
3932.0       1
1087.0       1
717.0        1
2271.0       1
583.0        1
9276.0       1
7103.0       1
1911.0       1
1435.0       1
1471.0       1
2193.0       1
7275.0       1
3491.0       1
751.0        1
449.0        1
459.0        1
645.0        1
873.0        1
8068.0       1
135.0        1
3552.0       1
7232.0       1
89.0         1
3417.0       1
2179.0       1
2063.0       1
2141.0       1
1823.0       1
1793.0       1
4125.0       1
9985.0       1
9916.0       1
7183.0       1
3747.0       1
1935.0       1
1582.0       1
713.0        1
453.0        1
364.0        1
573.0        1
811.0        1
4209.0       1
7179.0       1
500172.0     1
2293.0       1
2129.0       1
9839.0       1
2083.0       1
8037.0       1
2525.0       1
1441.0       1
1631.0       1
3558.0       1
9884.0       1
9126.0       1
4093.0       1
9877.0       1
9358.0       1
9230.0       1
Name: non_urban_intersection, Length: 506, dtype: int64

In [118]:
num_total = []
for inter in m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts().index:
    num_total.append(m_all[m_all['non_urban_intersection'] == inter].shape[0])
num_total - m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts()

1203.0      202
8015.0        8
867.0       254
57.0        770
2043.0      210
5.0         340
4071.0      172
317.0       252
58.0        243
325.0       103
2324.0       16
3497.0       31
4135.0       71
8017.0      221
4037.0       50
319.0        98
373.0       109
153.0        85
9378.0       40
4049.0      115
1083.0       90
4083.0       26
9736.0       32
1983.0       79
4197.0       49
475.0        27
641.0        37
1191.0       57
335.0       137
347.0        45
8055.0       84
1265.0       19
2169.0       33
1301.0       87
4043.0       41
639.0        83
4194.0       60
4182.0        6
8056.0       78
9470.0       26
4158.0       48
521.0        62
105.0        85
4189.0       43
3017.0       32
1137.0       30
3019.0       46
755.0        24
3898.0       15
1131.0       28
4223.0       42
361.0        60
831.0        89
4112.0       16
7095.0        9
536.0        15
683.0        53
863.0        32
3478.0       38
431.0        33
1421.0       17
8026.0       60
693.0        26
1161.0       87
4200.0       41
1317.0       34
1339.0      138
1621.0       43
91.0         77
1321.0        7
4177.0       61
445.0        12
9388.0        9
837.0        17
7289.0       30
1207.0       72
357.0        21
9674.0       27
4178.0       18
613.0        18
1195.0       32
1219.0      102
129.0         3
95.0         35
719.0       124
4018.0        8
7116.0       31
4104.0       27
19.0         16
1405.0       33
7157.0       14
125.0       142
8054.0       30
2273.0       31
9387.0       25
4062.0       53
2268.0        9
333.0        11
10005.0       5
9215.0        3
           ...
4131.0        3
3752.0        4
143.0         4
455.0        15
3408.0        2
7264.0        1
3964.0        1
393.0         0
275.0        20
9110.0        2
10073.0       6
371.0        27
2629.0        6
3630.0        2
3922.0       17
3961.0        2
3773.0        5
847.0         1
1279.0        1
4072.0       16
4137.0        0
409.0         5
4251.0       14
9229.0        2
4116.0        2
9124.0       20
1447.0       46
1955.0        4
1085.0       13
3710.0        8
9982.0        0
9107.0        0
8013.0       33
585.0         0
3430.0        0
1419.0       12
825.0         3
281.0         5
7098.0       16
563.0        13
9033.0        1
3932.0        8
1087.0       53
717.0        20
2271.0        7
583.0         1
9276.0        2
7103.0        8
1911.0        1
1435.0       17
1471.0       36
2193.0        6
7275.0        1
3491.0       18
751.0        15
449.0        31
459.0        19
645.0         0
873.0        14
8068.0       11
135.0        13
3552.0       11
7232.0        7
89.0         22
3417.0        4
2179.0        3
2063.0       29
2141.0       11
1823.0       11
1793.0       24
4125.0        0
9985.0        5
9916.0        1
7183.0        5
3747.0        3
1935.0        4
1582.0        3
713.0         2
453.0        33
364.0         3
573.0        28
811.0        21
4209.0      142
7179.0        2
500172.0      0
2293.0        2
2129.0        6
9839.0        0
2083.0       14
8037.0        0
2525.0        0
1441.0       36
1631.0       37
3558.0        3
9884.0        1
9126.0        9
4093.0        2
9877.0        4
9358.0        8
9230.0        2
Name: non_urban_intersection, Length: 506, dtype: int64

**Null Conclusion:** A lot of `non_urban_intersection` are missing, most of them only part of the instances translation missing. See details above.

**Specific values mistmatch investigations:** because of all the issues above, is it worth to investigate?

**Specific values conclusion:** because of all the issues above, not investigated

## accident_hour_raw and accident_hour_raw_hebrew

In [119]:
# accident_hour_raw                            720541 non-null int64
# accident_hour_raw_hebrew                     322739 non-null object
m_all[(m_all['accident_hour_raw'].isnull() == False) & (m_all['accident_hour_raw_hebrew'].isnull() == True)].shape

(397802, 98)

In [120]:
m_all[(m_all['accident_hour_raw'].isnull() == False) & (m_all['accident_hour_raw_hebrew'].isnull() == True)].describe()

,id,provider_and_id,provider_code,file_type_police,accident_type,accident_severity,location_accuracy,road_type,road_shape,day_type,police_unit,one_lane,multi_lane,speed_limit,road_intactness,road_width,road_sign,road_light,road_control,weather,road_surface,road_object,object_distance,didnt_cross,cross_mode,cross_location,cross_direction,road1,road2,km,km_raw,yishuv_symbol,geo_area,day_night,day_in_week,traffic_light,region,district,natural_area,municipal_status,yishuv_shape,street1,street2,house_number,non_urban_intersection,urban_intersection,accident_year,accident_month,accident_day,accident_hour_raw,accident_hour,accident_minute,longitude,latitude,x,y
count,3.978020e+05,3.978020e+05,397802.000000,0.0,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,39412.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,85412.000000,80670.000000,75067.000000,75067.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,332505.000000,397802.000000,332505.000000,331881.000000,332505.000000,306558.000000,36728.000000,272138.000000,2.034100e+04,3.566500e+04,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,397802.000000,391105.000000,391105.000000,391105.000000,391105.000000
mean,2.010373e+09,2.787766e+10,2.586729,NaN,4.660394,2.972235,2.573632,2.292776,8.453693,3.899493,30.892253,7.583471,0.222025,0.361258,0.154625,0.480646,4.635776,8.409709,3.745331,7.514138,7.519233,8.892457,8.954774,8.960629,0.111812,0.126261,8.785609,357.264178,227.871067,708.797794,702.635486,3872.595515,1.022798,1.900719,3.621659,8.209984,4.144503,52.814435,439.967973,15.881605,21.406289,798.539167,846.584486,8873.274405,1.693987e+04,1.495381e+07,2010.334666,6.414978,15.611686,57.444369,13.807482,18.216613,34.961033,32.173600,196438.996753,675609.760609
std,1.699263e+06,8.097839e+09,0.809784,NaN,4.070695,0.186378,1.864900,0.856325,0.599281,0.460079,17.877736,3.046661,0.761762,0.989774,0.380194,1.111834,0.803033,3.727153,2.303807,3.097870,3.091166,0.749012,11.090615,0.402947,0.598341,0.756089,1.263071,1293.786111,1113.374518,887.533084,892.419620,3224.154627,0.149258,1.670805,1.864584,2.470175,1.982409,28.038248,210.854392,37.029233,21.688890,1408.972819,1026.338245,3151.391876,1.214352e+06,2.215021e+07,1.702766,3.433666,8.800403,17.822809,4.469288,16.574951,0.214888,0.488207,20295.414062,54119.659743
min,2.008005e+09,1.200800e+10,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-478.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,11.000000,111.000000,0.000000,9.000000,0.000000,0.000000,-40.000000,0.000000e+00,1.000000e+00,2008.000000,1.000000,1.000000,25.000000,6.000000,0.000000,34.260947,29.493021,129666.000000,378409.000000
25%,2.009029e+09,3.200803e+10,3.000000,NaN,2.000000,3.000000,1.000000,2.000000,8.000000,4.000000,14.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,6.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,4.000000,0.000000,100.000000,99.000000,171.000000,1.000000,1.000000,2.000000,9.000000,3.000000,31.000000,311.000000,0.000000,13.000000,0.000000,239.000000,9999.000000,3.670000e+02,7.020003e+06,2009.000000,3.000000,8.000000,42.000000,10.000000,0.000000,34.798111,31.920457,180900.000000,647540.000000
50%,2.010055e+09,3.200908e+10,3.000000,NaN,3.000000,3.000000,2.000000,2.000000,8.000000,4.000000,20.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,40.000000,0.000000,330.000000,330.000000,4000.000000,1.000000,1.000000,4.000000,9.000000,4.000000,51.000000,431.000000,0.000000,14.000000,309.000000,507.500000,9999.000000,1.207000e+03,8.980009e+06,2010.000000,6.000000,16.000000,57.000000,14.000000,15.000000,34.892348,32.082155,189989.000000,665500.000000
75%,2.012022e+09,3.201106e+10,3.000000,NaN,5.000000,3.000000,3.000000,2.000000,9.000000,4.000000,51.000000,9.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,6.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.000000,0.000000,9.000000,85.000000,0.000000,1020.000000,1020.000000,6900.000000,1.000000,1.000000,5.000000,9.000000,5.000000,62.000000,512.000000,0.000000,16.000000,920.000000,1010.000000,9999.000000,3.698000e+03,1.490082e+07,2012.000000,9.000000,23.000000,71.000000,17.000000,30.000000,35.109624,32.568032,210554.000000,719327.000000
max,2.013062e+09,3.201306e+10,3.000000,NaN,20.000000,3.000000,9.000000,4.000000,15.000000,4.000000,61.000000,9.000000,5.000000,7.000000,4.000000,5.000000,5.000000,11.000000,7.000000,9.000000,9.000000,9.000000,1462.000000,9.000000,9.000000,9.000000,9.000000,9999.000000,9999.000000,9999.000000,9999.000000,9800.000000,2.000000,5.000000,7.000000,9.000000,9.000000,99.000000,999.000000,999.000000,99.000000,9999.000000,9998.000000,11111.000000,1.000000e+08,1.000000e+08,2013.000000,12.000000,31.000000,96.000000,23.000000,45.000000,35.845466,33.293023,279412.000000,799843.000000

In [121]:
m_all[(m_all['accident_hour_raw'].isnull() == False) & (m_all['accident_hour_raw_hebrew'].isnull() == True)]['accident_hour_raw'].value_counts()

65    12903
33    12269
69    12125
57    11918
49    11206
73    10993
53    10980
61    10787
67    10518
63    10179
55     9835
35     9660
71     9616
45     9526
31     9172
59     9114
51     8968
41     8902
37     8778
77     8219
75     8005
47     7733
32     7401
43     7381
39     7350
81     6702
79     6071
34     5498
83     5252
85     5242
29     5182
66     4800
70     4340
89     4192
64     4145
68     4114
30     4107
62     4042
36     4036
54     4011
87     3988
58     3770
72     3669
74     3571
56     3533
52     3405
50     3365
93     3271
38     3249
60     3217
27     3109
91     3050
48     3018
46     2918
42     2918
76     2764
78     2735
95     2687
40     2634
44     2504
28     2458
82     2240
80     2180
25     1836
84     1630
86     1614
96     1467
26     1287
90     1233
88     1193
94     1061
92      956
Name: accident_hour_raw, dtype: int64

**Null Conclusion:** Half the values of missing, a lot of different views. See details above

**Specific values mistmatch investigations:** not investigated because of all the issues above

**Specific values conclusion:** not investigated because of all the issues above